### ISSUE TITLE
[BUG] Issues with Model Error Analysis display and conditions

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1021]
**Describe the bug**
Bugs raised by @shir22 - 
1. Error values are very high, needs to be checked
2. Condition says that decrease in performance is 8%, while the decrease in performance from accuracy 1 to accuracy 0.75 is larger. 
Apart from that - the units (and nature) of the Error y axis is not clear and should be elaborated in the display.

**To Reproduce**
See Model Error Analysis results in the iris example https://docs.deepchecks.com/en/stable/examples/guides/quickstart_in_5_minutes.html

**Screenshots**
![image](https://user-images.githubusercontent.com/17730502/158339480-d9334612-3710-490e-9bed-9e75c1a20e80.png)
![image](https://user-images.githubusercontent.com/17730502/158339524-273ac17c-e429-45d6-b803-7bfa4185f470.png)

**Comment by shir22** [comment]
one additional comment - add to title of display the word "feature:"
so it will be Segmentation of error by feature: petal width (cm)
