### ISSUE TITLE
[BUG][CV] Refactor usage of `n_samples_per_class` out of `initalize_run`

### ISSUE THREAD

**Issue by matanper** [deepchecks/deepchecks#1022]
**Describe the bug**
When calling `n_samples_per_class` we generate a second iteration over the data. in order to combine the big update loop with the n_samples_per_class aggergation we need to remove the usage of it from `initalize_run` and only use it in `compute` after the update loop ended.

1. Refactor `n_samples_per_class` out of the following checks initalization:
- [x] HeatmapComparison
- [x] ConfusionMatrixReport
- [x] SimpleModelComparison

2. 
- [x] Add method "update_cache" on the VisionData which accepts batch and updates the `n_samples_per_class` cache, and call it in the update_loop of suite and in run loops of checks.

**Comment by noamzbr** [comment]
Regarding the second task, @yromanyshyn please update if this is resolved by the solution to #985.
