### ISSUE TITLE
[FEAT] [CV] Add support for image detection with segmentation 

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1039]
**Is your feature request related to a problem? Please describe.**
 Add support for image detection with segmentation 

**Describe the solution you'd like**
We just need a more general IoU and area functions and a new data type that inherits from detection data with a new label and prediction validation

**Describe alternatives you've considered**
A custom data object

**Comment by noamzbr** [comment]
In the first stage, use the existing custom segmentation defined in plot_custom_task_tutorial to:
Extend the IoU-based detection metrics to work for segmentation - main issue is defining IoU such that it works for segmentation maps
Add a VisionData based on MyCustomSegmentationData to the package core, add format validations and everything else needed for segmentation support (format definition, validation, tests)
Add an example of using deepchecks for segmentation.
Add segmentation specific metrics

**Comment by nirhutnik** [comment]
1. Start from 2nd bullet - create infra
2. Continue with 4th bullet - Create Dice metric (prediction X true)
3. Plan next steps

**Comment by nirhutnik** [comment]
Continued by #1888
