### ISSUE TITLE
[BUG] Warning has been seen to appear below OK checks in suite condition table

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1067]
**Describe the bug**
In a certain case, the condition table has been seen to have a warning appear blow the OK checks

**Expected behavior**
Condition order in the table should be:
Fail with Display
Fail without Display
Warning with Display
Warning without Display
Pass with Display
Pass without Display

Other then that order should conform to order of checks in the check_result. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17730502/159263773-6c2acb34-5648-44c8-8447-c6837f8840f0.png)
![image](https://user-images.githubusercontent.com/17730502/159263786-393647e8-d3ac-4b04-a8f8-51079b6da8a8.png)

**Comment by JKL98ISR** [comment]
fixed in #928 because it was cause by using category warn but pass=true

**Comment by JKL98ISR** [comment]
I was mistaken
