### ISSUE TITLE
[FEAT] Mixed Nulls - catch mixed nulls on non string columns (np.NaN/pd.NaN/Null/None/etc.)

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1074]
**Docs**

API Reference should include what are the DEFAULT NULLS that are checks (currently this can be found only by going into source)
Example notebook can also print out these nulls for convenience.

**Null Types**
1. NaT nulls not caught @chelseatroy can you elaborate?
3. Seems that list currently includes only strings (and null character). Does this catch also null objects? (e.g. the python None. Numpy and pandas nulls. or any other null that is likely to find it's way due to multiple feature engineering backends)

**Comment by chelseatroy** [comment]
I can elaborate!

`NaT` is what you get when you convert a sequence of values that contains timestamps, with some `None`s, to a pandas column. It stands for "not a timestamp". When I have a column with some `NaT`s, some timestamps, and some `None`s, the "Mixed Nulls" check still passes.

**Comment by chelseatroy** [comment]
I have confirmed that having the string 'null' and `None` also doesn't trigger Mixed Nulls:
<img width="941" alt="Screen Shot 2022-03-21 at 6 16 36 PM" src="https://user-images.githubusercontent.com/5744164/159383066-ae17b867-1654-48c8-b553-365a6e7e1d4c.png">

**Comment by shir22** [comment]
Updating here about this issue after some further investigation:

Mixed Nulls catches only **string nulls** ('none', 'nan', etc...). Also the documentation states that.
@noamzbr is there a specific reason that we implemented it only for those type of "nulls"?
The check can be more useful if it would catch various types of null representations... (e.g. python None, nump/pandas nulls, other types of null formats as they may arrive and be formatted from various data sources, etc.)

**Comment by noamzbr** [comment]
It also does catch np.NaN, but that's it. Agree that we should support also the various pandas nans and python None. 
We also do limit this check to columns of dtype pd.StringDtype, and I can't recall why. Probably can drop this requirement.

Only thing I would like to clarify - what do you mean by "other types of null formats as they may arrive and be formatted from various data sources, etc.)"? How can we catch other types of nulls we don't know about (except if they get casted earlier into numpy/pandas/python types)?

**Comment by chelseatroy** [comment]
@noamzbr good question, and we might have to find those by dint of folks running datasets through and seeing what doesn't catch. I do think it would be a good start to make this catch the nulls and Python `None` that we know about, and expand the check also to include other column types than the string ones, and that might cover a lot of cases.

**Comment by shir22** [comment]
Agree with both of your comments...

(btw what I meant in "other types" is to check existing nulls that we know of, not those that we don't know of :). for example - if we query with SQLAlchemy and there is a NULL value there, then how will it appear)
