### ISSUE TITLE
[BUG] save_as_html returns blank html files

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1118]
**Describe the bug**
Running save_as_html returns an empty, blank HTML file.

**To Reproduce**
run plot_detection_tutorial 

**Related to**
Probably related to the fix attempted in #1092

**Comment by shivshankardayal** [comment]
`plot_detection_tutorial.py` does not generate blank HTML file. Try re-running it from `main` branch again.

**Comment by shivshankardayal** [comment]
`plot_detection_tutorial.py` does not generate blank HTML file. Steps to figure out(from `main` branch):

Run `python source/tutorials/vision/plot_detetection_tutorial.py` from `docs` folder. It will save non-blank `output.html` in `docs` folder.

**Comment by JKL98ISR** [comment]
opened issue #1123 instead
