### ISSUE TITLE
[BUG] [CV] many metric/property related checks causing division by zero if the model has bad performance

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1123]
**Describe the bug**
many metric/property related checks causing division by zero if the model has bad performance.
this also causing json encoding fails for the plotly graphs.

**To Reproduce**
run plot_detection_tutorial
 or a model that predict everything wrong

**Expected behavior**
a raised error or a default value such as -1/0

**Screenshots**
![Screen Shot 2022-03-28 at 14 28 16](https://user-images.githubusercontent.com/26321553/160389107-45f3e65c-a963-4703-ac98-4f9f0505047e.png)

**Comment by shivshankardayal** [comment]
JSON encoding failing is an issue in `ipywidgets` when it dumps data in JSON format. If JSON has NaN or Inf it will not generate valid JSON.
