### ISSUE TITLE
[BUG] [CV] Image property drift graphs are empty when no drift

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1129]
**Describe the bug**
 Image property drift graphs are empty when no drift

**To Reproduce**
Run the check on data with same image sizes

**Expected behavior**
To not show the graphs

**Screenshots**
![Screen Shot 2022-03-29 at 16 15 17](https://user-images.githubusercontent.com/26321553/160619851-87d50ebe-af6c-4c24-bbc7-a4e2b4705af9.png)

**Comment by shir22** [comment]
Seems like there is a more general bug - in the probability density plot (regardless of drift/no drift)
Is it cause from only a single value in both datasets and thus no "distribution" plot?)
