### ISSUE TITLE
[BUG] [CV] drift plots unclear when there are many classes

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1138]
**Describe the bug**
the plot makes it look like there is a bug in the classes recognition and the "other" column isn't clear

**To Reproduce**
run the label/prediction drift check on a dataset with many classes

**Expected behavior**
explain better what the other means or remove the other column so the columns will look at a normal height 

**Screenshots**
![Screen Shot 2022-03-30 at 16 32 17](https://user-images.githubusercontent.com/26321553/160862783-f0b7f380-d7ae-482f-b14b-e735a663442d.png)

![image](https://user-images.githubusercontent.com/9868530/161554751-69316a04-c089-4e1e-9ac1-a6eee850aa8e.png)

**Comment by noamzbr** [comment]
This goes deeper - need to re-consider how PSI is used for many categories case.
Simple solution path: do drift the same way, but for display display the most drifted categories.
Complex solution: Use something other than PSI

At any rate - need to make clearer that the "Other" is a grouping of all others.
