### ISSUE TITLE
[BUG] [CV] add label map to conditions

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1140]
**Describe the bug**
Unclear what classes passed or didn't passed the condition because it uses the label id

**To Reproduce**
run class performance check

**Expected behavior**
have label map in the condition 
(dev comment: a bit hard to implement as a feature but as a user it was very unclear)

**Screenshots**
![Screen Shot 2022-03-30 at 16 41 16](https://user-images.githubusercontent.com/26321553/160864039-d8a4830f-1f09-4bdc-b3fa-e0377b7fcf10.png)

**Comment by shir22** [comment]
Suggestion: add both label id and label string (map) in all places where class-related displays exist (graphs, conditions, etc.)

**Comment by matanper** [comment]
Why do we need the map inside the condition? in the check output we need to already have the class as the name
