### ISSUE TITLE
[FEAT][CV] Don't display heatmap comparison when avg images are nearly identical

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1144]
**Is your feature request related to a problem? Please describe.**
When avg images are nearly identical, the plot shows two nearly identical images and then a black image. That carries no information and is confusing.

**Describe the solution you'd like**
Define a threshold on the diff (e.g. max pixel value in diff) and don't display if below threshold.

**Comment by JKL98ISR** [comment]
@shir22 it's problematic because we still want to show the other images and we can't leave it blank if we have a difference in bbox.
