### ISSUE TITLE
[FEAT] Model Error Analysis on 2d segments

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1167]
**Is your feature request related to a problem? Please describe.**
detect 2d segments the model preforms badly on and display it to user. Currently only showcased on a single feature

**Describe the solution you'd like**
Such segments can be found using 2 levels deep decision trees trained on model train data with the model error as labels.

**Comment by nirhutnik** [comment]
Already implemented a long time ago in #1678
