### ISSUE TITLE
[FEAT] new check - outlier detection

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1168]
**Is your feature request related to a problem? Please describe.**
A check to find outliers in a single tabular data set. Main scenario can be as part of the data integrity suite to check for possible pitfalls before the training procedure.

**Describe the solution you'd like**
Implement the LoOP algorithm and show case examples with highest outlier score + relevant conditions.

**Comment by shir22** [comment]
@Nadav-Barak can you add some context?
is this for tabular data? what is the typical usage / need?

**Comment by Nadav-Barak** [comment]
@shir22 Edited the description.
In addition in the future we can discuss adding a check whether an example in the test (set / incoming stream) in an outlier in comparison to the train data.
