### ISSUE TITLE
[FEAT] Attach exception traces to suite result. 

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1169]
**Is your feature request related to a problem? Please describe.**
Currently it's often hard to debug exceptions in checks running as parts of suites - all you can see is the error message. 

**Describe the solution you'd like**
Attach the exception trace as part of the result object.

**Comment by benisraeldan** [comment]
as part of the result object, or as part of the display? The exception already exists as part of the object (CheckFailure has the exception inside) so either make it easier to get, or the display itself.

**Comment by benisraeldan** [comment]
If we want this to be displayed, then I suggest a hidden (collapsible) section where the traces are available to be looked at (e.g. an arrow at the end of each check of `checks that did not run` section so a user can look at the trace. @JKL98ISR  is this something that is possible?

**Comment by JKL98ISR** [comment]
close to impossible rn (the table is just a df). I think we can just add an error print function that loops over the checkfalures and shows the stack traces with the check title

**Comment by benisraeldan** [comment]
suit_result.get_errors() and adding a print that tells the user that this exists?
