### ISSUE TITLE
[BUG] Check failure when working on GPU

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1171]
**Describe the bug**
When working on GPU devices, I get the following error on most of the checks:
![image](https://user-images.githubusercontent.com/20860465/161489114-f81ccc58-a89e-4aad-8ac0-16178e6e2f5e.png)

**To Reproduce**
Open this notebook on GPU:
https://www.kaggle.com/code/itay94/notebook1b0b03205f

**Environment (please complete the following information):**
 - OS: Kaggle
 - Python Version: Kaggle kernel
 - Deepchecks Version: 0.6.0

**Additional context**

**Comment by JKL98ISR** [comment]
can you run per check and add full stack trace?

**Comment by ItayGabbay** [comment]
It happened because my batch_to_images returned the images in the GPU.
We need to validate that the tensors returned are on the CPU, and if not - move them to the CPU.

**Comment by JKL98ISR** [comment]
we are not responsible to the code you wrote in batch_to_images and we cannot fix it

**Comment by noamzbr** [comment]
As @ItayGabbay said, we can't fix it but we can and should alert that the tensors are on gpu in our validation mechanism.
