### ISSUE TITLE
[FEAT][CV] How should I run on a sample?

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1175]
**Is your feature request related to a problem? Please describe.**
Currently, it is not clear how a user should run the suites on a sample of the data. It should be loud and clear in the code, our examples, and in the docs.

**Comment by shir22** [comment]
Two different topics - 
1. It should be clear how to run on sample / on all (in code, examples, docs)
2. What is the default... -> this depends on run times IMO + what is the likelihood of the sampling to be bias... (referring to our discussions about inability to shuffle & sample randomly?)
@noamzbr WDYT? (also - if we sample, shouldn't be bigger, e.g. for a use case of 100 classes 10K samples will be small...)
