### ISSUE TITLE
[BUG] [CV] Image property drift - fix error

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1184]
**Describe the bug**
fix error in image property drift

**To Reproduce**
1. Go to https://www.kaggle.com/code/itay94/notebookc2fb7a0a35

**Screenshots**
![image](https://user-images.githubusercontent.com/20860465/161570603-b7535655-1beb-4aa0-b7a7-4c7d56d17b94.png)

**Environment (please complete the following information):**
 - OS: Kaggle
 - Python Version: Kaggle
 - Deepchecks Version: 0.6.0

**Comment by shir22** [comment]
and shouldn't fail condition...

**Comment by noamzbr** [comment]
Desired remedy:
1. Condition should not try to run if there is no output to run on
2. There should be a forth state of condition, signifying a python exception and outputting the exception.
