### ISSUE TITLE
[BUG] [CV] Image segment performance visualization

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1186]
**Describe the bug**
Unable to read the text

![image](https://user-images.githubusercontent.com/20860465/161699240-cd2b9ece-0200-4e82-8ebf-db5c97767de1.png)

**Comment by noamzbr** [comment]
Actually, this check display is in need of a general remake. 
Things to remake:

1. Different name and wording (segments is confusing for vision)
2. When there is only a single value we should understand that.
3. Try to think of a clearer way to display percentile segments.
4. Also, nicer looking plots.

**Comment by JKL98ISR** [comment]
we should add x-axis label and fix the overlapping

**Comment by noamzbr** [comment]
Suggestion:
1. Use only a single metric (AP for detection, f1 for classification)
2. Show 2 property plots per line (so they have proper width)
3. Show only n_top most "variable" properties, sorted by variance or by max_performance - min_performance. 
4. Don't show properties with a single value
Extra suggestion that people may not like - color the bars according to their height, so that low bars (weak segments) are redder and high bars (good segments) are greener.

**Comment by JKL98ISR** [comment]
> Suggestion:
> 
> 1. Use only a single metric (AP for detection, f1 for classification)
> 2. Show 2 property plots per line (so they have proper width)
> 3. Show only n_top most "variable" properties, sorted by variance or by max_performance - min_performance.
> 4. Don't show properties with a single value
>    Extra suggestion that people may not like - color the bars according to their height, so that low bars (weak segments) are redder and high bars (good segments) are greener.

4 is indeed to much

**Comment by JKL98ISR** [comment]
> Suggestion:
> 
> 1. Use only a single metric (AP for detection, f1 for classification)
> 2. Show 2 property plots per line (so they have proper width)
> 3. Show only n_top most "variable" properties, sorted by variance or by max_performance - min_performance.
> 4. Don't show properties with a single value
> 5. Extra suggestion that people may not like - color the bars according to their height, so that low bars (weak segments) are redder and high bars (good segments) are greener.

5 is indeed too much

**Comment by noamzbr** [comment]
Also let's rename AP to Average Precision...

**Comment by JKL98ISR** [comment]
> Also let's rename AP to Average Precision...

it's a really big change
