### ISSUE TITLE
[BUG] jaccard_iou takes a large chunk of the runtime

### ISSUE THREAD

**Issue by benisraeldan** [deepchecks/deepchecks#1187]
**Describe the bug**
892.728 <module>  ../../tmp/ipykernel_34/1659815497.py:7
└─ 892.726 run  deepchecks/vision/base_checks.py:45
      [2669 frames hidden]  deepchecks, ignite, <built-in>, torch...
         723.237 jaccard_iou  deepchecks/vision/metrics_utils/iou_utils.py:18

jaccard_iou gets called many times during a run, so even though it's a simple calculation, we want to improve it's run time by using numpy

**Expected behavior**
reduced runtime.

**Environment (please complete the following information):**
 - OS: Kaggle
 - Python Version: 3.8
 - Deepchecks Version: 6.1

**Comment by noamzbr** [comment]
Numpy vectorization should be done at:
1. Confusion matrix - list_of_ious
2. iou_utils - compute_pairwise_ious

Do timing before the modification and after. If this won't improve enough, can consider numba.
