### ISSUE TITLE
[BUG][CV] example code is not tested on gpu

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1200]
**Describe the bug**
Example code is tested only on cpu. If it was tested on gpu, we would have noticed that the line:
`result = suite.run(training_data, val_data, model, device)
`
In plot_detection_tutorial places the device in the wrong place / without a keyname.

**To Reproduce**
Run plot_detection_tutorial  on gpu

**Comment by ItayGabbay** [comment]
imo it's not that the examples should run on the GPU, but the suites tests should run on GPU. 
I think @JKL98ISR has already fixed that. correct?
