### ISSUE TITLE
[BUG] [User report] A lot of white lines in a suite

### ISSUE THREAD

**Issue by matanper** [deepchecks/deepchecks#1203]
**Describe the bug**
When running suite there are a lot of white horizontal lines in the display

![image](https://user-images.githubusercontent.com/9868530/161949480-d0c962bf-533a-4ad5-af6e-74189fa1cb7d.png)

**Environment (please complete the following information):**
Jupyterlab with Python 3.6

**Comment by JKL98ISR** [comment]
couldn't recreate

**Comment by yromanyshyn** [comment]
@JKL98ISR 

>couldn't recreate

jupyterlab-plotly extension that is used to display plotly figures in jupyterlab env is incompatible with plotly version >5.5.0 therefore plots are not displayed - that is my assumption
