### ISSUE TITLE
[BUG] deepchecks version number

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1206]
version not working (see image)

reproduce steps:
create new virtual environment

pip install deepchecks

and then run
```
import deepchecks
deepchecks.__version__
```
in notebook
![image](https://user-images.githubusercontent.com/33841818/161975232-7d009ff3-1f96-4adc-9318-ad611bf9736b.png)

**Comment by ItayGabbay** [comment]
Fixed by #1204
