### ISSUE TITLE
[BUG] to_wandb not sectioning by train/test and overrides runs by checks

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1210]
**Describe the bug**
 to_wandb not sectioning by train/test and overrides runs by checks

**To Reproduce**
run a suite with train/test checks and duplicate checks in suite

**Expected behavior**
sections for each dataset and being able to run a suite with a couple of checks

**Screenshots**

**Comment by shir22** [comment]
Initial fix -  from 'name' to 'header', already applied in my local deepchecks environment (screenshots after that fix)

See example (note both DataDuplicates and CalibrationScore behavior):

Code that ran:
`custom_suite = Suite('Custom Evaluation',CalibrationScore(), CalibrationScore(),
                     DataDuplicates(), DataDuplicates(columns=['Total Value']))
suite_res = custom_suite.run(train_ds, test_ds, rf_clf)
suite_res.to_wandb(project=PROJECT_NAME, entity=ENTITY_NAME, name="my_run")`

### Suite Result
#### Calibration Metric
![image](https://user-images.githubusercontent.com/33841818/162167715-0db6398d-4822-4e35-a886-741753982ab5.png)

#### Data Duplicates - 
![image](https://user-images.githubusercontent.com/33841818/162167770-5e0450ce-a2ff-493f-8495-8779379d7a86.png)

### W&B Logging Result
#### Data Duplicates - appears 3 times (??)
![image](https://user-images.githubusercontent.com/33841818/162168073-f79f6f3b-33fc-4453-8aff-4ae47652e979.png)


#### Calibration Metric
Only one result (for each, after the above fix applied):
![image](https://user-images.githubusercontent.com/33841818/162169354-b810fb42-2422-4ab5-8e5e-1bd377609fa0.png)
