### ISSUE TITLE
[FEAT] Additional information for checks that do not produce output - "nothing found" 

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1238]
**Is your feature request related to a problem? Please describe.**
1. The output "nothing found" can represent different scenarios, from did nothing to check ran as intended and no issues were found. 
2. Some checks can display a general warning massage that cover both the case in which a dataframe was passed instead of a dataset and the case where a dataset without the relevant properties was passed. 

**Describe the solution you'd like**
1. a more detailed description on what has occurred, for example "no new categories were found in the test set for columns ..."
2. Save a boolean in self that specify whether a df was passed and display warning massages based on boolean.

**Comment by matanper** [comment]
about 2: decided to just have the same behavior if user passes a df, and add a warning in the context init
