### ISSUE TITLE
[FEAT][USE] Streamlit demo app of the package

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1255]
In order to demonstrate the value of the package, we want to create a simple demo web application that will enable users to explore the functionalities of different checks. We can take inspiration from https://albumentations-demo.herokuapp.com

 The first checks we will implement will be:

- [ ] Feature & Label Drift
- [ ] String Mismatch
- [ ] Data Duplicates
- [ ] Segment Performance 

In all of these, we will enable choosing from different datasets, have UI widgets to mess with the data in order to show the check's value

**Comment by matanper** [comment]
which datasets? what is "mess with the data"?
