### ISSUE TITLE
[FEAT][Vision] FastAI integration

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1257]
**Describe the solution you'd like**
Currently our vision package supports only torch models and datasets. Since FastAI is a widely used package that is **based on torch**, I suggest we should have a simple integration mechanism to fastai datasets and models.

https://docs.fast.ai/

**Comment by noamzbr** [comment]
A quick look shows that fast ai can work either with native torch objects inside it's learners and Dataloaders objects, or with their own native FastAI objects, which I can't tell from a first glance if they are implemented by pytorch underneath.

The first part of this task would be exploring FastAI and suggesting the best integration architecture, together with a functioning demo - meaning a single case in which we got the full suite to run on the fastAI objects. Actually adding integration and docs to the package will come in the next step.
* Make sure to present in the demo integration in the case of FastAI wrapping pytorch objects vs the case of FastAI using their own objects.

**Comment by matanper** [comment]
from the [fast.ai docs](https://docs.fast.ai/data.load.html#DataLoader)

> fastai includes a replacement for Pytorch's DataLoader which is largely API-compatible, and adds a lot of useful functionality and flexibility. 

Their DataLoader is indeed largely compatible with pytorch's DataLoader but there is difference in the way the batch sampling works, which we currently relay on in order to do sampling and to be able to get specific item using it batch index (the connection between the index we saw it in the batch to the real index in the Dataset)

**Comment by JKL98ISR** [comment]
> from the [fast.ai docs](https://docs.fast.ai/data.load.html#DataLoader)
> 
> > fastai includes a replacement for Pytorch's DataLoader which is largely API-compatible, and adds a lot of useful functionality and flexibility.
> 
> Their DataLoader is indeed largely compatible with pytorch's DataLoader but there is difference in the way the batch sampling works, which we currently relay on in order to do sampling and to be able to get specific item using it batch index (the connection between the index we saw it in the batch to the real index in the Dataset)
what if we will do it without sampling? (sampling only when supported)

׳י

**Comment by JKL98ISR** [comment]
> from the [fast.ai docs](https://docs.fast.ai/data.load.html#DataLoader)
> 
> > fastai includes a replacement for Pytorch's DataLoader which is largely API-compatible, and adds a lot of useful functionality and flexibility.
> 
> Their DataLoader is indeed largely compatible with pytorch's DataLoader but there is difference in the way the batch sampling works, which we currently relay on in order to do sampling and to be able to get specific item using it batch index (the connection between the index we saw it in the batch to the real index in the Dataset)

what if will not do sampling on it? (only sample when we can)

**Comment by matanper** [comment]
> what if will not do sampling on it? (only sample when we can)

A lot of the code in VisionData relies on it, and a lot of tests use the "get specific item using it batch index"

**Comment by matanper** [comment]
Found hack to wrap Fast.AI's Dataset in torch's DataLoader:

```
from torch.utils.data import DataLoader as torch_dataloader

def fa_dataloader_to_torch(dl):
  def collate(items):
    items = [dl.after_item(i) for i in items]
    return dl.do_batch(items)
  return torch_dataloader(dl.dataset, collate_fn = collate, batch_size=dl.bs)
```

Notebook of running fast.ai & deepchecks on the pets dataset:
https://colab.research.google.com/drive/1wBgwvTi-zJEUJ8i8aCHYIZx23KYBfeYH?usp=sharing

**Comment by matanper** [comment]
Opened follow-up issue #1314
