### ISSUE TITLE
[BUG] Maximum feature cardinality in WholeDatasetDrift is not configurable

### ISSUE THREAD

**Issue by JZschache** [deepchecks/deepchecks#1265]
**Describe the bug**
When running the WholeDatasetDrift on a dataset with a feature that has cardinality greater then 255, the following error is thrown by the HistGradientBoostingClassifier:

```
/usr/local/lib/python3.9/dist-packages/sklearn/ensemble/_hist_gradient_boosting/gradient_boosting.py in _check_categories(self, X)
    186 
    187                 if categories.size > self.max_bins:
--> 188                     raise ValueError(
    189                         f"Categorical feature at index {f_idx} is "
    190                         "expected to have a "

ValueError: Categorical feature at index 30 is expected to have a cardinality <= 255
```

There is no way to adjust the max_bins parameter of HistGradientBoostingClassifier. Alternatively, the feature cardinality could be reduced before training the HistGradientBoostingClassifier using the max_num_categories parameter of WholeDatasetDrift

**Comment by noamzbr** [comment]
Thanks @JZschache for catching an important bug! Will be added to our next milestone. 

**Proposed Solution**

1. As @JZschache suggested, group together minor categories using max_num_categories or 255 before passing to HistGradientBoostingClassifier. Make sure to apply the same grouping (generated solely on the train split) to the test split. 
2. Add an explicit test for that.

**Comment by nirhutnik** [comment]
### DoD:
Bug resolved and fix is in main.

### Logic:
Either add "other" category (can use "rare encoder" from old code) or target encode the categorical variable if its cardinality > 255

### Tasks:
* Decide on solution
* Implement
* Add test
