### ISSUE TITLE
[BUG] Fix Earth Mover's drift for distributions with outliers

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#1276]

**Comment by nirhutnik** [comment]
TBD

**Comment by nirhutnik** [comment]
`    dist1_qt_min = np.quantile(dist1, 0.01)
    dist1_qt_max = np.quantile(dist1, 0.99)
    dist2_qt_min = np.quantile(dist2, 0.01)
    dist2_qt_max = np.quantile(dist2, 0.99)
    dist1 = dist1[(dist1_qt_max > dist1) & (dist1 > dist1_qt_min)]
    dist2 = dist2[(dist2_qt_max > dist2) & (dist2 > dist2_qt_min)]

    val_max = np.max([np.max(dist1), np.max(dist2)])
    val_min = np.min([np.min(dist1), np.min(dist2)])
`

**Comment by nirhutnik** [comment]
Code that doesn't produce drift with regular EMD but produces drift with the modified version (Thanks @matanper ):

`import numpy as np
from deepchecks.tabular.checks import TrainTestFeatureDrift
from deepchecks.tabular.datasets.regression import avocado

column = 'Total Volume'

train, test = avocado.load_data(as_train_test=True)

# Insert drift
mean = 3
std = 3

test.data[column] = test.data[column] + np.abs(np.random.normal(mean, std, size=(len(test))) * np.average(test.data[column]))

check = TrainTestFeatureDrift(columns=[column]).add_condition_drift_score_not_greater_than()
result = check.run(train, test)

print(result)`

**Comment by noamzbr** [comment]
@nirhutnik Note that also the categorical drift PSI seems a bit underwhelming. Look at: https://checks-demo.deepchecks.com/?check=Train+Test+Feature+Drift, select avocado and column "region". May this be solved by #1272 ?

**Comment by nirhutnik** [comment]
@noamzbr Yes, it may, as there are many categories in this case.
