### ISSUE TITLE
[FEAT] Add option to save as md files - cml integration

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1290]
**Background**
cml is a ci tool which for our purposes sends md files as comments in PRs. (its features as a runner is irrelevant).

**Is your feature request related to a problem? Please describe.**
We can currently save checks and suites as html, we need to add an option to save as md files too.
as for now we can send just the condition table easily but it is not really helpful.

**Implementation Details**
Mostly we need to remove any style blocks in the html and save the plots as an image (this part might make us use some git giles api).

**Comment by noamzbr** [comment]
Note - check option to demonstrate this capability with a ci/cd integration using dagshub

**Comment by bgalvao** [comment]
+1 today I was looking for this

**Comment by matanper** [comment]
Hey @bgalvao, we are not planning to work on this issue soon, but we'll be glad to get a contribution from you 😃 
@yromanyshyn wrote most of our serialization logic and will be happy to assist and direct you in case you are interested

**Comment by bgalvao** [comment]
@matanper I am interested yes :)

**_On plot figures_**
I am not super knowledgeable about what is accepted in GitHub's Markdown and GitLab's Markdown. The general gist of it is that javascript cannot be run - so no live Plotly figures can be there.

My difficulty on this point is understanding how to set the three parameters of `SuiteResult.save_as_html` - `as_widget`, `requirejs` and `connected` - so as to generate a javascript-free output. @yromanyshyn 

Note: GitHub however [accepts SVGs](https://github.blog/changelog/2022-01-21-allow-to-upload-svg-files-to-markdown/). GitLab is a maybe.

_**On toggles**_ ✨ 
I cannot find where the toggles are on the html output of `SuiteResult.save_as_html` - frankly overwhelmed. What I found [in this gist](https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61) is that the Markdown-friendly way is to to use the `<details>` tag.

**Comment by matanper** [comment]
Great, I'm assigning you this issue 😄 

I think that you won't need to use the `save_as_html` but instead create a completely new [serializer](https://github.com/deepchecks/deepchecks/blob/main/deepchecks/core/serialization/abc.py) for markdown output. 

@yromanyshyn do you have any input or suggestions?

**Comment by yromanyshyn** [comment]
@bgalvao 

you can try something like this in order to transform HTML output into markdown

```python
from deepchecks.tabular.datasets.classification.adult import load_data, load_fitted_model
from deepchecks.tabular.suites.default_suites import train_test_validation
from deepchecks.core.serialization.suite_result.html import SuiteResultSerializer as HtmlSerializer
import pypandoc

model = load_fitted_model()
train, test = load_data()
result = train_test_validation().run(train_dataset=train, test_dataset=test, model=model)

# will serialize result to HTML without javascript,
# all plotly figures will be transformed into embedded images
serialized_result = HtmlSerializer(result).serialize(
    full_html=False, 
    include_requirejs=False, 
    include_plotlyjs=False,
    plotly_to_image=True
)

markdown_output = pypandoc.convert_text(
    serialized_result, 
    to='md', 
    format='html'
)

with open("suite-reslt.md", "w") as f:
    f.write(markdown_output)
```

but I must say that it looks like pandoc has some troubles with HTML tables, markdown output with them`s does not look as expected/ 

in general, if you plan to show check/suite results within GitHub as part of CD/CD action then I think you probably do not need markdown, just use plain HTML, GitHub is able to render it

**Comment by bgalvao** [comment]
I put the result in a github gist [here](https://gist.github.com/bgalvao/2a9d59f29328e3096d6e4087e1bdb43c) for everyone to see how it behaves with GitHub.

`<img>` tags where the image is encoded directly into the src attribute are not being rendered.

**Comment by matanper** [comment]
Looks good, do you want to open a pull request which adds this as a function on suite result (`result.as_markdown()`)?

**Comment by bgalvao** [comment]
I do :) Give me some time though.
It's a shame the output is not being rendered as intended though :(

**Comment by yromanyshyn** [comment]
@bgalvao 

> <img> tags where the image is encoded directly into the src attribute are not being rendered.

it looks, like the same is true for markdown/?

if that is true if it is not possible to embed an image directly into the output then you need to upload an image somewhere to make it possible to display it

**Comment by matanper** [comment]
it seems like it isn't possible and won't be possible...
https://github.com/github/markup/issues/270

**Comment by bgalvao** [comment]
Alright, in GitLab CI

```yaml
test-data-split:
  stage: test
  image: $CI_REGISTRY_IMAGE
  script:
    - dvc pull
    - dvc repro test_data_split
    # full suite result upload using the ![]() syntax, also works with []() syntax
    - echo '- ![Train-Test Suite Results](data/deepchecks_reports/data_split/suite_result.html)' >> report.md
    # simplified conditions table
    - cat data/deepchecks_reports/data_split/conditions_table.html >> report.md
    - cml comment create report.md --publish --publish-native --pr
```

When you use the `--publish` and [`--publish-native`](https://cml.dev/doc/ref/comment#--publish-native) flags on the cml command, cml will handle uploading the file (`suite_result.html` in this case) to the Git platform you're using. The result is something like this:

![suite_result](https://user-images.githubusercontent.com/17158288/201095182-84e831f3-af65-4350-aed2-83860ee073ec.png)

And that hyperlink to the top is the attachment of the `suite_result.html`.

The PR I can make is a documentation one, referring to this. Additionally, I can add code to render a simple table with the top-level view of the conditions.

**Comment by bgalvao** [comment]
@matanper the attachment that is hyperlinked displays all the graphics, even with live plotly plots :) but the user has to download it first by clicking on it.

**Comment by matanper** [comment]
@bgalvao Awesome 🚀 

> code to render a simple table with the top-level view of the conditions

Is the purpose of this to have a preview without the need to click on the file?

Anyway, sound like it will be a great fit in our documentation under "Integrations" in a new CML page (under `docs/source/user-guide/integrations`). Feel free to ping as if you have questions about the docs

**Comment by bgalvao** [comment]
> Is the purpose of this to have a preview without the need to click on the file?

Yes. :)

@matanper, I finally posted a PR. I would like some tips on how to make my code compliant with the codebase. :)

**Comment by matanper** [comment]
Hey @bgalvao,

We have a make command `make pylint` which checks the basics of our code style, apart from that we will comment on anything specific in the PR 😃

**Comment by daavoo** [comment]
Jumping in from https://discord.com/channels/485586884165107732/563406153334128681/1043161204052459580

> <img> tags where the image is encoded directly into the src attribute are not being rendered.
> if that is true if it is not possible to embed an image directly into the output then you need to upload an image somewhere to make it possible to display it

If you:

-  serialize the encoded images to some local path 
- use an image tag in the markdown pointing to that local path
- Add the [`--publish`](https://cml.dev/doc/ref/comment#--publish) flag to `cml comment` 

CML will take care of uploading the images to a public hosting (`https://asset.cml.dev` by default, but [custom hosting can be provided](https://cml.dev/doc/ref/comment#--publish-url)) and the images should be correctly displayed in GitHub / GitLab.

**Comment by casperdcl** [comment]
> Add the [--publish](https://cml.dev/doc/ref/comment#--publish) flag to cml comment

Minor note: `--publish` is `true` by default, so not explicitly required.

**Comment by matanper** [comment]
@bgalvao what do you think about @daavoo and @casperdcl suggestions?

**Comment by casperdcl** [comment]
https://github.com/astanin/python-tabulate might help :)
