### ISSUE TITLE
[BUG] [DOCS] when entering a tutorial the tree on the left disappears 

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1295]
**Describe the bug**
when entering a tutorial the tree on the left disappears 

**To Reproduce**
Enter the Tutorials tab then click on any specific tutorial

**Expected behavior**
The tree on the left showing all available tutorials should be visible

**Comment by noamzbr** [comment]
Happens for the vision tutorials, not the tabular ones.
