### ISSUE TITLE
[BUG] "Read More" link in performance report (and perhaps others is broken)

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1301]
**Describe the bug**
Leads to 404 according to one of our users. 

**To Reproduce**
Run performance report, click the "Read More" link.

**Comment by matanper** [comment]
The links are generated with full package version (for example https://docs.deepchecks.com/0.6.1/examples/...), but we changed the API URL to not include the last part of the version so it should omit it and generated as "https://docs.deepchecks.com/0.6/examples/..."

**Comment by noamzbr** [comment]
Found that also links in the docs lead to 404, e.g. the one here https://docs.deepchecks.com/stable/examples/tabular/checks/performance/examples/plot_segement_performance.html
