### ISSUE TITLE
[FEAT] Improve wording in Label Ambiguity condition

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1302]
**Is your feature request related to a problem? Please describe.**
The current wording "Ambiguous sample ratio is not greater than 0%" is unclear.

**Comment by shir22** [comment]
Consider changing also the check name ("Label Ambiguity")

**Comment by noamzbr** [comment]
Suggested check name: Conflicting Labels
Suggested condition name: Ratio of samples with conflicting labels not greater than
