### ISSUE TITLE
[USE][DOCS] Example - using hugging face object detection pytorch model

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1310]

**Comment by noamzbr** [comment]
DoD:
A doc entry under user guide->Integrations (/"using deepchecks with", or however we call the section where the fast.ai example resides).

Example contains:
loading a model from https://huggingface.co/models, perhaps this one https://huggingface.co/microsoft/swin-tiny-patch4-window7-224. Use a dataset that will work out of the box with imagenet. Write a VisionData for it. Then compare performance to a normal pytorch imagenet model using the Class Performance check. Perhaps even compare across segments.
