### ISSUE TITLE
[FEAT] Support sklearn 0.23.2

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1311]
Currently we only support sklearn versions >= 1.0. We need to try to support the 0.23.2 as it is widely used by many environments and frameworks.

**Comment by JKL98ISR** [comment]
not 100% if it is solvable for all use cases as 0.23 is missing important parameters for some sklearn functions.
it affects only a small amount of checks too, mainly some drift scenarios

**Comment by JKL98ISR** [comment]
btw issue is a bit wrong, we have scikit-learn>=0.24.2 in the requirements
