### ISSUE TITLE
[FEAT] Default condition in UnusedFeatures should be on num of low FI features. 

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1320]
**Is your feature request related to a problem? Please describe.**
The current condition limits the number of unused features with high variance. The main use for this check though is to make sure that the features we're including actually contribute something to the model, so the condition should be on that.

**Comment by noamzbr** [comment]
Would suggest naming the condition 
add_condition_number_of_low_feature_importance_features_less_than
Dropped the double negative (as #1339 will do to all existing conditions), and don't think "unused" adds info here.

**Comment by matanper** [comment]
Not clear enough

**Comment by noamzbr** [comment]
Not planned
