### ISSUE TITLE
[FEAT] Change condition wording to not have double negation

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1339]
Instead of "not less than" have "greater than" and instead of "not greater than" have "less than".
Notice that this excludes the actual value itself, if problematic can add "or equal to".

Based on feedbacks for condition clarity.

**Comment by shir22** [comment]
related to #1338 as both are condition improvements

**Comment by noamzbr** [comment]
Major manual name change and test update. 

**Take Note:** some cases it's important if the condition excludes or includes the threshold. Note these cases and consider adding  "or equal to" as @shir22 mentioned, and feel free to discuss.
