### ISSUE TITLE
[BUG] TrainTestSamplesMix cannot deal with categorical data

### ISSUE THREAD

**Issue by JZschache** [deepchecks/deepchecks#1340]
**Describe the bug**
TrainTestSamplesMix throws error when dataset contains a categorical variable.

**To Reproduce**
Adding a categorical variable to the example from [Train Test Samples Mix Docu](https://docs.deepchecks.com/en/stable/examples/tabular/checks/methodology/examples/plot_train_test_samples_mix.html#)
```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from deepchecks.tabular.checks.methodology import TrainTestSamplesMix
from deepchecks.tabular import Dataset

iris = load_iris(return_X_y=False, as_frame=True)
X = iris.data

X["cat_column"] = X["sepal length (cm)"].astype("category")

y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=55)
train_dataset = Dataset(pd.concat([X_train, y_train], axis=1),
            features=iris.feature_names,
            label='target')

test_df = pd.concat([X_test, y_test], axis=1)
bad_test = test_df.append(train_dataset.data.iloc[[0, 1, 1, 2, 3, 4]], ignore_index=True)

test_dataset = Dataset(bad_test,
            features=iris.feature_names,
            label='target')

check = TrainTestSamplesMix()
check.run(test_dataset=test_dataset, train_dataset=train_dataset)
```

**Expected behavior**
Not throwing the following error: `TypeError: Cannot setitem on a Categorical with a new category (__deepchecks_na_filler__), set the categories first`

**Comment by matanper** [comment]
Thanks

Looks like the problem is `pandas.fillna` fails when there are category columns. We either need to run fillna only on non-catgeorical columns, or add "__deepchecks_na_filler__" as category (`df[col].cat.add_categories('__deepchecks_na_filler__')`)
