### ISSUE TITLE
[BUG] [CV] many warnings while running detection metric

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1343]
**Describe the bug**
many warnings while running detection metric

**To Reproduce**
run the metric on a model that is bad at high iou

**Expected behavior**
no warnings (looks like an if can fix it)

**Screenshots**
![Screen Shot 2022-04-26 at 18 02 00](https://user-images.githubusercontent.com/26321553/165527288-fc0d372e-d248-48fa-9184-aa1ca9652ec1.png)

**Comment by Nadav-Barak** [comment]
Seems that can be solved with an if
