### ISSUE TITLE
[BUG] dataset files might get out of sync

### ISSUE THREAD

**Issue by matanper** [deepchecks/deepchecks#1358]
We had a bug where we updated the adult dataset model/data but forgot to re-upload it to figshare. This later on cause exception when trying to calculate metrics on the adult dataset & model.

We need a way to test for those changes and ensure the uploaded files are always up to date

**Comment by ItayGabbay** [comment]
I suggest validating the md5 of the model

**Comment by ItayGabbay** [comment]
After discussion - we will cover all datasets and models with unit tests that will try to predict some samples.
