### ISSUE TITLE
[FEAT] support a df of predictions instead of providing a model

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1364]
**Is your feature request related to a problem? Please describe.**
Currently, our checks and suites require a compatible model to work with. The 2 main functions that are used are the `predict` function that returns the predictions, and the inferring of `feature_importance`. It limits the package to work with a limited number of models and frameworks.

**Describe the solution you'd like**
Instead of specifying a model, let the user pass a data frame full of predictions (and probably another parameter that specifies the feature_importances). This way we will be model and framework agnostic.

**Comment by matanper** [comment]
We don't want to pass predictions to the run or something. IMO we need a wrapper that acts like a model, which the user can initialize with a dataframe

**Comment by noamzbr** [comment]
Agree with @matanper, would prefer a "Caching model" (or whatever) that is our object and can store predictions, and if we get it we know not to calculate FI...

**Comment by ItayGabbay** [comment]
After discussion, the following were decided:

## Tabular
we will pass 2 arguments to the run function:
`check.run(train, test, model=None, y_pred_train, y_pred_test, y_proba_train, y_proba_test, feature_importance)`
where the y_pred is iterable of the model decision, and the y_proba is iterable of probabilities 

## Vision
We don't need the y_proba, and the shape will be like our expected shapes for each use case.
`check.run(train, test, mode=None, y_pred_train, y_pred_test)`

We need good documentation for each.

**Comment by nirhutnik** [comment]
Note: We already take the "feature_importance" parameter. 
Also this needs to be well documented.
