### ISSUE TITLE
[FEAT] in object detection scorers, enable modifying the IoU and score thresholds it runs on

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1379]
## Steps
1. Design how that can be done such that it can be controlled from strings, or any other way without using the "make scorer" functionality or defining new callables.
2. Brainstorm and approve
3. Implement

**Comment by TheSolY** [comment]
The detection scorers are currently created by 2 classes:ObjectDetectionTPFpFn and AveragePrecisionRecall.  iou_thr is already a parameter to ObjectDetectionTPFpFn, need to add iou range parameter to AveragePrecisionRecall. 

DoD:
The IoU threshold of the detection scorers is controlled without defining new callables or calling make_scorer. 

Tasks:

- [ ] Implement the IoU range parameter in AveragePrecisionRecall - 0.5 SP
- [ ]  brainstorm or mini arc talk, my suggestion is to parse strings in a specific format in get_scorers_dict. - 0.5 SP
- [ ] Implement the result of the brainstorming - 1SP
- [ ] add tests for different metrics and thresholds - 0.5 SP

**Comment by TheSolY** [comment]
Following issue https://github.com/deepchecks/deepchecks/issues/2095
