### ISSUE TITLE
[BUG] Suite display not rendered correct in IFrame

### ISSUE THREAD

**Issue by matanper** [deepchecks/deepchecks#1392]
**Describe the bug**
When displaying suite result in IFrame (for example in colab) the style is not rendered correctly (very narrow and tables are ugly)

![image](https://user-images.githubusercontent.com/9868530/167290143-af9aa19e-8c2c-4da2-87e0-ddbd1e12497c.png)

**To Reproduce**
Run in colab:
```
from deepchecks.tabular.datasets.classification import iris
from deepchecks.tabular.suites import single_dataset_integrity

train, test = iris.load_data()
single_dataset_integrity().run(train)
```

**Comment by JKL98ISR** [comment]
we need to change the function is_widgets_available - we can use widgets as html even if they are disabled
