### ISSUE TITLE
[FEAT] NLP Module

### ISSUE THREAD

**Issue by matanper** [deepchecks/deepchecks#1393]
In the future, we will want to support NLP models. Using this issue to collect feature requests related to NLP 

https://docs.google.com/spreadsheets/d/1n7DLR0-fDTkOhCZYD2AYgZowO4c8SuuA5-NMr0uOK3U/edit#gid=0

**Comment by SangeethaVDirectLink** [comment]
One Feature that would help! 
1) NLP - Integrity - Data quality - It would be a great feature to have deepchecks perform validation with respect to data integrity - on how well the synthetic data points meets the quality standard of old data points. Customizing the quality standard in general - this is a great feature that has a good understanding of the model.
