### ISSUE TITLE
[FEAT][Tabular][Docs] add more info on the suites

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1397]
**Is your feature request related to a problem? Please describe.**
There is not clear place where we mention which suites are available, which checks they contain, where is the recommended logical step in the DS pipeline to use them and a code snippet how to run them.

**Describe the solution you'd like**
In the check gallery and a sub section on suites where each suite will have its on page similarly to a check.

**Comment by noamzbr** [comment]
Closed, as it's part of #1406
