### ISSUE TITLE
[FEAT] Restructure to focus on the three main deepchecks suites

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1406]
The three suites (integrity, train-test, performance) should appear everywhere - quickstart, deepchecks hierarchy, package structure & check gallery. 
1. Suite names should be reconsidered
2. The checks should be moved to their new place in the hierarchy in the package (and deprecation warnings raised). 
3. We should reconsider which checks goes where. 
4. Full suite will be replaced by the three suites in the quickstart (will be done by @shir22). 
5. Make it clear also in vision (though vision has very few integrity checks)
6. Api reference for the suites should detail what checks appear inside it.

**Comment by nirhutnik** [comment]
### Tasks:
1. Send suggestion of different suites - names and inner-partition of checks. Need comments from everybody and probably a heated discussion with a lot of wasted time. Do this BEFORE you start the assignment. - 1 SP
2. Move everything to where it should be. Update in package, tests, documentation hierarchy. Notice some references in docs try to reference by path. - 1 SP
3. Update Quickstart and other docs where full_suite is used. - 0.5 SP
4. Add "See also" by the logic written henceforth to all suite docstrings, with references to both other checks and other suites. - 0.5 SP

https://numpydoc.readthedocs.io/en/latest/format.html#see-also

**Comment by noamzbr** [comment]
I think part 2 and 3 can take more time than is specified here. Remember - when changing existing Quackster and other docs to use the new suites, must run them and see that the suite results look reasonable as an example.

**Comment by nirhutnik** [comment]
as wondering about that. What do you think? 2 SP and 1 SP?

**Comment by nirhutnik** [comment]
Updated

**Comment by nirhutnik** [comment]
The final suites and checks:
https://docs.google.com/spreadsheets/d/1mwpscVhtQUWzVR-kKi-L9H4x27JBO3xS3HNfMpe8FtY/edit?usp=sharing
