### ISSUE TITLE
[FEAT] Reconsider special character treatment when column is all special characters

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1453]
**Describe the bug**
Makes other checks (except Special Characters) fail, example:
"+" and "-" strings are considered as nulls - both in MixedNulls Check and in StringMismatch Check

**To Reproduce**
Run:
```
import pandas as pd
from deepchecks.tabular import Dataset
from deepchecks.tabular.suites import single_dataset_integrity

col_names = ["A" + str(i) for i in range(1,17)]
cat_features = ['A1', 'A4', 'A5', 'A6', 'A7', 'A9', 'A10', 'A12', 'A13', 'A16']
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data', sep=",", names=col_names) 
ds = Dataset(df, cat_features=cat_features)
si.run(ds)
```

Will result in:
Conditions Summary table:
![image](https://user-images.githubusercontent.com/33841818/168740389-1836f3e2-10a9-4586-b602-badb9a7814de.png)

Check Outputs:
![image](https://user-images.githubusercontent.com/33841818/168740474-8e1ad9dc-0f21-4f8a-811b-40f2ee2fa425.png)
![image](https://user-images.githubusercontent.com/33841818/168740492-d229efc8-3c4b-4d81-9e31-6b1bf082f1c8.png)

**Comment by matanper** [comment]
If you also suggested a solution here I missed it. Both checks use the `string_baseform` function, which transforms '+' and '-' into an empty string. We can change the checks/the function to leave the string as-is in case the transform results in empty string
