### ISSUE TITLE
[FEAT] MixedDataTypes to display a few examples of each type

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1454]
Current display:
![image](https://user-images.githubusercontent.com/33841818/168741336-7c6bdb6c-cb67-4970-a39b-7fcc80dead12.png)

Desired - to see a few unique examples from each type. currently have to inspect column in order to do it, e.g.:
![image](https://user-images.githubusercontent.com/33841818/168741428-87dbe8fb-296f-43a7-b6b1-891d95222049.png)
would want the check to display it by itself

**Comment by nirhutnik** [comment]
### Description:
Add another 2 rows to the additional outputs table, one for numeric examples and the other for string examples.
Put up to 3 unique examples.

### Inputs:
No new inputs. the "3 unique examples" thing is a display preference that is really not that interesting to the user and shouldn't be added as a parameter.

### Logic:
Add the needed rows to the _check_mixed_percentage function and it will update the dataframe by itself.

### Tasks:
* Add the needed fields to _check_mixed_percentage - 0.5
* Add test to make sure this works and is covered - 0.5

### Comments:
* Make sure samples are beautified - floats should not have more than 2 decimal points (use format_number) and strings should be cut with "..." if too long (maybe add function to strings.py that does that)
