### ISSUE TITLE
[BUG] Observing the results is missing from the Quickstart in 5 minutes

### ISSUE THREAD

**Issue by TheSolY** [deepchecks/deepchecks#1461]
https://docs.deepchecks.com/en/stable/user-guide/tabular/auto_tutorials/plot_quickstart_in_5_minutes.html#sphx-glr-user-guide-tabular-auto-tutorials-plot-quickstart-in-5-minutes-py
Need to add this section (save to html) in the end for non-notebook users.
example for a doc where this section exists https://docs.deepchecks.com/en/stable/user-guide/vision/auto_tutorials/plot_simple_classification_tutorial.html#sphx-glr-user-guide-vision-auto-tutorials-plot-simple-classification-tutorial-py

**Comment by shir22** [comment]
This will be closed by (and thus somewhat duplicate of) #1687 (that will be implemented after the new save and view user guides)
