### ISSUE TITLE
[BUG] Mixed Nulls check taking too long

### ISSUE THREAD

**Issue by galsr** [deepchecks/deepchecks#1472]
**Describe the bug**
When running Mixed Nulls check on azure databricks, with a dataset 242,335 rows long and 3 cols with only floats (and nans). It took the check 1.47 hours to finish.

**Expected behavior**
Suppose to take few seconds. 

**Screenshots**
![Screenshot 2022-05-18 124324](https://user-images.githubusercontent.com/95021845/169010677-c5b9309a-66d3-4f30-8d1e-d62086073eec.png)

**Environment (please complete the following information):**
Azure Databricks
 - Python Version: 3.8.10
 - Deepchecks Version: 0.6.4

**Additional context**
Also, as can be seen in the screenshot attached, in the results, same kind of Nans in the same col, are not grouped together, but instead every Nan is presented as an individual.

**Comment by matanper** [comment]
Thanks for reaching out to us! 
The NaN not grouped together will be fixed in an upcoming PR.

About the timing problem, I couldn't reproduce it. I tried to run on 3 columns on 2M rows and it was still pretty fast. Can you help us by providing the data, or a reproducible code?

**Comment by DL1992** [comment]
I can say this also happen to me - a data frame of 1M rows on 33 columns
after an hour and a half, I just killed the process

**Comment by noamzbr** [comment]
Hi @DL1992, thanks for reporting! Is there any chance you can upload a data sample on which this bug can be reproduced? On what platform were you running your code? I turns out that in the case of the initial report (by @galsr) the issue happens only on Databricks.

In the meanwhile, to further debug this issue, we should try to reproduce the bug on Databricks.

**Comment by DL1992** [comment]
Hi, Sadly I can't share the data since it's confidential. I'm not working on any platform. opening a notebook on a remote Linux server.
resources are not an issue (the remote server is very very large)

**Comment by matanper** [comment]
@DL1992 If possible please share with us the following:
1. sample your dataset to a size that takes only a few minutes to run. use `Dataset.sample` method
2. use this [gist](https://gist.github.com/matanper/e2802864fe408e634ae02971028b458b) and where it says "### Code to profile here" put the check run `MixedNulls().run(dataset)`
3. A list of the used methods with their timing will be printed. post for us the top 5 rows

**Comment by galsr** [comment]
Fixed with version 0.7.0
