### ISSUE TITLE
[BUG] SingleDatasetScalarPerformance skipping reduce operation warning ignores tensors size 1 

### ISSUE THREAD

**Issue by TheSolY** [deepchecks/deepchecks#1475]
In SingleDatasetScalarPerformance:
This warning only catches single number- should also catch arrays and tensors with size 1, and possibly other data structures with size 1 that we'll encounter later.
           
 if isinstance(metric_result, numbers.Real):
                warnings.warn(SyntaxWarning('Metric result is already scalar, skipping reduce operation.'
                                            'Pass reduce=None to prevent this'))

**Comment by noamzbr** [comment]
Outdated by https://github.com/deepchecks/deepchecks/issues/1637
