### ISSUE TITLE
[FEAT]Global default single-value metrics for monitoring

### ISSUE THREAD

**Issue by TheSolY** [deepchecks/deepchecks#1480]
In the same way that there are default scorers in the metrics module that return a list (value per class) for each task type, add defaults that return a scalar for monitoring.

**Comment by TheSolY** [comment]
Tasks:
- [ ] Decide Which metric will be the default for each task type
- [ ] Implement a function get_default_single_scorer similar to get_default_scorers in utils.metrics
- [ ] Replace default scorer with a call to the function in single_dataset_scalar_performance
- [ ] List the other functions that we want to replace the default in the future and open an issue

**Comment by noamzbr** [comment]
+ Also use these metrics in the new check of single_dataset_scalar_performance for tabular data

**Comment by TheSolY** [comment]
Not relevant after https://github.com/deepchecks/deepchecks/issues/1637
