### ISSUE TITLE
[CV][CHAR] Working with embeddings 

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1510]
## Goal
There is a lot of value to be gained in the CV package from using embeddings. Embeddings can be produced by a "benchmark" model or by the the user's model. The task is to try and characterize a relatively simple way to use these embeddings and get them from the user when needed.

## To consider
**For the "built in model":**
- What model suites this role?
- How would we make the user understand what embeddings are being used and how he can replace them with his own.

**For the user integration:**
- Should there be a new function in the VisionData object and what it should do?  
- Is there some way to get embeddings from most models without writing an integration (e.g., taking the output of the next to last layer?). Would it work on popular models?

**Comment by TheSolY** [comment]
I think that the user should be able to pass the embedding function as a parameter to the relevant checks with default embedding TBD.
The embedding function format should be:
* callable
* input: a batch of images 
* output:a batch of vectors representing the images in the latent space.

**Comment by TheSolY** [comment]
# Description:
Create a short list of relevant embedding methods- common models and other methods such as hashing and properties that we currently use. Decide how to integrate and communicate to the user.

# Tasks:
1. Research for commonly used methods - 2SP
2. Map which methods can be used off the shelf (in terms of availability and license), which should be adjusted, and which should be implemented from scratch - 1SP
3. List the checks that should use embedding - 1SP
4. Plan the refractor for the checks to accept embedding function as parameter - 1SP
5. Write a summary for a future embedding guide , what should it contain? for example, instructions for our API - 1SP

**Comment by TheSolY** [comment]
The characterization document: https://docs.google.com/document/d/1oPHJxAFxlHBiQWrekPbz1rLVBtwamFT_c00ytX6xmu0/edit?usp=sharing
