### ISSUE TITLE
[FEAT][Tabular][Checks] Allow access to all checks data not only top showing

### ISSUE THREAD

**Issue by DL1992** [deepchecks/deepchecks#1514]
**Is your feature request related to a problem? Please describe.**
I was running the Conflicting Labels Check on my dataset. which worked great and showed me that there were 476 records with conflicting labels, but it only showed me the 5 of them (which is what I would expect since that's the default)
Then I wanted to fix the issue by observing the record and removing them, But there wasn't any way to access all of them.
the only way I figured out how to do it is by running the test again with n_to_show=(the number the message showed me)

**Describe the solution you'd like**
I would like the test to return all relevant data to get to the problem faster.  it may show me only n_to_show, but when ill access the test object I should get all indexes of conflicting Labels.

**Describe alternatives you've considered**

I did notice I'm able to access the data the test returns, but it only returns the n_to_show. so just return everything and only **show** the relevant rows per the argument
**Additional context**

**Comment by noamzbr** [comment]
Great suggestion! Thanks @DL1992. 
It indeed makes more sense to return also the indexes of the conflicting labels.

**Comment by JKL98ISR** [comment]
@noamzbr we should maybe open a general issue to make sure n_show_top only affects the display as it should

**Comment by Nadav-Barak** [comment]
Following JKL suggestion - will solve this as part of the more general issue.
