### ISSUE TITLE
[FEAT] no auto-complete for context init arguments in the check.run function

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1527]
**Is your feature request related to a problem? Please describe.**
Context has many init args that we pass from the check.run but you have no indication of them.

**Describe the solution you'd like**
add the args to each check so it will auto-complete

**Comment by ItayGabbay** [comment]
See #1614

**Comment by matanper** [comment]
possible solution
https://softwareengineering.stackexchange.com/questions/386755/sharing-docstrings-between-similar-functions

**Comment by yromanyshyn** [comment]
pandas uses cool [Substitution](https://github.com/pandas-dev/pandas/blob/89578fe93d25299ac853d856332bec11e1d268fc/pandas/util/_decorators.py#L415) class for the documentation purpose, we might borrow it

example from documentation

```python
    sub_author_name = Substitution(author='Jason')

    @sub_author_name
    def some_function(x):
        "%(author)s wrote this function"

```
