### ISSUE TITLE
MixedNulls: Empty string is shown as empty string

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#1539]
When MixedNulls shows the different null types, if it found an empty string it just leaves the dataframe cell empty, which is very confusing. Should write '' or "empty string" or something. Check for all None types we look for.

**Comment by Nadav-Barak** [comment]
Test the display of this check for all null types we detect and see that they make sense, if not change the display output (as Nir suggested).

Specifically run this check with a DS with no nulls and each time add a different null type somewhere and see the visual display. Also view how in looks in StringMismatch output.
