### ISSUE TITLE
Drift checks (and maybe others) can't handle Int8 type

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#1540]
Both EMD and Domain Classifier can't handle Int8 type (new pandas type - int that can handle Nones). Most sklearn functionalities can't handle it as well.
Possible solution is just casting to float - more wasteful in terms of memory, but works for all functions.
Make sure to add relevant tests after solving.

Consider casting in the Dataset itself.

**Comment by noamzbr** [comment]
closed, moved content to #1538
