### ISSUE TITLE
Progress bar times are unclear

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#1545]
Progress bar timings sometimes exceed the expected time. Also, expected time changes dramatically between different updates. Also also, it should show how much it took so far in realtime (update every second)
<img width="480" alt="image" src="https://user-images.githubusercontent.com/92314933/170997877-8c4a2e84-1b40-4872-b4c1-dbb1f311bea3.png">

**Comment by noamzbr** [comment]
I agree - the expected behavior should be to show "# run checks / # total checks to run", and the amount of time spent so far. No more (we can't really estimate the remaining time)

**Comment by noamzbr** [comment]
Clarification - vision should be batch + time (which is the current state)
In tabular no time and n_checks out of total_checks

**Comment by yromanyshyn** [comment]
>  it should show how much it took so far in realtime (updated every second)

it will not be hard to change the text, 
but I do not see any way to achieve real-time update 
with `tqdm` library (which we currently use to create progress bars)

also, the difficulty of implementing real-time updates depends on what you 
mean under real-time update (what should it include). In some cases it becomes 
technically an extremely hard task/

if you want the "total time spent" to be updated in real-time then I think it could 
be achieved with help of simple js code) but if you want to update the entire 
progress bar (all other info) then it becomes a hard technical task/ 

In the second case IMO you will need a separate thread that will communicate 
with the checks processing loop and which will be sending updates to the client 
(jupyter UI) every second (this is very generally saying)
