### ISSUE TITLE
[BUG] some checks change the value according to n_show_top instead of only the display

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1560]
**Describe the bug**
some checks change the value according to n_show_top instead of only the display 

**To Reproduce**
for now we know it happens in the Conflicting Labels Check  but it may be in other checks too

**Expected behavior**
it should affect only the display

**Additional context**
We need to check all checks that are using this param and make sure n_show_top works as intended and fix otherwise.
related to #1514

**Comment by Nadav-Barak** [comment]
Step 1: review the for all checks whether they use n_show_top in any calculation that affect the CheckResult
Step 2: for checks that do use it (such as Conflicting Labels) fix it so that the resulting output would return the full information.

**Comment by Nadav-Barak** [comment]
Raise a flag if we find that it increase/ requires additional computations

**Comment by yromanyshyn** [comment]
just a note:

> for now we know it happens in the Conflicting Labels Check but it may be in other checks too

it does not happen with `Conflicting Labels` check
`Conflicting Labels` check returns the percent of ambiguous labels, 
`n_to_show` does not have an effect on it

but, yeap, other checks should be verified
