### ISSUE TITLE
[BUG] sometimes we refer to feature_importance as features_importance

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1561]
**Describe the bug**
sometimes we refer to feature_importance as features_importance.
it is in the context/suite/check params but should be feature_importance instead. (maybe also in other places).

we need to rename it and add deprecation warnings for features_importance

**Comment by nirhutnik** [comment]
### Tasks:
* Search for all occurences of features_importance and refactor
* Add deprecation warnings when needed + still accept the older name
