### ISSUE TITLE
[FEAT][Display] add possibility for tabs in check output

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1574]
Create a class that enables interactive (clickable) tabs in output such that when clicking on a tab the output changes.
All plots in all tabs are pre-calculated and divided based on parent tab. 
Should be able to get as input a dictionary of {"tab_name": string, "images" : list} and output something like this:

![Screen Shot 2022-06-02 at 15 10 14](https://user-images.githubusercontent.com/67195469/171645567-0359c365-b9de-4c83-a7ed-6121e2110ef4.png)

**Comment by matanper** [comment]
Clarification: The tabs should support other displays we support, not specifically images. So we should create a TabsDisplay class with serializers. the input for the class should be something like `TabsDisplay(names=['a', 'b'], displays=[x, y])` where the x, y are supported display items like plotly figure, HTML, etc
