### ISSUE TITLE
[FEAT][Vision] Better explanations in doc regarding how to use package in IDE

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1577]
**Is your feature request related to a problem? Please describe.**
Docs are based around the idea that users use the package in notebooks, we should update checks (especially in vision) to be more straight forward for IDE users.
This issue is only regrading changes in DOCS

**Describe the solution you'd like**
Some suggestions:
1. (received from community) add the commend "result.save_as_html" at the end of checks code snippets instead/ in addition to the regular "result" which only make sense in notebook.
2.

**Comment by TheSolY** [comment]
related issue: https://github.com/deepchecks/deepchecks/issues/1461

**Comment by TheSolY** [comment]
Since the new display, we should use .show instead of .save_to_html. 
I added the following text as comment to the feature-feature correlation tutorial and I think we should just add it to the rest of the check tutorials as well:
# To display the results in an IDE like PyCharm, you can use the following code:
# check.run(ds).show()
# The result will be displayed in a new window.

**Comment by shir22** [comment]
Late bloomer - can we piggy-back on this small docs-improvement-for vision issue and add in its scope also adding **a note about GPU support** in the relevant places? (as previously suggested by @TheSolY. If the issue was already opened please add a link)

**Comment by TheSolY** [comment]
@shir22 no issue for this, good idea to fix both at the same time, let's decide what the phrase should be

**Comment by TheSolY** [comment]
@shir22 I like this comment:
`# If you can, run this example on a GPU, it will be a lot faster.`
From PyTorch documentation https://pytorch.org/vision/stable/auto_examples/plot_optical_flow.html?highlight=gpu
![image](https://user-images.githubusercontent.com/99395146/174487162-7a00e7b5-76a5-49e0-b361-bb44435a115a.png)
