### ISSUE TITLE
[BUG] Data Integrity Suite is not detecting DataDuplicates, MixedDataTypes, ConflictingLabels or StringMismatch

### ISSUE THREAD

**Issue by nf78** [deepchecks/deepchecks#1587]
**Describe the bug**
 Data Integrity Suite is not detecting DataDuplicates, MixedDataTypes, ConflictingLabels or StringMismatch.

**To Reproduce**
After following the [Data Integrity Suite](https://docs.deepchecks.com/en/stable/user-guide/tabular/auto_tutorials/plot_quickstart_in_5_minutes.html#run-the-integrity-suite), very soon I realised that method `single_dataset_integrity(**kwargs)` is deprecated (documentation needs updating too), and followed recommendations shown in error messages to achieve this code using `data_integrity(**kwargs)` instead:

`from deepchecks.tabular.suites import data_integrity
from deepchecks.tabular import Dataset`

then:

     data_new = Dataset(data, cat_features=list_of_categorical)

     integ_suite_new = data_integrity()
     integ_suite_new.run(data_new)

where `data` is a `pandas.DataFrame`, with a mix of types like categorical, text and numerical data, loads of duplicates and conflicting labels and string mismatches.

this will return:
`

      Data Integrity Suite: [
	0: IsSingleValue
		Conditions:
			0: Does not contain only a single value
	1: SpecialCharacters
		Conditions:
			0: Ratio of entirely special character samples not greater than 0.1%
	2: MixedNulls
		Conditions:
			0: Not more than 1 different null types
	3: MixedDataTypes
		Conditions:
			0: Rare data types in column are either more than 10% or less than 1% of the data
	4: StringMismatch
		Conditions:
			0: No string variants
	5: DataDuplicates
		Conditions:
			0: Duplicate data ratio is not greater than 0%
	6: StringLengthOutOfBounds
		Conditions:
			0: Ratio of outliers not greater than 0% string length outliers
	7: ConflictingLabels
		Conditions:
			0: Ambiguous sample ratio is not greater than 0%
	8: OutlierSampleDetection
	9: FeatureLabelCorrelation(ppscore_params={})
		Conditions:
			0: Features' Predictive Power Score is not greater than 0.8
     ]
`

**Expected behavior**
I was expecting DeepChecks to detect those data integrity issues mentioned above.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Python Version: 3.8.12
 - Deepchecks Version: 0.7.1

**Comment by matanper** [comment]
Hey @nf78, the output you added is the print of the suite, not it result. Please try to do
```
result = integ_suite_new.run(data_new)
result.show()
```

**Comment by matanper** [comment]
You should have a look at the docs of [Data Duplicates](https://docs.deepchecks.com/en/stable/checks_gallery/tabular/data_integrity/plot_data_duplicates.html) and [String Mismatch](https://docs.deepchecks.com/en/stable/checks_gallery/tabular/data_integrity/plot_string_mismatch.html), which explains better each check.

About Data Duplicates, it works on rows and not on individual columns.

And about String Mismatch, I'm not sure what you refer to by weird values, basically it finds mismatches by transforming all the values to "base form" which means removing all special characters and whitespace, and lowering the caps. Then it shows all the values in the data which transformations resulted in the same base from.

**Comment by matanper** [comment]
Hey, @nf78 
You haven't replied for a few days I hope all of your issues were resolved. If there won't be a comment in the next few days, we will close this issue. Feel free to add a comment or open a new issue if needed 😃

**Comment by nf78** [comment]
Hi @matanper sorry been too busy lately, and thanks for your explanation. I guess it would be nice to have a column based duplicate search option, and will be happy to raise that as a feature request, if you think its worth it in terms of near future road map.

About the String Mismatch that's more clear now, thanks.

The Getting Started guide shoukd also be updated with the latest code to reduce initial time to experiment the tool. Perhaps another issue to be raised?

**Comment by ItayGabbay** [comment]
@nf78 we'll be glad if you can raise a detailed feature request regarding the column-based data duplicates, so we can push it into the roadmap.

About the getting started issue - It is going to be fixed in the next release :)

**Comment by nf78** [comment]
@ItayGabbay thanks and done!
