### ISSUE TITLE
[BUG] Missing pytest function from doc

### ISSUE THREAD

**Issue by DL1992** [deepchecks/deepchecks#1591]
**Describe the bug**
In the docs there is a section about "integration" with pytest. a SuiteResult should have " passed_conditions()" function to assert on. but none exist. Also, there is no clear way to find out in script (instead of a notebook) which tests  pass/fail/warn. and it feels like there should be.
best thing I manged to do was iterate over test_result.results ->[idx of test] -> category -> value
**To Reproduce**
Try to run a suite and then assert on the function from the docs

**Expected behavior**
The function that is mention in the docs should be real/ removed from the docs until such a time when it is ready

**Environment (please complete the following information):**
 - OS: linux
 - Python Version:3.7.1
 - Deepchecks Version:0.7.2

**Additional context**

**Comment by matanper** [comment]
Hey, the function in the docs is shown on `CheckResult`, and not `SuiteResult`, and it indeed exists. Regarding the suite:

1. We will add `passed()` function to make it easier to use also there 😃 
2."there is no clear way to find out in script which tests pass/fail/warn" - Can you clarify what you expect? you want to get all the results that have failed or just an aggregated boolean whether there are failures?

**Comment by DL1992** [comment]
you're right, my bad.
2. I would think both. first, a function that lets me do "assert suite.passed()" to see if all tests passed in pytest/scripts for validation
But if not - I do want to be able to see which test didn't.
