### ISSUE TITLE
[BUG] Weird behavior with "to_wandb" and confusion matrix

### ISSUE THREAD

**Issue by DL1992** [deepchecks/deepchecks#1592]
**Describe the bug**
After running a model evaluation suite and exprorint to wandb using "to_wandb" function, the confusion matrix appears in the w&b page without the values
**To Reproduce**

**Expected behavior**
The confusion matrix in w&b should appear like the confusion matrix in the notebook which has it values shown
![1654716717893](https://user-images.githubusercontent.com/21197955/172704682-e1097eaa-5371-48b6-96d7-f0df1006c043.jpeg)

**Environment (please complete the following information):**
 - OS: linux
 - Python Version:3.7.1
 - Deepchecks Version:0.7.2

**Comment by DL1992** [comment]
hmmm, literally just result = suite.run follow by result.to_wandb.
my wandb version is 0.12.9

**Comment by JKL98ISR** [comment]
what is the wandb and plotly version on the wandb server?

**Comment by matanper** [comment]
This issue is stale and we couldn't reproduce it.
@DL1992 feel free to reach out to us if this problem persists and we will try to help personally. Closing for now
