### ISSUE TITLE
[DOC] Dataset docstrings - move from load_data fuction to the dataset sub-module

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1596]
The description of the tabular datasets should be in the dataset submodule and not under the `load_data` function, for all datasets in classification and regression.

Screenshot for example:
The long description should be here:
![Image](https://user-images.githubusercontent.com/33841818/172895863-22d5822a-8eca-4290-8f74-65ff727fe8a3.png)

instead of here:
![Image](https://user-images.githubusercontent.com/33841818/172896044-78508c6d-89a3-4b18-bed1-156335885788.png)

**Comment by noamzbr** [comment]
## DoD
Just move this docstring a couple of rows up for each of the datasets. 
In the load data module just document the parameters and returns
