### ISSUE TITLE
[FEAT][Tabular] performance report -> Class Performance?

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1602]
Several changes are required:
1. Make clear how to supply alternative metrics to report 
- If alternative metrics are supplied only present them
- Only metrics for binary classification are accepted ( no "f1_micro")
- Metric should be applied to each class separately (as is now for defaults)
2. Change name to "Class performance"
3. plot file example should be on multi label classification + refactored + link to metric guide

**Comment by noamzbr** [comment]
NOTE: Degradation warning for existing class name
