### ISSUE TITLE
[FEAT] feature flag do not run display calculations

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1605]
If suite/ check is run via an automatic testing mechanism or if only the result value is of interest then we should allow an option to not run the display calculations. This is also the case for the as_scalar function.

As default we should calculate the display and add a feature flag do not calculate display. 
Should implement in a generic way so it is easily embedded in **all checks**.

**Comment by JKL98ISR** [comment]
this is nearly a package wide refactor
