### ISSUE TITLE
[FEAT][CV]property-label correlation check

### ISSUE THREAD

**Issue by TheSolY** [deepchecks/deepchecks#1608]
Data integrity check
Similar to the tabular feature-label correlation check but with the image properties as features. 
Useful for preventing shortcut learning.

**Comment by Nadav-Barak** [comment]
Use a similar mechanism as in the tabular FeatureLabelCorrelation.
Discuss how properties are provided + explain in example docs

**Comment by noamzbr** [comment]
Use a OK licensed version of the wolf vs husky dataset to showcase this check
https://www.kaggle.com/code/a45632/fastai-example-wolf-vs-husky/data
