### ISSUE TITLE
[BUG] Running Image Property Outliers Guide results in an error when importing modules

### ISSUE THREAD

**Issue by PJEstrada** [deepchecks/deepchecks#1613]
**Describe the bug**
When trying to run the Image Property Outliers Guide here: https://docs.deepchecks.com/en/stable/checks_gallery/vision/data_integrity/plot_image_property_outliers.html#sphx-glr-download-checks-gallery-vision-data-integrity-plot-image-property-outliers-py

I get the following error after importing deep checks 
```
[/usr/local/lib/python3.7/dist-packages/deepchecks/vision/datasets/detection/coco.py](https://localhost:8080/#) in <module>()
     21 import numpy as np
     22 import torch
---> 23 from cv2 import cv2
     24 from PIL import Image
     25 from torch import nn

ImportError: Bindings generation error. Submodule name should always start with a parent module name. Parent name: cv2.cv2. Submodule name: cv2
```

**To Reproduce**
Run pynb here: https://colab.research.google.com/drive/1BJRhObm6djvdgN2jCaDQOvAR8w567v7Z#scrollTo=0PkEfdqrG2bx

**Expected behavior**
Expect to see the check results and not import error.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Google Collab
 - Python Version: Python 3.7.13
 - Deepchecks Version: latest

**Additional context**

**Comment by ItayGabbay** [comment]
@PJEstrada Thanks!

The quick fix would be to limit opencv-python<4.6.0 in the vision-requirements.txt

Although I think we should fix it in another way...
