### ISSUE TITLE
[BUG] No examples in documentation in suites

### ISSUE THREAD

**Issue by aishgrt** [deepchecks/deepchecks#1614]
There is no example and parameter set of the suites:
https://docs.deepchecks.com/en/stable/api/generated/deepchecks.tabular.suites.single_dataset_integrity.html

Would be helpful to have something like this:https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

**Comment by aishgrt** [comment]
@shir22 @ptannor @matanper

**Comment by ItayGabbay** [comment]
Hmm, I think it makes sense to have them. However, it will require us to manually maintain this list of parameters..

**Comment by ItayGabbay** [comment]
## DoD
Have documentation of available parameters in suites and checks (related to #1527)

2 options available:
1. duplicating only the docstrings to contain the available parameters (this will cause the the functions and docs will have them, but autocomplete won't)
2. Duplicating both the docstrings and the arguments themselves. This will enable autocomplete but also really hard to maintain.

**Comment by ItayGabbay** [comment]
See #1565
