### ISSUE TITLE
[FEAT] Column-based Data Duplicates

### ISSUE THREAD

**Issue by nf78** [deepchecks/deepchecks#1622]
**Is your feature request related to a problem? Please describe.**
Very often, different rows may have duplicates in one field (that we care about) but not in other fields (we care less). A row-based duplicate detection, won't work in this case.

**Describe the solution you'd like**
It would be very useful if we could run column-based duplicates. Per example, we could pass as argument `columns=`, a list of columns or just a single column-name.

**Describe alternatives you've considered**
I could create several subsets of the same DataFrame with the selected columns, but that could lead to other inconsistencies.

**Additional context**
Also, I was expecting this to be considered as part of the report. Colum by Colum duplicates.

**Comment by nf78** [comment]
Hi @nirhutnik , Thanks for your feedback.

That's actually what I was looking for, but I normally use the `data_integrity` suit of tests instead of the `DataDuplicates` class.
```
mydata = Dataset(data)

integ_suite_new = data_integrity()
result = integ_suite_new.run(mydata )
```
So, can I pass the same argument to the `data_integrity` class? I've read about custom suites, but not sure how it's done.

**Comment by nirhutnik** [comment]
Hi @nf78 :) 
the data_integrity suite include the DataDuplicates check. For example, you can see in the user guide https://docs.deepchecks.com/stable/user-guide/tabular/auto_tutorials/plot_quick_data_integrity.html#run-the-deepchecks-suite that it "doesn't pass" on the specific given example.

But in general, yes. The same inputs that you put into a suite can be given to a check:

```
from deepchecks.tabular.checks import DataDuplicates
mydata = Dataset(data)

my_check = DataDuplicates()
result = my_check.run(mydata)
```

**Comment by matanper** [comment]
@nf78 To clarify, you can pass this option to the suite, but then it will apply this filtering on **all** the checks in the suite:

```
mydata = Dataset(data)

integ_suite_new = data_integrity(columns=['a','b','c'])
result = integ_suite_new.run(mydata )
```

If you want to apply this only for data duplicate I suggest you copy the data_integrity code, and add the parameter only to data_duplicates:
```
def my_data_integrity(**kwargs) -> Suite:
    """Create a suite that is meant to detect integrity issues within a single dataset."""
    return Suite(
        'Data Integrity Suite',
        IsSingleValue(**kwargs).add_condition_not_single_value(),
        SpecialCharacters(**kwargs).add_condition_ratio_of_special_characters_less_or_equal(),
        MixedNulls(**kwargs).add_condition_different_nulls_less_equal_to(),
        MixedDataTypes(**kwargs).add_condition_rare_type_ratio_not_in_range(),
        StringMismatch(**kwargs).add_condition_no_variants(),
        DataDuplicates(columns=['a','b','c'], **kwargs).add_condition_ratio_less_or_equal(),
        StringLengthOutOfBounds(**kwargs).add_condition_ratio_of_outliers_less_or_equal(),
        ConflictingLabels(**kwargs).add_condition_ratio_of_conflicting_labels_less_or_equal(),
        OutlierSampleDetection(**kwargs),
        FeatureLabelCorrelation(**kwargs).add_condition_feature_pps_less_than()
    )

integ_suite_new = my_data_integrity()
result = integ_suite_new.run(mydata )
```
