### ISSUE TITLE
[FEAT] Profiling the vision package

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1626]
**Is your feature request related to a problem? Please describe.**
Following #1566 (which is profiling the tabular package), we should know what is taking the most time & memory in the vision package, and how we can improve that

**Describe the solution you'd like**
1. See if the profiling used in #1566 fits also the vision.
2. Summarize profiling of all vision checks in presentable forms
3. For checks which are slow/heavy try to find the cause

**Comment by ItayGabbay** [comment]
This issue shouldn't include the integration to the CI. for this one, see #1629

**Comment by ItayGabbay** [comment]
Use it with static predictions
