### ISSUE TITLE
[FEAT] Create Quickstart for Model Evaluation

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1628]
**Describe the solution you'd like**
Style and structure similar to data integrity and train test validation quickstarts (in tabular user guides).
Includes: choosing a dataset, and demonstrating the model evaluation suite. (consider - using iris, from current "quickstart" that will be removed, or using a more compelling dataset and model, possible with a different scenario e.g. imbalanced data)

Tutorial should be focused towards a new user, meeting the package for the first time (should be short and simple while also demonstrating core abilities for using deepchecks, and links for further reading and customizations)

**Comment by ItayGabbay** [comment]
We should build it on the lending club dataset since it's more interesting in my opinion.

**Comment by shir22** [comment]
lending club dataset is used in lending club dataset, so that's a disadvantage...
(also @noamzbr says it's not straightforward to build a good model on it)
This task will likely include adding also a dataset (to be considered in story points)

additional suggestion for dataset - titanic

**Comment by ItayGabbay** [comment]
Steps:
- Choose/experiment with a good dataset (must contain cat and num features for beautiful output) (2 sp)
- Write the quickstart & upload the dataset and model and document it in the package (3 sp)
