### ISSUE TITLE
Refactor alternative metric mechanism to support new metrics and string metrics in vision

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1630]
**Is your feature request related to a problem? Please describe.**
There are several basic metrics that are currently not supported and we should implement, those include:
Classification: Sensitivity (recall), [specificity](https://www.jigsawacademy.com/sensitivity-vs-specificity-in-logistic-regression/), FPR, FNR, Precision-recall AUC
Object detection: in other issue - https://github.com/deepchecks/deepchecks/issues/1634

**Describe the solution you'd like**
Implement the metrics internally, make sure those metrics are implemented support the DeepcheckScorer class api. In addition keep in mind those metrics should also be applicable to vision classification tasks.
Add unit tests to make sure those metrics return the correct value + work properly with the DeepcheckScorer API

**Comment by noamzbr** [comment]
Additionally - need to add option (string representation, like scorer api) for per-class metrics. Currently a scorer function must be passed to use per-class metrics.

**Comment by nirhutnik** [comment]
### DoD:
Add these default scorers - Sensitivity (recall), [specificity](https://www.jigsawacademy.com/sensitivity-vs-specificity-in-logistic-regression/), FPR, FNR, Precision-recall AUC, as both strings and functions, both to vision and tabular.


### Tasks:
* Add metrics to both packages and see that they work + tests - 4 SPs
* Make sure we accept them as strings as well - 1 SP
