### ISSUE TITLE
[FEAT] SingleDatasetScalarPerformance update to support multiple scorers

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1637]
**Is your feature request related to a problem? Please describe.**
Update this check to accept a list of scorers (as scorer object or as a list of strings) and return a dictionary. Should create a common api to this and to https://github.com/deepchecks/private-issues/issues/44.

**Comment by noamzbr** [comment]
Not sure a common api is possible, considering that vision would use ignite metrics

**Comment by Nadav-Barak** [comment]
After finalizing our decision regarding how scorers are passed to model eval checks, implement it here

**Comment by JKL98ISR** [comment]
SingleDatasetScalarPerformance --> SingleDatasetPerformance that implements ReduceMixin

**Comment by TheSolY** [comment]
Also rename SingleDatasetPerformance

**Comment by TheSolY** [comment]
@JKL98ISR @Nadav-Barak @noamzbr In what case do we need the reduce if we want the result per class? When is a metric result not reduced over the sample axis?
