### ISSUE TITLE
[BUG] bug in the vision checks page, shows links that aren't supposed to show

### ISSUE THREAD

**Issue by TheSolY** [deepchecks/deepchecks#1647]
bug in the vision checks page, shows links that aren't supposed to show
https://docs.deepchecks.com/stable/checks_gallery/vision.html
![image](https://user-images.githubusercontent.com/99395146/174067517-b8f8dccd-608d-4f5a-9a5a-b318a54c002a.png)

**Comment by ItayGabbay** [comment]
Closed by #1648
