### ISSUE TITLE
[BUG][CV] Image property outliers display output when it doesn't run

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1656]
See following image, result of suite output when running on dataset with only 2 images.
![image](https://user-images.githubusercontent.com/33841818/174195713-e729dbba-de4e-4696-9edf-5cb7f935f8c7.png)

prntscrn from community user ([from the following thread in slack](https://deepcheckscommunity.slack.com/archives/C02UELDTZHD/p1655418009785889?thread_ts=1655410799.938469&cid=C02UELDTZHD))

ImagePropertyOutliers shows blank output which isn't not clear.

**Desired State**
If no output, state explicitly why, in the agreed format.
In general - if no outliers found for whichever reason (even if for other reasons such as no outliers found), the display shouldn't be like that as it seems buggy, verify that that is the case.

**Comment by TheSolY** [comment]
DoD:
The test has a nice display when there's no output

- [ ] Decide what the display should look like
- [ ] Implement the display and add an "if" to the check's display
- [ ] Add a unittest for this case
