### ISSUE TITLE
QST: data_integrity suite detect features which is in dataframe but not in feature list

### ISSUE THREAD

**Issue by chendingyan** [deepchecks/deepchecks#1666]
### Research

- [X] I have searched the [[deepchecks] tag](https://stackoverflow.com/questions/tagged/deepchecks) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

None

### Question about deepchecks

```
ds_whole = Dataset(feat_df, label=target_col, features=features, cat_features=cate_features, datetime_name=date_col)
integ_suite = data_integrity()
integ_result = integ_suite.run(ds_whole)
```
There are features(festival_name) in feat_df, but not in features, and Mixed Nulls still detect it as a feature
<img width="955" alt="image" src="https://user-images.githubusercontent.com/16874978/174551796-79ca6b6d-dd81-45a9-b114-385d2c050a0e.png">
<img width="334" alt="image" src="https://user-images.githubusercontent.com/16874978/174551883-21886d79-f178-4ae7-ac25-8ea8d90c0649.png">

**Comment by matanper** [comment]
Hey, thanks for the report 😃 

You are right about the behavior, the check goes over all columns disregarding their type. In some cases, it is interesting to check non-feature columns, but I agree it shouldn't be the default. 

We will add a new flag for integrity checks which controls if non-features columns are also checked

**Comment by nirhutnik** [comment]
Opened an issue for the flag that @matanper proposed. Closing this issue.
https://github.com/deepchecks/deepchecks/issues/1752
