### ISSUE TITLE
[BUG] user guide pytest page is outdated

### ISSUE THREAD

**Issue by DL1992** [deepchecks/deepchecks#1691]
The user guide pytest page, https://docs.deepchecks.com/en/stable/user-guide/integrations/pytest.html, is outdated.
only showing how to use it with single checks. But it seems that after 0.8.0 you added the ability to use more functions with test suites.
This should be reflected in the docs so users will know what they can do without looking inside the code base itself

**Comment by ItayGabbay** [comment]
@DL1992 Thanks for your issue. 
If you want - you can try and contribute :) 
Anyway, we will be able to fix this in the next release
