### ISSUE TITLE
[BUG] Outlier sample detection exception

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1700]
**Describe the bug**
When scrolling through the docs I saw this error in the integrity suite:
![image](https://user-images.githubusercontent.com/20860465/177029968-6282acf6-675f-486f-90ca-f692743832b3.png)

https://docs.deepchecks.com/stable/user-guide/tabular/auto_tutorials/plot_quick_data_integrity.html

**Comment by Nadav-Barak** [comment]
DOD: Reproduce and fix
