### ISSUE TITLE
[CHAR][CV] Receive static properties instead of calculating them

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1706]
We want the vision checks to be able to receive properties as a parameter instead of calculating them

This issue should also include a sample implementation for a single check.

**Comment by TheSolY** [comment]
DoD:
A clear plan for how the relevant checks work with both pre-calculated properties and property names.

Tasks:

- [ ] Copy the list of checks that accept properties from the embedding char
- [ ] Define a signature for the properties 
- [ ] Decide where in the function the "if" between the 2 options happen 
- [ ] How will the functions signature change to support both? - 1 SP (up to here)
- [ ] Implement for one check + usage example including different properties - 2 SP
- [ ] Should the pre-calculated properties be saved as an attribute in the dataset object? - 0.5 SP

**Comment by TheSolY** [comment]
We shouldn't use the term static properties because it's confusing with static properties in a class . I suggest the names precalculated or cached

**Comment by TheSolY** [comment]
Opened an issue for the planned refractor https://github.com/deepchecks/deepchecks/issues/1753
