### ISSUE TITLE
[BUG] Model Error Analysis - when unable to train meaningful error model - add explanation + don't display it in red

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1708]
Current status: When in suite - works fine, no additional output.
When run by itself, this is display:
![image](https://user-images.githubusercontent.com/33841818/177060609-5d9cffcb-9206-4dcd-81e5-60e8f1eacdd7.png)

Problems in current situation:
1. It is red and the user thinks they have a bug.
2. They don't understand what's wrong.

Solution - change output format. consider referring to check example docs (explanation of algorithm includes what can make it it fail)

**Comment by noamzbr** [comment]
@Nadav-Barak How are we handling this in the new check?

**Comment by Nadav-Barak** [comment]
In the new check there is a more detailed explanation, can also add a link to docs but there is already one in the "more information" link

**Comment by noamzbr** [comment]
If there is a red message, turn it not red
