### ISSUE TITLE
[FEAT] Update CV Quickstarts and remove reference to full_suite

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1721]
**Is your feature request related to a problem? Please describe.**
Update CV Quickstarts, to reflect easily to the user the different tasks support and the different usage scenarios (suites for different points in pipelines).
DoD: Suggest best flow for: different tasks + different points in pipeline (different suites) and Implement the restructure.
Specifically this includes removing the `full_suite`

**Describe the solution you'd like**
Update (and possibly restructure) the CV quickstarts.

**Comment by noamzbr** [comment]
# Tasks
1. In both tutorials (classification & object detection), replace full suite with the one suite that gives the most interesting results
2. add a short discussion / sentences about the other suites, when to use them and link to the api reference with the other suites.
