### ISSUE TITLE
[FEAT] Implement new scorers

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1728]
Implement scorers for the following metrics:
[specificity](https://www.jigsawacademy.com/sensitivity-vs-specificity-in-logistic-regression/), FPR, FNR, Precision-recall AUC

**Comment by Nadav-Barak** [comment]
Also implemented all averaging machenisms (micro, macro, etc..)
Decided to pass on Precision-recall AUC since it is close enough to https://scikit-learn.org/stable/modules/generated/sklearn.metrics.average_precision_score.html#sklearn.metrics.average_precision_score
