### ISSUE TITLE
Fix issues & renaming in the simple_classification_data interface

### ISSUE THREAD

**Issue by TheSolY** [deepchecks/deepchecks#1731]
We should implement a function the accepts a path to a directory of images and returns a Dataset object in our format.
The use case is that the user has a directory of images and wants to run integrity and train-test validation checks on it, without too much preparation. 
In the future we can upgrade with preprocessing for to support model evaluation as well but I don't see it as necessary for the preliminary implementation.

Keras has a good implementation for this https://www.tensorflow.org/api_docs/python/tf/keras/utils/image_dataset_from_directory

We can expect the data to be organized like Keras expects it- train/test > class name > images belonging to class

**Comment by TheSolY** [comment]
We already have a function called load_data in simple_classification_data, but it only works if the directory contains both train and test with content divided to classes. We need to improve it rather than building from scratch.

Tasks:
1. Rename load_data to vision_dataset_from_directory
2. Add support for a single dataset without train/test split
3. Add support for a validation folder - train/validation/test split
4. Make a tutorial on how to use it, preferably in quickstart.

**Comment by TheSolY** [comment]
Clarification: the expected behavior for simple_classification_data is to support a single dataset, and the fact that it doesn't work for train if the test folder is empty is a bug.

**Comment by Nadav-Barak** [comment]
DoD: implement as described above

**Comment by noamzbr** [comment]
I don't think we need bullet number 3 (validation folder), as the rest of the package is built around train-test as the relevant datasets.
