### ISSUE TITLE
[FEAT] in evaluation suite single datasets checks can run only on test set

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1742]
**Is your feature request related to a problem? Please describe.**
There are several checks is model evaluation suite that are single dataset checks, they should by default run only on test set.

**Describe the solution you'd like**
A feature flag that allow this functionality which is by default set to true

**Comment by noamzbr** [comment]
Will be done in https://github.com/deepchecks/deepchecks/issues/2027
