### ISSUE TITLE
[FEAT] pass scorer list to model evaluation suite

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1743]
**Is your feature request related to a problem? Please describe.**
When creating a suite we should have the option to pass scorer to use in all contained checks.

**Describe the solution you'd like**
A possibility to pass scorers argument to suite + demonstrate the use of it in metrics guide + additional places in docs

I am not sure whether this functionality exist, if it does than this task should be a doc task.

**Comment by noamzbr** [comment]
I exits as part of the **kwargs mechanism, but only if the keywords are the same in each check. Anyway even if this works it should be tested that it works nicely.

**Comment by Nadav-Barak** [comment]
Additionally, should be demonstrated explicitly in metrics guide / evaluation suite quick start.

**Comment by TheSolY** [comment]
The alternative_scorers is already a parameter of the suite. Need to rename it "scorers" in the suite and in all the checks that it calls so it passes the correct kwargs to the checks.

DoD:
The scorers parameter is named "scorers" in the suite and all the checks included in it and the documentation is updated accordingly.

Tasks:

- [ ] Rename the scorer parameter "scorers" in all the checks called by the suite - 1 SP
- [ ] Rename the scorer parameter "scorers" in the suite and make sure it's passed correctly to the checks - 1SP
- [ ] Update the example in the metrics guide - 0.5 SP
- [ ] Update the plots for the suite and the checks - 1 SP

**Comment by TheSolY** [comment]
Including this issue in the tasks for the current issue https://github.com/deepchecks/deepchecks/issues/1795

**Comment by nirhutnik** [comment]
Reducing to 3 SPs - 
* going over all checks and updating names, signatures and adding deprecation warnings - 2 SPS (using pycharm's refactor will do this for plots and tests automatically)
* Adding test per check for deprecation - 1 SP

**Comment by noamzbr** [comment]
Consider how to treat tabular, vision and NLP differently

**Comment by Nadav-Barak** [comment]
@noamzbr I think they should all have the same api for passing scorers
