### ISSUE TITLE
[FEAT][Detection] Implement aggregation methods for object detection metrics

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1750]
We currently implemented precision, recall, F1 score, false positive rate, false negative rate in per class manner.
We want to also implement an averaging mechanism for them (similar to what we did in tabular) - binary, micro, macro, weighted

**Comment by TheSolY** [comment]
DoD:
The following averaging over classed mechanisms are implemented: binary, micro, macro, weighted for the following metrics: precision, recall, F1 score, false positive rate, false negative rate.

Tasks:

- [ ] Implement binary - calculate per class and show only the positive class. - 1 SP
- [ ] Implement micro - 1 SP
- [ ] Implement macro - 1 SP
- [ ] Implement weighted - 1 SP
- [ ] unittests for the new cases - 1 SP
- [ ] Update the metrics guide - 1 SP

**Comment by TheSolY** [comment]
Try to use the _averaging_mechanism from the tabular module additional_metrics
