### ISSUE TITLE
[FEAT][DOCS] Improve "supported model" explanation - how can I use my own (non scikit-learn) model?

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1754]
**Is your feature request related to a problem? Please describe.**
Currently it is not clear how to use a model wrapper for each type of task we should make the explanation it should be more elaborate.
In addition, the docs kind of mix up the scenario of "pre computed predictions" with the scenario of "your own model wrapper", they should be clearly separate scenarios. And the pre-computed predictions link should be fixed.

https://docs.deepchecks.com/stable/user-guide/tabular/supported_models.html

**Comment by Nadav-Barak** [comment]
IMO there should be in a **single** plot file with two sections - out of the box supported models (which will be short version of current supported models) and using precomputed prediction (which also be shorten).

Is this close to what you meant? @shir22

**Comment by noamzbr** [comment]
If we agree for a single file for both static predictions and model format, consider changing the name of this section.

**Comment by shir22** [comment]
@Nadav-Barak, indeed, that sounds like a good solution that will make it much clearer, given a good format and section for that page

Note - I think that it is recommended to have it as an rst file like the current one (and in its current location in docs, possibly as @noambzr suggested - with an updated more wholesome name) and not as a "sphinx gallery (plot) file"

**Comment by ItayGabbay** [comment]
@shir22 why? 
If we do this as a py file, the code will get validated in every pr and it will be much easier to catch broken things
