### ISSUE TITLE
[BUG] Some of the links in README file not working or redirecting properly

### ISSUE THREAD

**Issue by kishore-s-15** [deepchecks/deepchecks#1756]
**Describe the bug**
Some of the links in the README file not working or redirecting properly.

1. Below link does not redirect to the desired destination:

![Link Redirection Issue](https://user-images.githubusercontent.com/56688194/178528429-a0c65120-bf51-4ee2-b07c-dfb816ebf5bd.png)

2. Below link does not work:

![Link not working](https://user-images.githubusercontent.com/56688194/178528548-531579ce-469b-4458-a468-6f02ace3f161.png)

**Expected behavior**

1. Link should have redirected to the `When Should You Use Deepchecks?` section of the `Getting Started` page of deepchecks documentation. Instead it just redirects to the top of the `Getting Started` page.
2. Link should redirect to either `Which Types of Checks Exist?` section of the `Getting Started` page of deep checks documentation or the README should be changed to point to `Tabular Checks` and `Vision Checks` page of deepchecks documentation.

**Comment by kishore-s-15** [comment]
Hi,
    I am starting off my open source journey with `Deepchecks`. Can I work on this issue ?

**Comment by kishore-s-15** [comment]
https://github.com/deepchecks/deepchecks/tree/main/examples

![Examples Link not working](https://user-images.githubusercontent.com/56688194/178725119-203fa698-0d37-4580-8bfe-e7d802e5f63e.png)

The below link also has a 404 error.

**Comment by matanper** [comment]
Sure, we will be happy to get a contribution, I'm assigning this issue on you @kishore-s-15 
Do you need any help getting started?

**Comment by kishore-s-15** [comment]
> Sure, we will be happy to get a contribution, I'm assigning this issue on you @kishore-s-15 Do you need any help getting started?

For README files which are outside `docs` folder, can I just change the URLs and open a pull request?

**Comment by kishore-s-15** [comment]
https://github.com/deepchecks/deepchecks/tree/main/deepchecks/vision

Issues from Vision README file, The below link return 404.

![Vision README Issue 1](https://user-images.githubusercontent.com/56688194/178726783-94a60cd3-2765-4b94-bcbe-0dc888c60d67.png)

![Vision README Issue 2](https://user-images.githubusercontent.com/56688194/178726822-8f534839-e539-4c1c-9762-9bc51eb02e81.png)

**Comment by matanper** [comment]
> > Sure, we will be happy to get a contribution, I'm assigning this issue on you @kishore-s-15 Do you need any help getting started?
> 
> For README files which are outside `docs` folder, can I just change the URLs and open a pull request?

yes

**Comment by kishore-s-15** [comment]
On the project level README file, `Train-Test Validation Quickstart (loans data) `link points to `Quickstart - Data Integrity Suite` instead of `Quickstart - Train-Test Validation Suite` page.

![README Issue](https://user-images.githubusercontent.com/56688194/178728250-01a0c5cd-7238-4eb2-b4e9-efa1f6ac9d2b.png)

**Comment by kishore-s-15** [comment]
> > > Sure, we will be happy to get a contribution, I'm assigning this issue on you @kishore-s-15 Do you need any help getting started?
> > 
> > 
> > For README files which are outside `docs` folder, can I just change the URLs and open a pull request?
> 
> yes

Ok.

**Comment by kishore-s-15** [comment]
@matanper Where do you want me to point this link to ? Currently we have two types of checks (i.e) [Tabular Checks](https://docs.deepchecks.com/stable/checks_gallery/tabular.html) and [Vision Checks](https://docs.deepchecks.com/stable/checks_gallery/vision.html).

![Link not working](https://user-images.githubusercontent.com/56688194/178729379-0bcd5ddd-0cc3-459c-8e26-743fab8b43b5.png)

**Comment by kishore-s-15** [comment]
I have made the necessary changes to the project level and vision README files.
