### ISSUE TITLE
[FEAT] Enable explicit control of FI calculation

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1757]
**Is your feature request related to a problem? Please describe.**
We want the user to be able to use our feature importance calculation mechanism easily in two scenarios:
1. Passing calculated feature importance to a check/suite 
2. Calculating feature importance and exporting the FI Series to an external source

**Describe the solution you'd like**
Currently if the user wants to control the FI calculation he can either pass a FI Series he calculated elsewhere, or modify one of the following parameters of the run() method:
```
        feature_importance_force_permutation: bool = False,
        feature_importance_timeout: int = 120,
```
We want the option for an intermediate flow - use something equivalent to our `calculate_feature_importance` method (perhaps with the permutation_kwargs explicitly stated), get an FI Series that can be inspected, and then pass it to the run() feature_importance arg.

Also add to docs

**Describe alternatives you've considered**
This creates a "two ways to do one thing" situation, so need to consider if there is a way to simplify.

*Additional alternative*: create a sub package with SHAP that can calculate way better FI compare to permutation importance.

**Comment by nirhutnik** [comment]
### DoD:
New function + example of use in documentation

### Inputs:
New function name - calculate_feature_importance
args: all sklearn.permutation_importance args. 
no timeout.

### Outputs:
The same format we expect.

### Tasks:
* Create and separate function - 1 SP
* Add test
* Add section in feature importance guide.  - 1 SP

**Comment by Nadav-Barak** [comment]
After completed use this in relevant checks plot examples to reduce run time (check whose model is a pipeline that do not have FI - such as Unused features)
