### ISSUE TITLE
[FEAT][Vision] ability to use deepchecks tabular classification metrics

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1760]
**Is your feature request related to a problem? Please describe.**
Currently vision classification scorers act as follow : we look for a deepcheck vision implementation of scorer name and if we do not find one we try and look for a scorer with that name in sklearn

Some examples: fnr_per_class, fnr_macro, fnr_micro ... 

**Describe the solution you'd like**
Instead / in addition to looking in sklearn, look in the dict of names available for the tabular classification.

Bonus to consider:
Remove the deepcheck implemented vision classification scorers (precision and recall) and automatically search scorer in the tabular scorers dict

**Comment by JKL98ISR** [comment]
was done
