### ISSUE TITLE
[BUG] Format precentage in new category output

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1766]
**Describe the bug**
<img width="1028" alt="CleanShot 2022-07-14 at 10 38 05@2x" src="https://user-images.githubusercontent.com/33841818/178928294-4771baed-2769-45fb-b947-b7346e7c0f83.png">

See "percent of new category in sample"

**To Reproduce**
Use to following dataset:
https://github.com/AllonHammer/CPI_HRNN/blob/master/resources/cpi_us_dataset.csv
Dataset definition:
`ds = Dataset(df, datetime_name='Date', label='Price', cat_features=['Category_id', 'Category', 'Indent', 'Parent', 'Parent_ID'])
`
Split first 40000 samples to be train, and the rest to be test.
And run the relevant checks (or the `train-test-validation` suite)

**Comment by kishore-s-15** [comment]
@shir22 Could you mention the steps to reproduce this issue ?

**Comment by TheSolY** [comment]
@shir22 If I understood correctly, the issue is that the conditions summary shows "0.02%" but the additional outputs show "0.00" and they should show the same number. Which dataset did you use?

**Comment by shir22** [comment]
Yes, indeed @TheSolY . And specifically, for consistency, to use the same formatting function as is used in the "More Info" in the Conditions Summary table...

About the dataset + steps to reproduce: I added the specific steps in the edited issue description

**Comment by shir22** [comment]
@kishore-s-15 would you like to be assigned to this one?

**Comment by noamzbr** [comment]
Granted, and much appreciated!

**Comment by kishore-s-15** [comment]
@shir22 Could you provide the code to reproduce the above error?

```
import pandas as pd

from deepchecks.tabular.dataset import Dataset
from deepchecks.suites import train_test_validation

df = pd.read_csv("./cpi_us_dataset.csv")

train_df = df.iloc[:40000, :]
test_df = df.iloc[40000:, :]

train_ds = Dataset(train_df, datetime_name='Date', label='Price',
        cat_features=['Category_id', 'Category', 'Indent', 'Parent', 'Parent_ID'])

test_ds = Dataset(test_df, datetime_name='Date', label='Price',
        cat_features=['Category_id', 'Category', 'Indent', 'Parent', 'Parent_ID'])

suite = train_test_validation()
suite.run(train_ds, test_ds)
```

I used the above code but was not able to reproduce the issue.

**Comment by shir22** [comment]
Can you show the print screen of the Category Mismatch Test?
I just ran your code now, and this was the output, like in the original description it shows 0.00

![CleanShot 2022-07-24 at 18 51 55](https://user-images.githubusercontent.com/33841818/180655509-24cdaa0d-971d-476f-9ce4-32fcf70c3e41.png)

**Comment by kishore-s-15** [comment]
My bad, I ran the code as a script file instead of a notebook file. Got the same output now.
