### ISSUE TITLE
[FEAT] Date parsing - improve date print 

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1767]
**Is your feature request related to a problem? Please describe.**
Print doesn't look good, we should handle the date prints ourselves 
(and not print hour minutes (mileseconds... etc.) if dates aren't given in that resolution)

For all relevant checks

See example:
<img width="561" alt="CleanShot 2022-07-14 at 10 41 02@2x" src="https://user-images.githubusercontent.com/33841818/178928888-8204ee83-e1bc-4379-8126-6fa7c192f425.png">

**Comment by noamzbr** [comment]
Related to #1769 and should be done together

**Comment by nirhutnik** [comment]
Baked with #1769
