### ISSUE TITLE
[BUG] Date Leakage Checks

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1769]
**Describe the bug**
A few things here:
<img width="572" alt="CleanShot 2022-07-14 at 12 05 40@2x" src="https://user-images.githubusercontent.com/33841818/178946155-300a1b83-5bd3-4a97-82e8-937be232f5e5.png">

1. Overlap shouldn't find case of duplicates (in this case no overlap, just duplicates). The sentence "1.26% of test data dates before last training data date (2016/05/15 00:00:00.000000 )" isn't correct, as they aren't before...
2. Output of the duplicates - give the column name a relevant title (currently "0")
3. Seems that the percentage size isn't correct in the duplicates (should be 1.26%).
4. Overlap check should give a few examples of the previous dates (show the earliest in test)

**To Reproduce**
Use to following dataset:
https://github.com/AllonHammer/CPI_HRNN/blob/master/resources/cpi_us_dataset.csv
Dataset definition: 
`ds = Dataset(df, datetime_name='Date', label='Price',
             cat_features=['Category_id', 'Category', 'Indent', 'Parent', 'Parent_ID'])`

Split first 40000 samples to be train, and the rest to be test.
And run the relevant checks (or train-test-validation suite)

**Comment by nirhutnik** [comment]
### Tasks:
* Fix percentage mistake in "duplicates" - counting a set's length and that's why it's wrong
* Fix column name in "additional info" - rename to "duplicate values"
* Create function for pretty printing dates based on truncated value and use it for dates. get read of space before right parenthesis.

**Comment by noamzbr** [comment]
Added 0.5 SP to facilitate writing tests for the current bugs and for the pretty date printer thing

**Comment by shir22** [comment]
About overlap -  I am strongly for verifying that overlap conditions fits the textual description in the check:
"test data is earlier than train data", and specifically to not fail check if the status is that "latest test data is equal to earliest train data", like in the attached screenshot.
If you disagree please elaborate

**Comment by nirhutnik** [comment]
Updated the overlap due to the conv with Shir
