### ISSUE TITLE
[FEAT][DOCS] Put quickstarts in a separate section than the other tutorials in the User Guide

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1770]
**Is your feature request related to a problem? Please describe.**
Currently they're all together (various guides & quickstart tutorials) and it's hard to understand what's going on and to navigate.
<img width="364" alt="CleanShot 2022-07-14 at 12 14 54@2x" src="https://user-images.githubusercontent.com/33841818/178947966-35b05460-219d-41df-a408-001046cfda21.png">
Relevant both in Vision and in Tabular.

Would want the quickstarts to be in a separate subsection with only them
e.g. in Tabular Quickstarts & Vision quickstarts
note - update relevant links (in welcome.rst & make sure that we have a correct redirect to the 5 min quickstart as that link appears in various places)

**Comment by ItayGabbay** [comment]
@kishore-s-15 I assigned it to you. 
Feel free to ping me with any question :)

**Comment by ItayGabbay** [comment]
@kishore-s-15 Looks good. These files are being generated by sphinx-gallery. You can have a look at the sphinx gallery configuration on the conf.py.

When changing - make sure you do the necessary changes in the conf.py or create subgalleries.
