### ISSUE TITLE
[FEAT][Tabular] prediction drift classification update

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1775]
By default prediction drift should run on probas and multiclass should be PSI but in addition we should add a flag that controls which one to use.

Add abilities to run on probas for both binary and multiclass 
Add support in them for reduce_output()
Handle display stuff for multiclass probas drift option

**Comment by noamzbr** [comment]
## Goal
Prediction drift computes and displays drift on the proba scores outputted by the model. This is done per class.
Update this behavior for both tabular and vision checks.
Default behavior - the check computes drift on the proba for binary classification and on the decision for multiclass. 

## DoD
Updated checks for both tabular and vision packages. Add example of that to both examples.

**Inputs**:
The check will have the additional following arguments (names are open to change):
- probability_drift='auto'. Controls whether to compute drift on proba or decision, enables the user to force either option.
- max_classes_to_display=3. Maximal number of classes to display when showing drift on the proba per class.

**Display**:
When computing on proba, display the distribution of the proba for each class, max max_classes_to_display classes. Sort classes by amount of drift.
