### ISSUE TITLE
[FEAT] Replace VisionSegmentPerformance and ModelErrorAnalysis with Vision Weak Segment Performance

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1780]
**Is your feature request related to a problem? Please describe.**
In the tabular package we replaced SegmentPerformance and ModelErrorAnalysis with the new Weak Segment Performance. Should do also for vision.

**Describe the solution you'd like**
An equivalent of the tabular Weak Segment Performance, partitioning on properties.

**Complications**
1. The current Image Segment Performance caches predictions and labels before partitioning according to properties and computing metrics. This won't work for segmentation. Consider - can we know in advance what are the max/min values of properties before calculating.
2. Adapting this to embedding properties.

**Comment by Nadav-Barak** [comment]
Weak segment performance can work quite similarly, but requires the following inputs:
needs to receive as input a dataframe for properties values per image. 
need to receive loss per image (this will require thinking how to calculate for object detection / segmentation)

Output will look as in tabular, Heatmap with segments based on properties.
