### ISSUE TITLE
[BUG] When model type / column type aren't relevant for check, don't display this as "Error"

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1813]
**Describe the bug**
See Model Evaluation Quickstart Output, under "Didn't Run":
![CleanShot 2022-07-24 at 18 09 58](https://user-images.githubusercontent.com/33841818/180653508-0daf809e-ec2a-4dfa-ba57-328ea4807613.png)
and also Data Integrity Quickstart:
![CleanShot 2022-07-24 at 18 12 20](https://user-images.githubusercontent.com/33841818/180653633-df5a0d68-4c6e-4fbc-b9cc-76e52f4b3b2d.png)

Text is "ModelValidationError: Check is..."
User feedback: this shouldn't state "error", but just explain that the check isn't relevant.
(Note: We've fixed this previously, verify that we revert this for all relevant scenarios when "check is irrelevant...)

**Comment by nirhutnik** [comment]
### Logic:
In core/serialization/common.py, in create_failures_dataframe, we add the type of exception to the message we add to failed check. We should add a filter there, that for some Exceptions, we won't print the name of the exception and just the message.
Alternatively, we can change the name of the exception (and similar ones) to "NotImplementedForModelType" or something like that.

### Tasks:
* Decide (with Shir & Gabbay) on which approach to take.
* Implement - 0.5 SP

**Comment by nirhutnik** [comment]
Ok, scratch that:
code before that just states which exceptions to include the name in, should just remove ModelValidationError and make sure that it makes sense for everywhere it's raised
