### ISSUE TITLE
Improve Cramer's V by fixing small categories

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#1816]
Cramer's V is inferior to PSI because we added handling of smaller categories to PSI, while we have not done so for Cramer's V.

There are some ways to do the same for Cramer's V - namely, using the same solution (of clustering small categories together) or just simply ignoring small categories. 

Would suggest this to be enabled as a third method - "cramers_v_corrected" or something. No need to enforce it on everyone. Sometimes the sensitivity to small categories is important

**Comment by nirhutnik** [comment]
### Inputs:
Add new drift method - "cramers_v_corrected" or something similar that is clear that corrects small categories.

### Logic:
Try 2 methods:
1. all categories with less than X (5?) instances - unite to one category.
2. Drop categories with under than X instances


### Tasks:
* Create the new method - 1 SP
* Compare it to previous method + PSI using Nir's notebook. Make sure it is stable like PSI is. - 1 SP
* Add tests and add to all relevant checks + docstrings - 2 SP

**Comment by Nadav-Barak** [comment]
@nirhutnik Send me Nir's notebook and expect some follow up questions
