### ISSUE TITLE
[FEAT] Help user avoid misclassification of task type

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1820]
**Is your feature request related to a problem? Please describe.**
When a Dataset is created, task type is inferred using the label.
Sometimes this is done incorrectly, e.g. see #1814 (inferred as multiclass classification instead of regression), and may result in weird result values.

**Describe the solution you'd like**
1. For multiclass of integers, add a warning when inferring task type that we found x values of the label and interpreted them as multiclass, but they could be regression as well, with a code snippet of how to define this.
2. For checks that use the task type and the prediction value (such as the Train Test Prediction Drift, but not limited ot it) add a validation that the prediction value indeed fit the defined task type, in if they don't - check should return an error or warning, with explanation how to define task type to avoid this issue. (otherwise we'll be displaying meaningless results on predictions... whether it's drift calculation, model performance metrics, etc.)

**Comment by DanBasson** [comment]
@nirhutnik can you please assign this issue to me?

**Comment by nirhutnik** [comment]
> @nirhutnik can you please assign this issue to me?

@DanBasson Done :)
