### ISSUE TITLE
[BUG] Conflicting labels n_to_show behavior 

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1828]
**Describe the bug**
The n_to_show should change only the number displayed, not the "out of how many...", see here:
![CleanShot 2022-07-26 at 17 10 35@2x](https://user-images.githubusercontent.com/33841818/181027405-5a71c475-66c4-484d-bf15-45c928432017.png)
Screenshot taken from [Conflicting Labels Docs Page](https://docs.deepchecks.com/stable/checks_gallery/tabular/data_integrity/plot_conflicting_labels.html)

**Comment by TheSolY** [comment]
DoD: n_to_show changes the first but not the second number.
