### ISSUE TITLE
[BUG] Whole Dataset Drift display looks bad when runs on categories with long names

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1832]
**Describe the bug**
See screenshot:
![CleanShot 2022-07-26 at 19 13 03](https://user-images.githubusercontent.com/33841818/181057447-b046acff-fdd2-4bd6-aefb-052db830ec47.png)

**To Reproduce**
Run:
```
import pandas as pd
import numpy as np

from deepchecks.tabular.dataset import Dataset
from deepchecks.tabular.checks import WholeDatasetDrift

df = pd.read_csv("data/cpi_us_dataset.csv")

train_df = df.iloc[:40000, :]
test_df = df.iloc[40000:, :]

features = ['Category', 'Weight', 'Parent', 'Indent']
cat_features = ['Category', 'Parent', 'Indent']

train_ds = Dataset(train_df, datetime_name='Date', label='Price',
        cat_features=cat_features, features=features)

test_ds = Dataset(test_df, datetime_name='Date', label='Price',
        cat_features=cat_features, features=features)

WholeDatasetDrift().run(train_ds, test_ds)
```

On the [following dataset](https://github.com/AllonHammer/CPI_HRNN/blob/master/resources/cpi_us_dataset.csv) (as "data/cpi_us_dataset.csv")

**Comment by noamzbr** [comment]
Proposed solution - find the max length of display that "looks good" and shorten all names to match, e.g. shorten "Owners equivalent rent of primary residence" to "Owners equival..."

**Comment by shir22** [comment]
It's quite common to have long names, I think the solution should include
more than ~14 chars
and best if it's extendable by hover-over

**Comment by noamzbr** [comment]
Note - investigate why the * about sampling shows so close to the plot (and this overlaps with the x axis labels)
