### ISSUE TITLE
[DOC] missing documentation for static predictions in vision

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1847]
missing documentation for static predictions in vision

the one who'll write it can use the tabular static prediction tutorial and the vision static prediction tests for help.

**Comment by TheSolY** [comment]
DoD: a tutorial for passing static predictions in vision including motivation and code examples.
The tabular tutorial for reference https://docs.deepchecks.com/en/stable/user-guide/tabular/auto_tutorials/plot_static_predictions.html#sphx-glr-user-guide-tabular-auto-tutorials-plot-static-predictions-py

**Comment by noamzbr** [comment]
Note that this is simpler because no need for "model wrapper" guide here, but harder because format of predictions is more complex for object detection. 
Consider what docs need to link to this guide. For example, quickstarts?

**Comment by Nadav-Barak** [comment]
Note - the link you added above is a old doc that we deleted, better to use relevant sections [here](https://docs.deepchecks.com/dev/user-guide/tabular/supported_models.html) for reference
