### ISSUE TITLE
[FEAT] Rename Whole Dataset Drift check to Multivariate Drift

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#1848]
**Is your feature request related to a problem? Please describe.**
Multivariable drift is a better name than the WholeDatasetDrift. Several requests from the community came in about that.

**Comment by noamzbr** [comment]
Remove ImageDatasetDrift from vision

**Comment by ItayGabbay** [comment]
@kishore-s-15 assigning this to you

**Comment by kishore-s-15** [comment]
Sure, Thanks @ItayGabbay. I'll work on it.
