### ISSUE TITLE
[Docs] Documentation contains a mistake.

### ISSUE THREAD

**Issue by cemalgurpinar** [deepchecks/deepchecks#1849]
Package Version: 0.8

In "Additional Notes about Conditions in a Suite" section, there is a second bullet like "Most check classes have built-in methods for adding monditions.". The word "monditions" should be change with "conditions".

Best regards.

Cemal GURPINAR

**Comment by Nadav-Barak** [comment]
Hey @cemalgurpinar, good catch!
Would you be interested in contributing by uploading a PR fixing this issue?

Thank you

**Comment by cemalgurpinar** [comment]
Definitely, I will !
