### ISSUE TITLE
[BUG] Numbers in FeatureLabelCorrelationChange display plot are illegible because they are too small

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1850]
**Describe the bug**
The numbers over the test set, that include also the percentage change, are in much smaller font and therefore hard to read.
![CleanShot 2022-07-31 at 16 28 38](https://user-images.githubusercontent.com/33841818/182028625-cacab8fa-83a7-492c-9a38-2de33abb641f.png)

**To Reproduce**
See here:
https://docs.deepchecks.com/stable/checks_gallery/tabular/train_test_validation/plot_feature_label_correlation_change.html#run-the-check

**Expected behavior**
Make numbers clearer.
If possible - have percent change in a different color (for clarity). nice to have, not very important.

**Comment by TheSolY** [comment]
DoD: fix the display font and possibly color.
