### ISSUE TITLE
Not clear how to add static predictions to SingleDataSet checks

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1852]
In order to pass static predictions to a SingleDataSet checks you have to pass them into the y_pred_train argument.
For SingleDataSet checks this is not intuitive.

Do not have a cooked suggestion, maybe override the run function in SingleDatasetCheck class with different arguments.

**Comment by noamzbr** [comment]
Yes should have only a single y_pred & y_proba in these checks

**Comment by noamzbr** [comment]
### DoD:
* Both vision and Tabular SingleDatasetCheck receive only pred/proba for a single dataset, not train and test. It is passed to the train dataset proba/pred in the context.

**Comment by noamzbr** [comment]
deprecation warning

**Comment by Nadav-Barak** [comment]
In addition - add input validation for the

**Comment by TheSolY** [comment]
Tasks:

- [ ] refactor vision SingleDatasetCheck 1 SP
- [ ] refactor tabular SingleDatasetCheck 1 SP
- [ ] add tests

**Comment by TheSolY** [comment]
On a personal note I think that it's very clear to pass the static predictions (and properties) only to train and this issue is unnecessary.
