### ISSUE TITLE
[FEAT] First steps in nlp

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1858]
Taking our first steps into creating deepchecks.nlp

In general, nlp package will support currently only static prediction (no model object) for different types of classification tasks. Also at first, will only support train test validation (mainly drift) and model evaluation

Steps included in this issue:
1. Arc talk, Agree on general concept + structure + formats for input data / labels and for static predictions
1.1 How prediction are handled? cached? static properties?
2. Build general structure for package + context + base suite + Dataset (input + label + validation)
3. Input validation for input structure and str (not the internal labels format)
4. First check - properties drift with 2 basic properties (str length, number of words)
5. Mechanism to pass static properties (as DataFrame in different argument to run)
6. First suite - train test validation which will contain the first check

Steps not included in this issue:
1. Documentation
2. Input validation for labels
3. handle static predictions + metrics, working with labels

**Comment by noamzbr** [comment]
What will be achieved by the end of the task:

1. Package base - dataset, base checks, suite obj.
2. SingleDatasetPerformance check for multiclass + multilabels
3. default model eval suite 
4. tests
