### ISSUE TITLE
[FEAT] Add package installation explanation to vision quickstarts

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1865]
**Is your feature request related to a problem? Please describe.**
If a user arrives to the vision quickstart (which is a reasonable entry point) the "how to install" isn't accessible (not a code snippet, nor a link to the installation guide).

**Describe the solution you'd like**
Adding to all CV quickstarts installation instructions for the deepchecks for CV submodule.
See example in tabular quickstarts, e.g. [data integrity quickstart](https://docs.deepchecks.com/dev/user-guide/tabular/auto_quickstarts/plot_quick_data_integrity.html)
<img width="651" alt="CleanShot 2022-08-02 at 01 03 09@2x" src="https://user-images.githubusercontent.com/33841818/182253618-03d75e64-0453-4e78-8659-d4955c695b29.png">

**Comment by noamzbr** [comment]
Add the following code to the head of quickstart examples:
```
import sys
!{sys.executable} -m pip install "deepchecks[vision]" --quiet --upgrade # --user
```

**Comment by kishore-s-15** [comment]
Can I work on it @noamzbr @shir22 ?

**Comment by kishore-s-15** [comment]
> Add the following code to the head of quickstart examples:
> 
> ```
> import sys
> !{sys.executable} -m pip install "deepchecks[vision]" --quiet --upgrade # --user
> ```
> 
> (Also, do make sure it actually does what it's supposed to)

The above code snippet works on local and also on google colab. I can add it to [Image Data Validation quickstart](https://docs.deepchecks.com/dev/user-guide/vision/auto_quickstarts/plot_simple_classification_tutorial.html), similar to [Data Integrity quickstart](https://docs.deepchecks.com/dev/user-guide/tabular/auto_quickstarts/plot_quick_data_integrity.html)
