### ISSUE TITLE
[FEAT] research embedding methods + properties

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1868]
Research methods we can use in our NLP package
Come up with a suggestion how to implement those methods inside checks
Discuss options in arc / algo talk

**Comment by TheSolY** [comment]
DoD: 
a document detailing common embedding methods and properties for NLP, and suggestions on using them in checks.
Tasks:

- [ ] Research common NLP embedding methods -2 SP
- [ ] Research common properties, and suggest other reasonable ones - 1SP
- [ ] Suggestions for checks that can use properties and embedding - 0.5 SP
- [ ] arc talk

**Comment by Nadav-Barak** [comment]
Link to updated NLP research doc https://docs.google.com/document/d/15fRuqEigkeW8dJF4aS03ukZxMVXNVbQBI0yf540yHkQ/edit#

**Comment by TheSolY** [comment]
https://docs.google.com/document/d/15gSgOvRxu17jpaBLdX-2PxIJ7qIhZ4SOGucjqjLh9WM/edit#heading=h.hn6o7w2k4dlb
