### ISSUE TITLE
[FEAT] Add support for token classification metrics

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1869]
Research which metrics are common. Can we use also ranking metrics using sklearn?

Add support in them to the DeepChecksScorer

No need to support them in tabular checks

See if easy to extract relevant stuff from tabular metrics to core (because used by all packages no only tabular)

**Comment by noamzbr** [comment]
## DoD
1. There are tests in place that make sure that multilabel sklearn metrics can be computed from static labels and predictions using DeepChecksScorer
2. List of important multilabel metrics that sklearn does not support that we need to add + opened issue for that

**Comment by noamzbr** [comment]
# Change of plans
This task is now about adding support for token classification metrics using the seqeval library

**Comment by noamzbr** [comment]
Closed by #1959
