### ISSUE TITLE
[FEAT] Update custom vision task to note that Segmentation is already part of the package

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1887]
**Is your feature request related to a problem? Please describe.**
As segmentation is added as a built in part of the package, changes should be introduced to the existing segmentation custom task guide to let the user know it's just an example, and that for actual segmentation they should use the built in solution.

Make sure that the built in solution and the custom task don't diverge seriously. 

**Additional context**
This is a temporary solution until https://github.com/deepchecks/deepchecks/issues/1856 is done.

**Comment by nirhutnik** [comment]
Just change the wording to clarify that this custom check is instance segmentation and not semantic segmentation
And change the class names to reflect this
