### ISSUE TITLE
Semantic segmentation - Tests & Docs

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#1888]
Continues #1039 

Tasks:
- Add tests for SegmentationData - 0.5
- Add tests for checks with elif for segmentation (with working model) - 0.5
- Add tests for properties - 0.5
- Update checks docstrings - 0.5
- Add use-case of semantic segmentation to docs - 3 SP

Moved some tasks to #1939

**Comment by nirhutnik** [comment]
Might-be-usable code for semantic segmentation in PropertyLabelCorrelationChange - 

```
        elif dataset.task_type == TaskType.SEMANTIC_SEGMENTATION:
            for img, label in zip(batch.images, batch.labels):
                for seg_label in np.unique(label):
                    seg_location = label == seg_label
                    seg_img = np.expand_dims(seg_location, axis=2) * img
                    class_id = int(seg_label)
                    imgs += [seg_img]
                    target += [dataset.label_id_to_name(class_id)]
            property_type = PropertiesInputType.PARTIAL_IMAGES
```

**Comment by TheSolY** [comment]
also add the new default properties to test_default_properties in properties_utils_tests
and a test for label_property_outliers with a segmentation task
