### ISSUE TITLE
[FEAT] Add validation in tabular dataset creation that there are no columns with identical names

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1909]
**Is your feature request related to a problem? Please describe.**
A pandas dataframe can have columns with the same name, but for the operation of the deepchecks package that can lead to unexpected bugs.

**Describe the solution you'd like**
Validate that this is not the case in the dataset init

**Comment by kishore-s-15** [comment]
Hi @noamzbr, Can I work on this issues ?

As mentioned [here](https://github.com/deepchecks/deepchecks/pull/1895#discussion_r945306496), I'll add a validation to check if `df` have duplicate column names in [dataset.py](https://github.com/deepchecks/deepchecks/blob/main/deepchecks/tabular/dataset.py)

**Comment by noamzbr** [comment]
Hi @kishore-s-15, sorry for the late reply I missed you're comment here. 
It would be great if you can take that! Only thing I'd ask is that the error message will also tell the user **what column names** are duplicated, rather than just alert him to that fact.

**Comment by kishore-s-15** [comment]
Sure, I'll work on it. Thanks @noamzbr

**Comment by kishore-s-15** [comment]
@noamzbr I have come up with a couple of methods for listing out the names of the duplicated columns.

1. Using python set data structure for finding the duplicated columns.

```
dataset_columns = list(df.columns)

columns_hashset = set()

duplicated_columns = list()

for column in dataset_columns:
  if column in columns_hashset:
    duplicated_columns.append(column)
  else:
     columns_hashset.add(column)

```

2. Using Counter datatype
```
from collections import Counter

duplicated_columns = []

columns_counter = Counter(df.columns)

for column, frequency in columns_counter.items():
  if frequency > 1:
      duplicated_columns.append(column)
```

The duplicated_columns list contains the duplicated columns in both the methods.

**Comment by kishore-s-15** [comment]
I'll make the changes now.
