### ISSUE TITLE
[FEAT] Runtime improvement for drift checks

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1914]
**Is your feature request related to a problem? Please describe.**
We would like to have a run time of <1ms per column for 10K samples for both categorical and numerical drift. Barring that, let's try to reduce the runtime. Currently Carmers-v takes double the time of earth movers.

Profiling results at https://drive.google.com/file/d/1OtrUg48rV9jRNL9tMHCgat7KDYGVTus3/view?usp=sharing

**Describe the solution you'd like**
Some suggestions:
1. Are there arguments for these scipy functions that can be played with?
2. Are there alternative OSS implementations?
3. numba
4. intel libraries

**Describe alternatives you've considered**
Revert to PSI as default categorical drift.

**Once Done**
Update the benchmark spreadsheet

**Comment by nirhutnik** [comment]
### DoD:
* TrainTestFeatureDrift calculation time for 10,000 samples is now X3 faster
* Update the benchmark spreadsheet


### Tasks:
* Map the main reasons why these calculations are slow - 1 SPs
* Find alternative solutions - scipy, numba, numpy, different algorithm, calculate things only once, calculate estimation. Add tests. - 2 SPs.
* Extra SP for the fact that there's no clear solution - 1 SP.

**Comment by noamzbr** [comment]
Closed as code relies on basic optimized python / numpy operations (Counter for categorical, np.argosrt for numeric).
#1966 is related but does not solve the underlying issue
