### ISSUE TITLE
[FEAT] Runtime improvement for performance checks

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1918]
**Is your feature request related to a problem? Please describe.**
We would like to have a run time of <1ms 10K samples for performance checks running several (3?) metrics. Barring that, let's try to reduce the runtime. Currently performance calculation takes way more than that, as can be seen here:

[profiling performance.txt](https://github.com/deepchecks/deepchecks/files/9358944/profiling.performance.txt)
(rename txt to html locally and open)

**Describe the solution you'd like**
Some suggestions:
1. Are there arguments for these scipy functions that can be played with? Can we pass the list of labels in advance and save time on computing unique labels?
2. Are there alternative OSS implementations?
3. intel accelerated sklearn
4. numba

Once Done
Update the benchmark spreadsheet

**Comment by Nadav-Barak** [comment]
After discussion decided on need to reduce run time as much as possible and preferably at least X2.
Candidates for easy improvements are:
1. shared confusion matrix between scorers
2. reduce runtime of scorers validation

**Comment by ItayGabbay** [comment]
Intel acceleration won't work
