### ISSUE TITLE
[FEAT] Docs for nlp package

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1940]
Create documentation for the NLP package that matches the documentation of the vision package.
 
**Components**
- [ ] #1976
- [ ] Add a "NLP Checks" section
- [x] #1971
- [ ] #1972
- [ ] #1973
- [ ] #1974
- [ ] #1975
- [ ] Add NLP to the getting started + Readme
- [ ] API reference for NLP

**Comment by noamzbr** [comment]
Currently - the only thing is adding the NLP Check section

**Comment by nirhutnik** [comment]
No need for parent issue.
All tasks either done as part of #1907 or will be closed separately later
