### ISSUE TITLE
Unify the API for passing number of samples to the tabular checks

### ISSUE THREAD

**Issue by TheSolY** [deepchecks/deepchecks#1942]
Similar to what we did for Vision: https://github.com/deepchecks/deepchecks/issues/1863
Currently it's sometime passed to the init, for example in feature_feature_correlation has a parameter n_samples, and sometime to the run.
Should be passed only to the run in on all of the tabular checks.

**Comment by noamzbr** [comment]
Something we need to address - currently different check have a different default number of samples (and rightly so, integrity checks can and should run on more samples). This will go away if we implement this.

**Comment by noamzbr** [comment]
Decision: Add n_samples init argument to all tabular checks

**Comment by noamzbr** [comment]
Closed by https://github.com/deepchecks/deepchecks/issues/2013
