### ISSUE TITLE
Adult dataset label is corrupt

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#1970]
Adult dataset label has 4 unique values instead of 2 - '<=50K' and '<=50k.' both mean the same thing.
Should fix + make sure fixed in examples

**Comment by nirhutnik** [comment]
This requires a change either in the dataset itself in figshare, or in the processing we do. 
I think it's much easier fixing in the processing.

So - 
* fix the processing - 0 SP
* Change tests and docs accordingly (make sure they still yield our wanted results) - 0.5 SP

**Comment by TheSolY** [comment]
Doesn't happen when divided to train and test
