### ISSUE TITLE
[BUG] change usage of classes in scorers to use not just dataset classes but also predictions

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1981]
**Describe the bug**
incorrect behavior in some model evaluation checks using dataset classes and scorers
if a prediction contains a new class the results might shift and be incorrect

easiest to see in SingleDatasetPerformance check and pass y_pred_train with a new class

the fix should be a set of dataset.classes (classes fund in label) and classes found in prediction - fix all scorers using predict

p.s also needs tests

**Comment by noamzbr** [comment]
Fixed by #2050
