### ISSUE TITLE
[FEAT] Add ap ar scorers with averaging method 

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1984]
Currently we only support average_precision_per_class, average_recall_per_class

we should also support macro / micro/ weighted

**Comment by TheSolY** [comment]
DoD:
Object detection metrics average precision and average recall support averaging options macro / micro/ weighted.

Tasks:

- [ ] Implement macro and weighted macro 1 SP
- [ ] Implement micro 1 SP
- [ ] Tests 0.5 SP
- [ ] Update the Metrics Guide 0.5 SP

**Comment by TheSolY** [comment]
Implement micro moved to https://github.com/deepchecks/deepchecks/issues/2078
