### ISSUE TITLE
[FEAT]Displaying stemmed words in NLP checks

### ISSUE THREAD

**Issue by TheSolY** [deepchecks/deepchecks#2023]
In the display of KeywordFrequencyDrift the words appear in their stemmed form which is less readable.
Transform the words to a readable form.
Will be relevant for future NLP checks as well.
Points to consider: what is the best grouped form? how others are doing it, for example in word clouds?
![image](https://user-images.githubusercontent.com/99395146/190983503-9a2f21f2-f123-4745-95b9-1b98bcb393cd.png)

**Comment by TheSolY** [comment]
DoD:
KeywordFrequencyDrift display shows words in a non-stemmed manner.

**Comment by TheSolY** [comment]
I couldn't find an off the shelf way to do it, others use lemmatization instead of stemming so the tokens used in the algorithm are more readable to begin with.

**Comment by TheSolY** [comment]
![image](https://user-images.githubusercontent.com/99395146/198324865-9193c897-cb77-4684-a370-102900e195ae.png)
Looks better now

**Comment by noamzbr** [comment]
Closed by https://github.com/deepchecks/deepchecks/pull/2114
