### ISSUE TITLE
[FEAT] Add flag in suite run() controlling SingleDatasetCheck behavior 

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#2027]
**Is your feature request related to a problem? Please describe.**
Currently suite always runs SingleDatasetChecks on both train and test. For certain use cases this is not ideal.

**Describe the solution you'd like**
Add a flag in the suite run() controlling this. Default is to keep the status-quo and run on both datasets. Alternative would be running only on test.

**Comment by TheSolY** [comment]
Need to do this for both vision and tabular
