### ISSUE TITLE
[FEAT] Support simpler IOB annotation for token classification

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#2030]
**Is your feature request related to a problem? Please describe.**
In addition to the existing support for token classification with the `(class, start_span, end_span)` label annotation format, support the IOB format of `['ttoken1', 'token2'] ['class1', 'class2']` (which doesn't allow for mismatch of tokenization between the labels and the model predictions.

**Describe the solution you'd like**
Enable the user to provide the simpler IOB annotation as input for the TextData

**Comment by nirhutnik** [comment]
### DoD:
NLP module works, by default, using the IOB annotation. It also supports and can receive the Bressler annotation.

### Background:
Check SingleDatasetPerformance already works with the IOB format, translated by the span_aligner.

### Inputs:
add input "format_type" to Dataset object in NLP in case the user wants to predefine?
add span_aligner inputs to Dataset and remove from SingleDatasetPerformance 

### Logic:
* A user will be able to insert their data in both IOB and Bressler formats. Which format was used will be deduced and validated.
* When requiring IOB format, a check will call to a function in the Dataset, which holds a cached version of the data (calculates on the first call and then keeps the data). This is done for only a sample of the data.
The "span aligner" (to be renamed to a different name) will be part of the Dataset and receive its inputs in the dataset init.
* In the future, checks that do require the Bressler format will raise an error if the IOB format was given.


### Tasks:
* Find IOB dataset to use - 1 SP.
* Add option to receive and deduce IOB format, and validate - 2 SPs
* Move span aligner to cache in Dataset object (and remove from check SingleDatasetPerformance) - 2 SPs
* Add tests - 1 SP
* Update docstrings + format guide - 1 SP

### Comments: 
* When building the cache, notice the fact that sometimes different checks take different samples and this should be considered. See how it's done in other places.

**Comment by nirhutnik** [comment]
Changed task: Agreed to remove the span aligner and the support in other formats, for simplicity

**Comment by noamzbr** [comment]
Closed by #2205
