### ISSUE TITLE
[BUG] binary classification with labels which are not 0,1

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#2031]
**Describe the bug**
In this case the sklearn scorers will crush without appropriate massage to the user

**Expected behavior**
For it to work + explain how the pos label is selected in docs

Design how the solution should look like + implement.
Current problem - scorers are initialized without the data in a general manner so it will be hard to pass pos_label argument

**Comment by noamzbr** [comment]
Closed by #2050
