### ISSUE TITLE
[FEAT] Improve property calculation time

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#2055]
**Is your feature request related to a problem? Please describe.**
Calculating properties is way slower compared to what it should be. It also should be faster for a single image, not only on a vectorized batch.

**Describe the solution you'd like**
Check options like
1. use cv2
2. use cython
3. Utilize concurrent loading of images with pytorch dataloader

**Comment by TheSolY** [comment]
Implement the function calc_default_image properties to improve the runtime of the default properties.
Improvements to try:

- [ ] Shared calculations between properties for example rgb intensity 
- [ ] Sample the pixels to reduce the calculations on large images, take rgb vs grayscale into consideration - 1SP
- [ ] Tensorize list comprehensions by resize and stack - 1SP
- [ ] lru_cache
- [ ] tests

* Tried functools lru cache and it can't serialize a list, need to try again after tensorizing
