### ISSUE TITLE
[FEAT] Make class mechanism in NLP match the one in tabular & vision

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#2056]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/deepchecks/deepchecks/pull/2050, scorers receive the list of classes in the task from the context. 
- In tabular, the context aggregates the class from: the .classes_ in the model, the labels in the data, the predicted labels OR the user supplied list of classes (passed to the Dataset constructor).
- In vision, the context gets the classes from proba shape (always 0..n-1)

So now the NLP branch is out of sync with this change and must pass it's own classes to the DeepcheckScorer constructed in nlp scorers.py. Need to implement a mechanism in the context to get the list of all classes in the task, similarly to what is done in tabular and vision.

**Describe the solution you'd like**
On the face of it it should be implemented like it is in tabular - look at all present classes in labels and prediction, OR just receive classes from the user through TextData constructor. The complication is that in NLP we also implemented multilabel, whose label format (binary matrices) requires the possibility of passing a "label dict" like the one we have in vision, giving names to the classes from 0 to n-1. This is the current use of the `classes` argument of the TextData constructor. 

So we have a complicated situation here - in the case of regular classification / token classification, labels are like in tabular (the label you see in the data is the label name), but for multilabel tasks you must find a way to let deepchecks know what are the class names.

**goal**
Suggest a solution to that will catch all these cases and enable us to pass a list of classes to the constructor of DeepcheckScorer . Refactor the TextData `classes` argument and NLP context to implement suggestion.

**Comment by nirhutnik** [comment]
1. Match structure to tabular - 2 SP
2. Design solution for multilabel and approve with Gabbay + Sol/Nadav - 1 SP
3. Implement - approx. 3 SP

**Comment by nirhutnik** [comment]
Design changed a bit - now "classes" is an input received in the "run" function, and this supports multilabel by default.

**Comment by noamzbr** [comment]
Closed by #2146
