### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by naiborhujosua** [deepchecks/deepchecks#2083]
**Install package failed**
```python 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_17/3131868189.py in <module>
      5 from sklearn.ensemble import RandomForestRegressor
      6 from sklearn import datasets
----> 7 from deepchecks.suites import single_dataset_integrity, train_test_validation, model_evaluation
      8 from deepchecks.checks import TrustScoreComparison
      9 import scipy.stats as stats

ImportError: cannot import name 'single_dataset_integrity' from 'deepchecks.suites' (/opt/conda/lib/python3.7/site-packages/deepchecks/suites.py)

```

**To Reproduce**
1. Install deepchecks by  !pip install --upgrade  deepchecks
2 . ImportError: cannot import name 'single_dataset_integrity' from 'deepchecks.suites' (/opt/conda/lib/python3.7/site-packages/deepchecks/suites.py)

**Expected behavior**
the package must be installed but an error occurred

**Environment (please complete the following information):**
 - I use Kaggle kernel

**Comment by Nadav-Barak** [comment]
Hi @naiborhujosua, since the release of our [https://docs.deepchecks.com/dev/user-guide/vision/auto_quickstarts/plot_simple_classification_tutorial.html](vision package) the tabular functionalities can be found under deepchecks.tabular.XXX
