### ISSUE TITLE
[TABULAR] Design a way to infer the correct predicted class from probas

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#2090]
**Is your feature request related to a problem? Please describe.**
Currently in the tabular package predictions must be given / implemented, while predict_proba is optional. Theoretically (and done in practice in Vision) it's possible to get the predicted class from .argmax() on the proba. In tabular though, it's more complicated because classes don't have to be [0, .., n-1].

**Describe the solution you'd like**
Two possible solutions:
1. Leave as is, tabular users must give predictions
2. Use the context.classes to get the classes that correspond to the proba columns. Downside is that it practically assumes that all classes are in the label.

**Comment by noamzbr** [comment]
following up on our discussion, probably the solution here is to require the user to provide `classes` in cases when proba are supplied without a model or predictions.

**Comment by Nadav-Barak** [comment]
use cases are as follow:
If probas are provided one of the two must be: 
user have provided model classes
same number of unique labels in label col as in proba vector length

relevant validation will be placed
