### ISSUE TITLE
[BUG] Suite html results don't display plotly graphs properly for certain enviroments

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#2105]
**Describe the bug**
The suite results are lacking graphs for and are rendered weirdly for certain envs

**To Reproduce**
Suite results that contains graphs

**Expected behavior**
result displayed as it was if viewed as native HTML

**Screenshots**
![image](https://user-images.githubusercontent.com/17730502/197505432-17dd1edd-2232-4b3a-bf9e-350b5e2743c7.png)
![image](https://user-images.githubusercontent.com/17730502/197505451-809b02d8-4ecd-4b0c-8125-18e565cefb61.png)

**Environment**
[pip-requirments.txt](https://github.com/deepchecks/deepchecks/files/9851341/pip-requirments.txt)
[conda-requirements.txt](https://github.com/deepchecks/deepchecks/files/9851342/conda-requirements.txt)

**Additional context**
Bug reported by @Yarden234, who also asked for this fix to be applied also to 0.8.x

**Comment by yromanyshyn** [comment]
@noamzbr 

what env (collab, jupyter-notebook, kaggle) is used on screenshots?

provided requirements files do not contain `jupyter-server` nor `jupyterlab-server` so it is not classical jupyter or jupyter lab but I see `databricks-cli` package, so is that `databricks`?

**Comment by Yarden234** [comment]
@yromanyshyn The screenshot is simply from the downloaded HTML file of the suite.
And producing this results came from using VS-Code.
I can provide the code if it helps.

**Comment by yromanyshyn** [comment]
@Yarden234 

> I can provide the code if it helps.

if that is possible, yes, please

**Comment by Yarden234** [comment]
@yromanyshyn 
Hey I see now that any code produce that results (just a random x and y and random split), so my specific code doesn't really matter

**Comment by yromanyshyn** [comment]
@Yarden234 

> @yromanyshyn Hey I see now that any code produce that results (just a random x and y and random split), so my specific code doesn't really matter

sorry I did not notice initially that you use `deepchecks===0.8.0`
currently I cannot understand why this happens with this particular version
but this bug is not present in the latest `deepchecks` version, 
please try to update, it should help
