### ISSUE TITLE
Tokenization design - NLP

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#2116]
### DoD:
An agreed design

### Background:
Currently, our TextData object receives only plain text. For IOB format, we need to know the original tokenization.

### Tasks:
Write alternatives. Research Huggingface Dataset / Tokenizer. - 1 SP
Discuss and decide on a solution - 1 SP

### Comments:
Options: each sample is a list of tokens? Receiving a delimeter? Receiving a Tokenizer object?

**Comment by noamzbr** [comment]
Can look at https://huggingface.co/datasets/conll2003 for e.g. of a token classification dataset in HuggingFace

**Comment by nirhutnik** [comment]
Merged into another issue
