### ISSUE TITLE
[BUG] RocReport plots roc curve of negative class in binary classification

### ISSUE THREAD

**Issue by arvkevi** [deepchecks/deepchecks#2151]
**Describe the bug**
For binary classification, the `RocReport` class can plot the roc curve of the negative class. I'm a new user, so I could be misinterpreting something.

**To Reproduce**
```python
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import auc, roc_curve, RocCurveDisplay

from deepchecks.tabular import Dataset
from deepchecks.checks import RocReport

X, y = make_classification(n_samples=500, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

result1 = RocReport().run(dataset=Dataset(X_test, y_test), model=model).show(show_additional_outputs=True)
result2 = RocReport(excluded_classes=[1]).run(dataset=Dataset(X_test, y_test), model=model).show(show_additional_outputs=True)
result3 = RocReport(excluded_classes=[0]).run(dataset=Dataset(X_test, y_test), model=model).show(show_additional_outputs=True)
```

`result1` and `result2` generate the same image, where it appears to be the roc curve of the negative class. 
![result1](https://user-images.githubusercontent.com/9151717/202612593-31018c71-cba7-4b4c-a491-a38be440f6bc.png)

`result3` looks as I would expect:
![result3](https://user-images.githubusercontent.com/9151717/202613171-bef0b8c5-a683-425d-ac5b-5fe7519dfbbb.png)

**Expected behavior**
I expected the default roc curve to look similar to the default roc curve from scikit-learn:

```python
RocCurveDisplay.from_predictions(y_test, model.predict_proba(X_test)[:, 1], pos_label=1)
```
![sklearn_pos1](https://user-images.githubusercontent.com/9151717/202613097-8539f52e-e2f5-46ca-814a-e243d3750893.png)

But, instead, the default output from `RocReport` looks like the scikit-learn roc curve of the negative class:

```python
RocCurveDisplay.from_predictions(y_test, model.predict_proba(X_test)[:, 0], pos_label=0)
```
![sklearn_pos0](https://user-images.githubusercontent.com/9151717/202613455-1d9f0f54-e664-4120-9510-631f59d88a60.png)

**Environment (please complete the following information):**
 - OS: MacOS
 - Python Version: 3.9
 - Deepchecks Version: 0.8.3

**Comment by Nadav-Barak** [comment]
Hi @arvkevi, Thanks for reporting the bug! It was fixed and will be available in the upcoming release :)

**Comment by arvkevi** [comment]
Thank you, @Nadav-Barak!
