### ISSUE TITLE
[FEAT] Tabular fairness suite

### ISSUE THREAD

**Issue by OlivierBinette** [deepchecks/deepchecks#2208]
## **Describe the solution you'd like**

(As discussed briefly with @noamzbr.)

A suite of checks for assessing the fairness of classification and regression models. Proposed fairness checks:

- **Performance Disparity:** Check that there are no major performance disparities across a set of pre-defined subgroups (e.g., across sex and race). For certain choices of performance measures, this is equivalent to the *equalized odds* fairness metric in classification. 
- **Demographic Parity:** Check that there are no major differences in the response distribution across subgroups.
- **Representativity:** Check that pre-defined subgroups are sufficiently well represented in the data (i.e., make sure that no subgroup of interest is underrepresented in the data).

These checks should implement functionality comparable to what is other toolkits such as [Microsoft's Responsible AI Fairness Dashboard](https://github.com/microsoft/responsible-ai-toolbox/blob/main/docs/fairness-dashboard-README.md). It can also go much beyond that by:
1. Evaluating fairness at the intersection of multiple subgroups and allowing for control variables.
2. Providing high-quality visualizations for evaluating fairness across many subgroups and control variables.
3. Implementing a broad set of fairness metrics.
4. Accounting for sampling uncertainty when comparing performance metrics across subgroups.

I think (4) is out of score of deepchecks, but (1)-(3) are achievable.

## **Describe alternatives you've considered**

The **SegmentPerformance** check looks at performance within subgroups. However, it is now deprecated and it is limited  to looking at only two subgroups. Furthermore, it does not provide default conditions that are suited to fairness evaluation. Same problem with **WeakSegmentsPerformance** which isn't well-suited for fairness analysis.

### What could this look like?

```python
class PerformanceDisparityReport(SingleDatasetCheck):

    # List of protected attributes (e.g., sex and age)
    target_features: List[Hashable]

    # Optionally, a single variable to use as a control (e.g., education level)
    control_feature: Hashable = None

    # Scoring funtions
    scorers: Union[Mapping[str, Union[str, Callable]], List[str]] = None
    
    # For classification, whether to report scores as class averages.
    class_avg: bool = True

    # Each feature (in target_features and control_feature) is to be discretized in at most `max_segments` groups.
    max_segments: int = 10

    # Smallest group size on which a performance metric is going to be computed
    min_group_size: int = 5

    # Visual attributes to use for sensitive variables. Defaults to ["x", "color", "facet_col"]
    facets: List[str] = None

    # Visual attribute to use for performance dis-aggregated by class. Defaults to "facet_col".
    class_facet: str = "facet_col"
```

### How can we visualize performance at the intersection of many subgroups?

I would recommend using a **strip plot** to visualize scores across subgroups. An histogram of subgroup size can be overlayed to provide context.

For example, using the adult dataset and "sex", "race" and "age" as sensitive features, we can visualize performance by class and subgroup. Only the first two subgroups (sex and race) will be assigned distinct visual elements (on the x-axis and color), but there will be one point for each corresponding age group as well.

```python
from deepchecks.tabular.checks.model_evaluation.performance_disparity_report import PerformanceDisparityReport
from deepchecks.tabular.datasets.classification import adult

check = PerformanceDisparityReport(target_features=["sex", "race", "age"], max_segments=3, scorers=["f1_per_class"])

dataset = adult.load_data()[0]
model = adult.load_fitted_model()
check.run(dataset=dataset, model=model)
```

![screenshot](https://user-images.githubusercontent.com/784901/208325018-423e8811-c004-48c8-ae6f-5b9cc0d9e4c4.png)

### What conditions could be added?

We can threshold the difference between min and max performance across subgroups, or the ratio between min and max performance across subgroups. We can also put a lower boundary on performance for all subgroups.

### Why only allow for a single control feature?

Multivariate control variables can be reduced to a univariate variable by regressing on the outcome. I think this is sufficient for fairness analyses and it keeps things simple enough.

### What else could be considered?

What I've proposed so far are *group* fairness checks (see https://en.wikipedia.org/wiki/Fairness_(machine_learning)). Individual or counterfactual fairness checks could also be considered. Additionally, more general definitions of group fairness based on independence and conditional independence between variables could be assessed using statistics such as a $\chi^2$ divergence, KL-divergence, or conditional entropy. It's less easily interpretable than what I proposed, but it's more principled and it's amenable to formal statistical tests.

**Comment by OlivierBinette** [comment]
Following discussion with noamzbr, I will focus for now on:

1. A simplified proposal for the PerformanceDisparityReport.
2. Exploration of visualization options which are scientifically accurate, visually attractive, and easy to understand.

**Comment by OlivierBinette** [comment]
As an alternative to the strip plot (which shows the performance for all subgroups), we can make a visualization which focuses on subgroups with the largest score difference.

**Advantages:**
- More easily interpretable and immediately highlights performance disparities.

**Disadvantages:**
- Requires choosing the kind of difference to look at (absolute or relative), and the baseline to use (difference to average score, difference to maximum observed score, or difference to perfect score).

![screenshot](https://user-images.githubusercontent.com/784901/208515981-269a7453-41fb-4dce-85a9-7bfbc75bc073.png)

**Comment by OlivierBinette** [comment]
Current progress is at https://github.com/OlivierBinette/deepchecks/blob/fairness/deepchecks/tabular/checks/model_evaluation/performance_disparity_report.py. Continuing tomorrow.

**Comment by noamzbr** [comment]
Good progress! 

Regarding the plot - I like it, my current concern is that at a first glance it wasn't clear to me that "the largest bar is the worst". My intuition was that as we're measuring performance, "greater is better". I had to look at the axis name and the fact that the numbers are negative to understand. Another concern is that this plot only shows the difference, but I have no way to asses how bad this difference it is - how large compared to the average value.

Regarding the options - in what cases would I want to compare to the maximum / perfect score?

Lastly, something I've noted in the code - if there is not equivalent to is_classwise in scorers.py, maybe it should be there.

**Comment by OlivierBinette** [comment]
@noamzbr Thanks for the comments! I'll work on tweaks to the visualization to address them. Right now, we can see how bad the difference is by hovering over a bin. The scores for the subgroup and for the average are displayed in a "details" section. I'll see if I can incorporate that information in the plot visually.

For the other points:
- We might want to compare to maximum/perfect score when we care about identifying subgroups with the worst performance. An alternative here would be to plot the scores directly, but in that case a bar plot is not the most appropriate and we'd have to change the display.
- `is_classwise` is currently not very robust due to a bug flagged in #2214. Once it works well enough I'll move it to scorers.py

**Comment by noamzbr** [comment]
about the first point - won't the largest difference from average group would also be the worst performing group?

**Comment by OlivierBinette** [comment]
@noamzbr The average is computed for each control_feature level group (e.g., each education group). But the perfect/max score would be absolute across all control_feature level groups. But in some cases "best possible score" is not defined or is infinity, so not sure what to do there.

**Comment by OlivierBinette** [comment]
An alternative to the bar plot would be plot average scores and subgroup score side by side. Below, we have the average score in blue and the subgroup score in in red. I still need to add labels, legends, etc.

**Advantages:**
- More fine-grained visualization

**Disadvantages:**
- Higher visual complexity.
- Can't quite manage to make the plot look as good as I would like (it'd be nice to have pointed bars instead of the pairs of points joined by a line).

![screenshot](https://user-images.githubusercontent.com/784901/208701404-6a197679-1d5e-4e28-a51d-50babe3803fc.png)

**Comment by OlivierBinette** [comment]
Incremental improvement which helps distinguish between positive and negative performance differences. I think this is starting to look much better.

![screenshot](https://user-images.githubusercontent.com/784901/208708903-8ccea60b-834e-4c76-b2c3-d5f96b86f13c.png)

**Comment by noamzbr** [comment]
This looks better indeed, but I still have something that confuses me - what is the "original point" for each of the categories - is it the average performance for that bin of the control variable?

Also, need to think of a way to clarify the role of the two elements in the names of the ticks in the y axis. We know the first is the target and the second is the control variable, but would be good to make it clearer somehow.

**Comment by OlivierBinette** [comment]
Yes the "original point" is the average performance for that bin of the control variable. I agree that this all needs to be clarified. I'll see what I can do.

**Comment by noamzbr** [comment]
is there a way to hierarchically display it so that all the female/male are showing together? Easy way would be to sort the y axis ticks first by the target, a more complex solution (if possible) will include some visual separation in the graph between the areas belonging to each target variable value

**Comment by OlivierBinette** [comment]
I think it would be best to preserve the sort by magnitude of the performance difference. But on top of that, I agree we could group by education using facet_col or color. It would make the plot quite a bit bigger (we'd have one subplot for each education level, and then we'd plot the top K performance differences within each), but it might be easier to understand.

Otherwise I'm continuing to see if I can make the plot more interpretable using labels and such:

![screenshot](https://user-images.githubusercontent.com/784901/208732503-9df2351a-00ef-4e06-a324-e056b533f90c.png)

**Comment by OlivierBinette** [comment]
Other example:

![screenshot](https://user-images.githubusercontent.com/784901/208735667-f5f809e4-914c-41ff-8c9a-8568c61c24be.png)

**Comment by OlivierBinette** [comment]
There's the option of hiding the y ticks label, since they are repeated as data point labels:

![screenshot](https://user-images.githubusercontent.com/784901/208765490-956a7280-1e7b-4220-ad97-7b561a6c961d.png)

**Comment by OlivierBinette** [comment]
Example without a control feature:

![screenshot](https://user-images.githubusercontent.com/784901/208767281-d7c72e22-f6c6-4f77-97e5-b76edeff98e4.png)

**Comment by OlivierBinette** [comment]
What it looks like with grouping by education (note: the labeling and spacing gets tricky to manage):

![screenshot](https://user-images.githubusercontent.com/784901/208775848-3af6e0bc-1ead-48d9-a28a-69e87ea7e3fc.png)

**Comment by OlivierBinette** [comment]
We can also do a grid, but this won't scale to a large number of protected subgroups.

![screenshot](https://user-images.githubusercontent.com/784901/208779878-a6cba200-0e80-4dc9-b4ab-7519b1fcc4ac.png)

**Comment by OlivierBinette** [comment]
I think the grid or grouped visualizations look better, but this visualization quoted below is more scalable and more focused on the goal of the check. I'll move forward with it for now.

> There's the option of hiding the y ticks label, since they are repeated as data point labels:
> 
> ![screenshot](https://user-images.githubusercontent.com/784901/208765490-956a7280-1e7b-4220-ad97-7b561a6c961d.png)

**Comment by OlivierBinette** [comment]
We could also display the information in a table. This isn't styled nicely but it gives a rough idea of what could be done.
![screenshot](https://user-images.githubusercontent.com/784901/208787448-96e4aeb6-51b3-49da-b75c-d479e69932c1.png)

**Comment by Nadav-Barak** [comment]
Hey @OlivierBinette great to have you onboard! this type of display looks really good IMO and also the idea in general. 
2 suggestions / questions:
Would add a mechanism which filter and displays only the top X education groups bins (if doesn't already exist).

In general in the check you define both the subgroup feature and controlling feature? can imagine a case where you do only receive a subgroup feature and search across all other features as candidates for control feature.
If you are going in that direction you can use a tab widget as in [here](https://docs.deepchecks.com/dev/checks_gallery/tabular/model_evaluation/plot_weak_segments_performance.html) for display.
> Below, I binned education into only three groups and show all performance differences. Note that spacing and labeling of the subplots gets tricky to manage.
> 
> ![screenshot](https://user-images.githubusercontent.com/784901/208776715-a3ea11fa-a18f-4c2b-b047-1e6c5d786903.png)

**Comment by noamzbr** [comment]
Hi, so first IMO the vertically split graph (that Nadav copied above) looks by far the best, and is easiest to read. I think that if we manage to make it scale (e.g. given an assumption that we have max_cat in the 5-10 range) it the best option.

@Nadav-Barak I didn't fully understand what you you mean by top X education groups? You mean that we need to show the N bins in which there is the largest difference? If so, I support (I think that's what is done here).
Also @Nadav-Barak , control feature is a user defined thing that has meaning, you can't search for it. For e.g. in this case Education is selected because it is allowed for education to "cause" different outcomes, but for individuals with the same education level race is not allowed to affect the outcome.

**Comment by noamzbr** [comment]
Also small note - let's print the name of the score in the x axis

**Comment by OlivierBinette** [comment]
Sounds good! Thanks for the comments :)

I'll make a plot with:
1.  A vertical grid of the top N (around 1-5) control groups where largest performance differences are seen. 
2. When there are model classes and scores per class, there will be one subplot for each combination of model class + subgroup where largest differences are observed.
3. Within each subplot, we'll see the top M around (1-5) subgroups where largest differences are seen.

I'll also work on improving the documentation and adding a "how to read this plot" tooltip or caption.

**Comment by noamzbr** [comment]
1. Sounds good
2. Would encourage the user to not pass multiclass metrics, as display & check will be easier for aggregate metrics / metrics on a single class.

Just making sure - the full data (all classes, control variable groups and target groups) will be available in the check result object? There perhaps it can be a pandas DataFrame

**Comment by OlivierBinette** [comment]
@noamzbr Yes the full data (including everything needed to reproduce the plots, modulo transformations) will be in the check result. 

Currently it's a pandas dataframe with columns for the model classes, protected feature, control feature, "_scorer", "_score", "_baseline" and "_count". Each row gives the score and baseline score for a given combination of model class, protected feature, and control feature.

![screenshot](https://user-images.githubusercontent.com/784901/208935552-4593d970-6ca0-41fc-b327-7cdcea6c3d5a.png)

**Comment by Nadav-Barak** [comment]
ohh ok I get it,  
Alternative suggestion (weaker and can be implement in the future) - the check (and the fairness suite also) will accept a list of protected features and a list of 'cause' features and do the same sort of grid search I suggested above

> @Nadav-Barak I didn't fully understand what you you mean by top X education groups? You mean that we need to show the N bins in which there is the largest difference? If so, I support (I think that's what is done here). Also @Nadav-Barak , control feature is a user defined thing that has meaning, you can't search for it. For e.g. in this case Education is selected because it is allowed for education to "cause" different outcomes, but for individuals with the same education level race is not allowed to affect the outcome.

**Comment by noamzbr** [comment]
@Nadav-Barak regarding multiple control variable we probably better use the method described briefly by @OlivierBinette in the opening comment (under "Multivariate control variables"). @OlivierBinette perhaps care to elaborate a bit, or open a future issue explaining how that may be done?

Regarding multiple targets / protected features - if the user has defined several protected features, I guess they mean for all of them to "pass" the check, so I think it makes sense to create one instance of the check per protected feature.

**Comment by OlivierBinette** [comment]
@Nadav-Barak, @noamzbr 

To expand to lists of protected and control features, I think we could do this:
- Based on the list of protected features, define a new feature which corresponds to the intersection of all the groups. Do the same for the control feature. Then apply the same methodology as above for a single protected feature and a single control feature.

This would be very convenient as a way to look at the intersection of say race and gender. But it's also an easy thing for a user to do prior to passing the data to the check.

More clever ways to reduce control features would better be done by the user or as part of the statistical approach to fairness analysis (based on looking at conditional dependencies). I'll leave that for future issues/features.
