### ISSUE TITLE
[FEAT] vision api refactor step 2

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#2218]
Goal of this step is to complete the core code.
Specifically, at this step we will implement support in pytorch stream dataloader, tensorflow datasets + tests for both
Major issue - a lot of our metrics are based on ignite which is based on torch
At the end will run profiler to see if we can get 'easy wins' in run time

Not included in this issue: docs, head functionality, properties refactor, monitoring

**Comment by noamzbr** [comment]
Also making sure everything runs both on cpu and gpu

**Comment by Nadav-Barak** [comment]
https://github.com/deepchecks/deepchecks/pull/2244
