### ISSUE TITLE
[BUG] Fix Typo in docs/source/getting-started/installation.rst

### ISSUE THREAD

**Issue by chaeheum3** [deepchecks/deepchecks#2232]
**Describe the bug**
In [docs/source/getting-started/installation.rst](https://github.com/deepchecks/deepchecks/blob/cdfcfc5fbc23d7daf99a74505c0cfd17fc320a17/docs/source/getting-started/installation.rst) fix typo located at line 73

Before
```
Istallation of deepchecks for CV should be stated explicitly and it includes
```

After
```
Installation of deepchecks for CV should be stated explicitly and it includes
```

**Comment by noamzbr** [comment]
Thanks @chaeheum3! Will be fixed in #2239
