### ISSUE TITLE
Widgets don't work in jupyter lab

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#2344]
There's an issue with plotly > 5.5.0 that causes our widgets to not show in jupyter lab under "model not found".

![image](https://user-images.githubusercontent.com/92314933/220109091-8a328281-39eb-4f2d-8f39-d44e5ba16d64.png)

**Comment by noamzbr** [comment]
Closed by https://github.com/deepchecks/deepchecks/pull/2360
