### ISSUE TITLE
drift - normalize l2_weighted

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#2351]
Currently, l2_weighted method (in TrainTestFeatureDrift) is unbounded, and can get large results based on a large number of features.
We need to find some way to normalize it, ideally by finding a way that will scale it between 0 and 1.

possible solutions:
* Limit number of features, by hardcoded number or by >0.01 feature importance
* add some regularization based on number of features (/log(N))
* Probably there are also better ones

**Comment by noamzbr** [comment]
Closed by #1898
