### ISSUE TITLE
[FEAT] condition for Confusion Matrix Report

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#2443]
Add a condition to verify that all cells in the output confusion matrix with more then x percent of the data have a score of at least (1-y)*avg_score.

Similar to add_condition_segments_relative_performance_greater_than in weak_segment_abstract.py

Should be implemented in confusion_matrix_abstract.py and tested in tabular, nlp sub packages

**Comment by kishore-s-15** [comment]
Hi @Nadav-Barak, I would love to take up this.

**Comment by dsjoench** [comment]
@Nadav-Barak, I'd love to take this if kishore-s-15 pass on.

**Comment by Nadav-Barak** [comment]
Hi @kishore-s-15 , I have assigned this issue to you :)

I know you are already familiar with the CI but feel free to reachout if you are having troubles.
Make sure to also add relevant tests and to update the plot_confusion_matrix_report.py files with the a relevant new section about the condition (reference in plot_single_dataset_performance.py - Define a condition).

**Comment by kishore-s-15** [comment]
Thanks for assigning this issue to me @Nadav-Barak.
