### ISSUE TITLE
[FEAT] Additional properties NLP

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#2452]
Add additional properties for the NLP sub package.

We have a lot of checks in the NLP sub package that rely on high quality text properties.
Currently we have some which can be seen at text_properties.py.

We need to add more, can be based on simple internal python methods like text length or complex that uses external models such as formality.

When suggesting a new property - include what is the run time for the property and what are the dependencies it has

**Comment by hjain5164** [comment]
@Nadav-Barak I would like to work on this task. Can I go ahead and can you guide me about this task as well?

**Comment by Nadav-Barak** [comment]
For sure, assigning it to you :)

As a first steps:
1. Review the contribution guidelines - https://github.com/deepchecks/deepchecks/blob/main/CONTRIBUTING.rst
2. Run and verify all test pass on your local fork
3. Review the current available nlp properties - see text_properties.py file in the deepchecks repo
4. Run the following from a notebook and verify in works on a dataset of your choice - calculate_default_properties(data, include_long_calculation_properties = True)

As second step:
Let disscuss ideas for possible properties - either come up with suggestion or we can brain storm together (https://join.slack.com/t/deepcheckscommunity/shared_invite/zt-y28sjt1v-PBT50S3uoyWui_Deg5L_jg)

**Comment by kishore-s-15** [comment]
Hi @Nadav-Barak, If I could also work concurrently with @hjain5164 on this task, I would love to contribute to this feature.

**Comment by hjain5164** [comment]
@Nadav-Barak I am unassigning myself for now. @kishore-s-15 You can go ahead and work on this task.

**Comment by Nadav-Barak** [comment]
Hey, Since we need as many cool properties as we can get and we have many ideas I have opened an additional issue and assigned it to @kishore-s-15.
@hjain5164 Currently i keep this issue assigned to you since you already did the heavy lifting of coming up with cool ideas. Let me know if you will be unable to finish it in the near future
