### ISSUE TITLE
[FEAT] Additional NLP properties (2)

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#2454]
Add additional properties for the NLP sub package.

We have a lot of checks in the NLP sub package that rely on high quality text properties.
Currently we have some which can be seen at text_properties.py.

We need to add more, can be based on simple internal python methods like text length or complex that uses external models such as formality.

When suggesting a new property - include what is the run time for the property and what are the dependencies it has

**Comment by Nadav-Barak** [comment]
First steps for contributing to this issue:
1. Review the contribution guidelines - https://github.com/deepchecks/deepchecks/blob/main/CONTRIBUTING.rst
2. Run and verify all test pass on your local fork
3. Review the current available nlp properties - see text_properties.py file in the deepchecks repo
4. Run the following from a notebook and verify in works on a dataset of your choice - calculate_default_properties(data, include_long_calculation_properties = True)

As a second step:
Let discuss ideas for possible properties - either come up with suggestions or we can brain storm together (https://join.slack.com/t/deepcheckscommunity/shared_invite/zt-y28sjt1v-PBT50S3uoyWui_Deg5L_jg)

**Comment by noamzbr** [comment]
Would be very interesting IMO to add text complexity related properties, such as some of the ones in https://github.com/textstat/textstat

**Comment by noamzbr** [comment]
Other ideas - n duplicates within sample (word or more than word), is_question

**Comment by kishore-s-15** [comment]
Hi @Nadav-Barak & @noamzbr, I would like to work on this task.

**Comment by hjain5164** [comment]
Hi @kishore-s-15 are you working on this task? Can you let me know the properties which you are adding since I am also going to add more text properties and don't want to make duplicates?

**Comment by kishore-s-15** [comment]
Hi @hjain5164, I've not started working on this issue yet but am very much interested in contributing. I've messaged you on Slack, we can converse in that forum if it's fine with you.

**Comment by noamzbr** [comment]
Other ideas I can suggest for you two - identifying special formats within the text, such as datetime, urls etc.

**Comment by hjain5164** [comment]
As discussed with @Nadav-Barak, proceeding with ARI and average sentence length for now. Will discuss on other properties later on.
