### ISSUE TITLE
Better handle download of nltk dependencies 

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#2487]
**Is your feature request related to a problem? Please describe.**
Currently in nltk downloads (punkt and stopwords) are handled inconsistently:
1. In properties, if you didn't run the download command you'll get an error and need to run download yourself, which is very problematic
2. In the duplicate detection checks, they are downloaded on file import

**Describe the solution you'd like**
1. nltk download will be quite
2. nltk stuff will automatically be downloaded when needed
3. In cases when nltk stuff can be replaced by alternative methods (such as .split()) this should be done when download is not possible, see what was done in the Unknown Tokens check.

**Comment by hjain5164** [comment]
Hi @noamzbr, since I already worked on the text properties, can I work on this and make all the property functions have separate nltk downloads?

**Comment by noamzbr** [comment]
Hi @hjain5164, sorry this was already closed by https://github.com/deepchecks/deepchecks/pull/2493
