### ISSUE TITLE
[BUG] display bug UnknownTokens

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#2529]
**Describe the bug**
Display looks weird when:
1. there are no unknown tokens
2. their percentage are very small
3. their percentage are very very small (rounded to 0 as in second image)

**To Reproduce**
run the check on just_dance_comment_analysis

from deepchecks.nlp.checks import UnknownTokens
from deepchecks.nlp.datasets.classification import just_dance_comment_analysis

train, _ = just_dance_comment_analysis.load_data(use_full_size=True)
UnknownTokens().run(train)
![image](https://github.com/deepchecks/deepchecks/assets/67195469/708914b6-941b-4c44-96d3-af5475d380d2)

from deepchecks.nlp.checks import UnknownTokens
from deepchecks.nlp.datasets.classification import just_dance_comment_analysis

train, _ = just_dance_comment_analysis.load_data(use_full_size=False)
UnknownTokens().run(train)![image](https://github.com/deepchecks/deepchecks/assets/67195469/0d8fa679-6d9e-4d3b-bbef-bbd348aa917c)

**Comment by noamzbr** [comment]
Fixed
