### ISSUE TITLE
Add description for builtin properties

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#2552]
Some properties are not that straight-forward, such as "lexical density", or users may not know exactly how they're calculated, like "Language".

I think we need to find a way to add descriptions to builtin properties, and add that description in some way to the output graphs.

Possible solutions:

Add HTML code for "(i)" / hover information info on each property (shown in picture) - probably complicated code-wise, and requires refactor of properties to add the description, but most elegant

Add a URL under each graph that points to the NLP Properties Guide part on built-in properties. Bonus: Do it only for builtin properties - Easier, but less elegant, still requires to differentiate between builtin and non-builtin properties.

![image](https://github.com/deepchecks/deepchecks/assets/92314933/4cbe38d7-8404-4818-a1fe-84b3fe542409)

**Comment by noamzbr** [comment]
@hjain5164 will you want to take that?

**Comment by hjain5164** [comment]
@noamzbr you can assign it to me.

**Comment by hjain5164** [comment]
@noamzbr / @nirhutnik  We can add annotations maybe here but I am actually confused on how can we position the annotation close the title since each title would be different and there is no option to have annotations placed in relative position of title. Any idea/suggestions here?

**Comment by hjain5164** [comment]
Yeah I initially tried that way, but it seems that the plot title considers only a string. Will check over inserting HTML somehow again and will update here.

**Comment by hjain5164** [comment]
So, after discussing, we came to the conclusion that we can show the (i) text after the plot tittle using its Unicode character and also display a one-liner small description after the plot title. This will only work for text property plots.
