### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by pr3sh** [deepchecks/deepchecks#2631]
Is there a docker image that can be used to build / containerize the monitoring UI from source? Would like to deploy this on a Kubernetes environment if possible

**Comment by noamzbr** [comment]
Hi @pr3sh, did you look at the install guide for the monitoring product https://docs.deepchecks.com/monitoring/stable/getting-started/deploy_self_host_open_source.html? If you still have a problem, you can open an issue in https://github.com/deepchecks/monitoring or send a question in the community slack https://join.slack.com/t/deepcheckscommunity/shared_invite/zt-1zn0p33s5-H5MsO3GScnHm_nZsN6iQQw
