### ISSUE TITLE
[FEAT] Fixing Inconsistent Legend Colors for Train and Test Datasets in Train-Test-evaluation Charts 

### ISSUE THREAD

**Issue by Fruit-loops** [deepchecks/deepchecks#2633]
## Overview
Firstly, I would like to express my gratitude for developing this incredibly useful tool. While using it, I noticed an inconsistency in the legend colors for the Train and Test datasets in Train-Test-evaluation related charts. This can be confusing when observing the charts. I would like to propose the idea of fixing the legend colors for the Train and Test datasets to improve the readability and consistency of the charts.

## Issue Description
Currently, some charts represent the Train dataset in blue, while others use blue to represent the Test dataset. This inconsistency can lead to confusion for users, especially when dealing with multiple datasets. Fixing the legend colors for the Train and Test datasets would help reduce confusion and make it easier for users to understand and interpret the data in the charts.

## Suggestions
I suggest considering one of the following solutions:

1. Fix the legend color for the Train dataset as blue and assign a different color (e.g., green) for the Test dataset.
2. Allow users to customize the legend colors for the Train and Test datasets according to their preferences.
Expected Impact
By fixing the legend colors for the Train and Test datasets, we can improve the readability and consistency of the charts, making it easier for users to understand the data. This will help reduce confusion and enhance user efficiency.

Thank you for your time and consideration. I believe that by fixing the legend colors for the Train and Test datasets, this tool will become more user-friendly and intuitive.

Best regards,

**Comment by noamzbr** [comment]
Hi @Fruit-loops thanks for raising our awareness to this! 
Is this something you'd be willing to contribute on? Especially your first point of syncing the way we represent train and test across our checks.

**Comment by noamzbr** [comment]
Hi @Fruit-loops, I think the same issue was raised by https://github.com/deepchecks/deepchecks/issues/2643, and the fix will be merged soon. 
Do you know of any other checks that have the same issue with reversed names?
