### ISSUE TITLE
[BUG] Incorrect Legends in FeatureDrift Check - DeepCheks v0.17.3

### ISSUE THREAD

**Issue by castilho25** [deepchecks/deepchecks#2643]
**Describe the bug**
The bug is related to the incorrect labeling of legends in the DeepCheks framework, specifically within the FeatureDrift check. As of version 0.17.3, the legends for the train and test datasets are swapped, causing confusion during the analysis of the results.

**To Reproduce**

1. Install DeepCheks version 0.17.3 using the command: pip install deepchecks==0.17.3.
2. Implement the DeepCheks Suite with the FeatureDrift and NewCategoryTrainTest checks.
3. Prepare your datasets for the evaluation.
4. Run the DeepCheks evaluation on your datasets using the implemented Suite.
5. Observe the output of the FeatureDrift check.

**Expected behavior**
In the FeatureDrift check, the legend for the train dataset should be correctly labeled as "Train," and the legend for the test dataset should be correctly labeled as "Test." The correct labeling will ensure a straightforward and accurate interpretation of the results, allowing users to identify any feature drift between the training and testing datasets.

**Actual behavior**
As of version 0.17.3, the FeatureDrift check mistakenly swaps the legends, resulting in the "Test" label being applied to the train dataset and the "Train" label being applied to the test dataset. This mislabeling creates confusion for users who expect the legends to represent the conventional meaning of training and testing datasets.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version: Python 3.6
 - Deepchecks Version: 0.17.3

**Comment by noamzbr** [comment]
Hi @castilho25, thanks for raising awareness for this issue! Will be fixed with https://github.com/deepchecks/deepchecks/pull/2644

**Comment by noamzbr** [comment]
closed by #2644
