### ISSUE TITLE
[FEAT] create a helm chart for Kubernetes deployment of Deepchecks Monitoring Open Source.

### ISSUE THREAD

**Issue by bgalvao** [deepchecks/deepchecks#2730]
**Is your feature request related to a problem? Please describe.**
 
There is no easy way of deploying Deepchecks monitoring easily to kubernetes.

**Describe the solution you'd like**

A helm chart so I can just install it with Helm.

**Describe alternatives you've considered**

With Kubernetes... There is hardly an alternative like Helm for this problem.

**Additional context**
`None`

**Comment by noamzbr** [comment]
Hi @bgalvao thanks for opening this. I think it's better though to open this issue in https://github.com/deepchecks/monitoring where it's most relevant.

**Comment by bgalvao** [comment]
ok, I was not aware. I'm moving it over.
