### ISSUE TITLE
[FEAT] Update dependencies

### ISSUE THREAD

**Issue by j-adamczyk** [deepchecks/deepchecks#2773]
**Is your feature request related to a problem? Please describe.**
There are a lot of outdated dependencies in DeepChecks, with locked maximal versions of libraries, which makes it impossible to use it with modern versions of other libraries.
Examples:
- `scikit-learn` (max 1.3)
- `transformers` (max 4.36.2)
- `ipywidgets` (max 7.8.2)

Those packages also transitively depend on other packages, and I have a total mess of dependencies.

**Describe the solution you'd like**
Update DeepChecks dependencies and allow newest (and future) versions of other libraries.

**Comment by JKL98ISR** [comment]
Hey, we released a new version 0.19.1 that upgrades those versions
