### ISSUE TITLE
[BUG] pip install "deepchecks[nlp-properties]" fails on Windows (because fasttext does not build)

### ISSUE THREAD

**Issue by bmerkle** [deepchecks/deepchecks#2786]
**Describe the bug**
I am following the installation guideline https://docs.deepchecks.com/stable/getting-started/installation.html
now installation of `pip install "deepchecks[nlp-properties]"` fails

During the installation the wheel is download downloading fasttext-0.9.3.tar.gz (which is not officially released AFAIK)
https://github.com/facebookresearch/fastText/releases
The latest release is 0.9.2 currently.

Building fasttext-0.9.3 fails on windows because of a compiler error msgs. 

I know that this is not the error of deepchecks but specifiying 
Collecting fasttext>=0.8.0 (from deepchecks[nlp-properties])
is maybe not the best idea. (as it always pulls the newest release then)

the workaround on windows with `pip install fasttext-wheel` did not work either

**To Reproduce**
1. [Go to '...'](https://docs.deepchecks.com/stable/getting-started/installation.html) 
2. pip install "deepchecks[nlp-properties]"
3. building fasttext fails'
4. See error below

**Expected behavior**
pip install "deepchecks[nlp-properties]" should work also on windows

**Screenshots**

**Environment (please complete the following information):**
 - OS:  Windows 10/11
 - Python Version:  3.11.9
 - Deepchecks Version: 0.18

**Additional context**
(venv) C:\work\llm-eval-frameworks\samples>pip install "deepchecks[nlp-properties]"
Looking in indexes: https://aritfactory.xxx.xxx/artifactory/api/pypi/pypi/simple
Requirement already satisfied: deepchecks[nlp-properties] in c:\work\llm-eval-frameworks\venv\lib\site-packages (0.18.1)
....
Requirement already satisfied: h11<0.15,>=0.13 in c:\work\llm-eval-frameworks\venv\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7.6.5->deepchecks[nlp-properties]) (0.14.0)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (pyproject.toml) ... error
  error: subprocess-exited-with-error
      python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(186): error C2065: "ssize_t": nichtdeklarierter Bezeichner
      python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(186): error C2065: "ssize_t": nichtdeklarierter Bezeichner
      python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(186): error C2672: "pybind11::init": keine \x81bereinstimmende \x81berladene Funktion gefunden
      C:\Users\merklbe1\AppData\Local\Temp\pip-build-env-o8qjymlk\overlay\Lib\site-packages\pybind11\include\pybind11\pybind11.h(1978): note: kann "Ret pybind11::init(CFunc &&,AFunc &&)" sein
      python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(186): note: "pybind11::init": Ung\x81ltiges Vorlage-Argument f\x81r "CFunc", Typ erwartet.
      C:\Users\merklbe1\AppData\Local\Temp\pip-build-env-o8qjymlk\overlay\Lib\site-packages\pybind11\include\pybind11\pybind11.h(1970): note: oder "Ret pybind11::init(Func &&)"
      python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(186): note: "pybind11::init": Ung\x81ltiges Vorlage-Argument f\x81r "Func", Typ erwartet.
      C:\Users\merklbe1\AppData\Local\Temp\pip-build-env-o8qjymlk\overlay\Lib\site-packages\pybind11\include\pybind11\pybind11.h(1958): note: oder "pybind11::detail::initimpl::constructor<Args...> pybind11::init(void)"
      python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(186): note: "pybind11::init": Ung\x81ltiges Vorlage-Argument f\x81r "Args", Typ erwartet.
      python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(186): error C2672: "pybind11::class_<fasttext::DenseMatrix>::def": keine \x81bereinstimmende \x81berladene Funktion gefunden
      C:\Users\merklbe1\AppData\Local\Temp\pip-build-env-o8qjymlk\overlay\Lib\site-packages\pybind11\include\pybind11\pybind11.h(1677): note: kann "pybind11::class_<fasttext::DenseMatrix> &pybind11::class_<fasttext::DenseMatrix>::def(pybind11::detail::initimpl::pickle_factory<Args...> &&,const Extra ...)" sein
      C:\Users\merklbe1\AppData\Local\Temp\pip-build-env-o8qjymlk\overlay\Lib\site-packages\pybind11\include\pybind11\pybind11.h(1671): note: oder "pybind11::class_<fasttext::DenseMatrix> &pybind11::class_<fasttext::DenseMatrix>::def(pybind11::detail::initimpl::factory<Args...> &&,const Extra ...)"
      C:\Users\merklbe1\AppData\Local\Temp\pip-build-env-o8qjymlk\overlay\Lib\site-packages\pybind11\include\pybind11\pybind11.h(1664): note: oder "pybind11::class_<fasttext::DenseMatrix> &pybind11::class_<fasttext::DenseMatrix>::def(const pybind11::detail::initimpl::alias_constructor<Args...> &,const Extra ...)"
      C:\Users\merklbe1\AppData\Local\Temp\pip-build-env-o8qjymlk\overlay\Lib\site-packages\pybind11\include\pybind11\pybind11.h(1657): note: oder "pybind11::class_<fasttext::DenseMatrix> &pybind11::class_<fasttext::DenseMatrix>::def(const pybind11::detail::initimpl::constructor<Args...> &,const Extra ...)"
      C:\Users\merklbe1\AppData\Local\Temp\pip-build-env-o8qjymlk\overlay\Lib\site-packages\pybind11\include\pybind11\pybind11.h(1645): note: oder "pybind11::class_<fasttext::DenseMatrix> &pybind11::class_<fasttext::DenseMatrix>::def(const T &,const Extra ...)"
      C:\Users\merklbe1\AppData\Local\Temp\pip-build-env-o8qjymlk\overlay\Lib\site-packages\pybind11\include\pybind11\pybind11.h(1620): note: oder "pybind11::class_<fasttext::DenseMatrix> &pybind11::class_<fasttext::DenseMatrix>::def(const char *,Func &&,const Extra ...)"
      python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(186): note: "pybind11::class_<fasttext::DenseMatrix> &pybind11::class_<fasttext::DenseMatrix>::def(const char *,Func &&,const Extra ...)" erwartet, dass 3 Argumente - 1 angegeben werden.
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fasttext
Failed to build fasttext
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (fasttext)

R

**Comment by bmerkle** [comment]
unfortunately yes. I installed fasttest-wheel successfully (version 0.9.2) 
but installing  "deepchecks[nlp-properties]" seem to autopull version 0.9.3 (which does not exisit as prebuild version. 

Can I specify the version 0.9.2 somewhere for the deepchecks install ?

(venv) C:\work\llm-eval-frameworks\samples>pip show fasttext-wheel
Name: fasttext-wheel
Version: 0.9.2
Summary: fasttext Python bindings
Home-page: https://github.com/facebookresearch/fastText
Author: Onur Celebi
Author-email: celebio@fb.com
License: MIT
Location: C:\work\llm-eval-frameworks\venv\Lib\site-packages
Requires: numpy, pybind11, setuptools
Required-by:

**Comment by bmerkle** [comment]
I tried the following workaround and this seems to work
```
pip install "deepchecks[nlp-properties]" --no-deps
pip install fasttext-wheel
```

**Comment by bmerkle** [comment]
i looked into `requirements/nlp-prop-requirements.txt` but this file already contains the valid code 
`fasttext>=0.8.0, <0.9.3`
so i think in the next release this problem should be fixed ?

https://github.com/deepchecks/deepchecks/blob/bbe56420a85eb07448defb2077f13f6c650bad43/requirements/nlp-prop-requirements.txt

**Comment by JKL98ISR** [comment]
Yes, we will have a release soon - also it is possible to install via main branch i.e `pip install git+https://github.com/deepchecks/deepchecks`
Glad you found a workaround.
