### ISSUE TITLE
feature importance crashes if not supplied with a standard sklearn model

### ISSUE THREAD

**Issue by benisraeldan** [deepchecks/deepchecks#371]
>TypeError: If no scoring is specified, the estimator passed should have a 'score' method. The estimator my_dumb_model() does not.

permutational importance assumes model has `fit` and `score` attributes. We need to check if it has these attributes.
If it does not have a score function, use a default from the assumed task type.

**Comment by noamzbr** [comment]
@benisraeldan Just to clarify - this does work on the standard models we support right? (sklearn, lightgbm, catboost, xgboost)
