### ISSUE TITLE
Output Result of Full Suite In PDF / HTML

### ISSUE THREAD

**Issue by jonathanbd135** [deepchecks/deepchecks#386]
Hi,

This tool is excellent. 
Is there a way to generate a report of the full suite? (i.e. in pdf / ppt / any other format that can be presented not in a notebook but sent by mail to managers etc after a model training / research).

**Comment by noamzbr** [comment]
Hi @jonathanbd135, thanks for the suggestion! We're indeed intending to add the option to output suite results to pdf / html. 
In the meanwhile, you can use the "Export as" functionality provided by jupyter. It only requires a few additional dependencies, detailed [here](https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.).
