### ISSUE TITLE
Running suite in collab throws an execption

### ISSUE THREAD

**Issue by AlmogBaku** [deepchecks/deepchecks#416]
```python
suite.run(train_dataset=ds_train, test_dataset=ds_test, model=rf_clf)
```

<img width="1406" alt="Screen Shot 2022-01-02 at 19 54 30" src="https://user-images.githubusercontent.com/98982/147884833-1b968f49-c2bf-476a-8e1a-0be23ae49c0b.png">

**Comment by ItayGabbay** [comment]
This was fixed since we migrated ROC curve to plotly from matplotlib.
