### ISSUE TITLE
[BUG] calcualting permutational feature importance takes too much time 

### ISSUE THREAD

**Issue by benisraeldan** [deepchecks/deepchecks#420]
on a complex model with a large dataset (30+ features with 20k+ samples) permutational importance ran for over 30 minutes. 

options:
 - limit time we calculate feature importance
 - flag to decide if we run feature importance or not
 - find faster algorithm to calculate feature importance

**Comment by noamzbr** [comment]
Currently resolved by _PERMUTATION_IMPORTANCE_TIMEOUT
