### ISSUE TITLE
[Feature] label field should be able to get label column name and label series

### ISSUE THREAD

**Issue by benisraeldan** [deepchecks/deepchecks#423]
### Currently
`Dataset` object can get both `label` and `label_name` as parameters.

### suggestion
The parameter `label` should be able to get a `pd.Series` and identify it as such and also be able to get a `string`/`int` and identify it as column in the DataFrame

(same for `index` and `date`)

**Comment by matanper** [comment]
this is problematic, since we add series to dataframe we need a column name. that's what label + label_name can be used together for. and it doesn't make sense to allow both of them to accept string
