### ISSUE TITLE
Model error analysis improvments

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#429]
1. I would expect to see the total accuracy of the model over the whole dataset, in order to compare how good/bad the segment in respect to the total performance.
2. We need to capitalize the y axis in the chart.

![image](https://user-images.githubusercontent.com/20860465/147909436-2637e007-b65c-4599-83a0-a299ca6b5883.png)

**Comment by noamzbr** [comment]
Also, need to improve the segmentation heuristic for categorical features
