### ISSUE TITLE
Progress bar stops if warnings are printed (and then continues in a separate instance)

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#477]

**Comment by nirhutnik** [comment]
![image](https://user-images.githubusercontent.com/92314933/148069358-9d8d9061-c951-452f-b100-b1e36eaa6ef5.png)

**Comment by ItayGabbay** [comment]
@JKL98ISR what's your take on this?

**Comment by JKL98ISR** [comment]
This only happens if widgets are disabled and we can't do nothing about it other then to solve all the warnings (some aren't under our control).
I will open an issue about those warnings and close this issue.
