### ISSUE TITLE
Trust score description is not clear enough

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#482]
As a user that is not familiar with trust score concepts, I can't understand what this check does. 

![image](https://user-images.githubusercontent.com/20860465/148077090-5317499a-2a85-4b3a-8215-f4c2ce531ca5.png)

**Comment by matanper** [comment]
I don't think there is a lot to do here. we don't want to write a long text, it doesn't fit in the suite and the user won't read it. the only option I think of is to have section about it in the documentation and put a link to there
