### ISSUE TITLE
Received unclear error while running the ModelErrorAnalysis check

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#502]
**Describe the bug**
Received unclear error while running the ModelErrorAnalysis check 

**To Reproduce**
Run the check using CatBoostClassifier

**Expected behavior**
A clear output of what I can change to run the check or a result

**Screenshots**
![Screen Shot 2022-01-05 at 12 47 28](https://user-images.githubusercontent.com/26321553/148210189-c9b76436-e5fc-4ad8-b763-2108aa2a70d2.png)

**Environment (please complete the following information):**
 - OS: mac osx
 - Python Version: 3.8
 - Deepchecks Version: 0.1.3

**Comment by matanper** [comment]
that's a legit error.
@noamzbr

**Comment by noamzbr** [comment]
resolved by #561
