### ISSUE TITLE
[FEAT] Visualization of Regression Systematic Error box plot unclear

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#527]
**Is your feature request related to a problem? Please describe.**
Visualization of Regression Systematic Error box plot unclear

![Screen Shot 2022-01-06 at 16 14 53](https://user-images.githubusercontent.com/26321553/148396690-7115e4e1-c81b-4458-81c7-f0d074db6990.png)

**Describe the solution you'd like**
Labels to be shorter and not sideways. Also labels are unclear.

**Comment by noamzbr** [comment]
Hi @JKL98ISR, can you be more specific about what is unclear about the labels? Other two comments I agree.

**Comment by ItayGabbay** [comment]
@yromanyshyn let's make the labels a bit shorter

**Comment by yromanyshyn** [comment]
@noamzbr @ItayGabbay @JKL98ISR 
is this expected (screenshot)?
![image](https://user-images.githubusercontent.com/71635444/148742564-a0a88b7e-9655-4648-bbc0-809926560e51.png)
