### ISSUE TITLE
Wrong BSD license tag in the distribution

### ISSUE THREAD

**Issue by jond01** [deepchecks/deepchecks#532]
Although you clearly state in the repository that the software is licensed under AGPLv3, you do not explicitly specify the license type in the `setup.py` script. The license metadata is then derived from a wrong classifier: 
https://github.com/deepchecks/deepchecks/blob/7974e66d95358f4bccdd2ea16591b98e1ae74529/setup.py#L114

It's reflected in the [PyPI](https://pypi.org/project/deepchecks/) distribution:
![image](https://user-images.githubusercontent.com/36337649/148455950-abdd6865-9bf6-473a-88f4-3e86efa925a8.png)

**Comment by ItayGabbay** [comment]
@jond01 thanks for paying attention letting us know.
PR #536 fixed that and the correct license will show up on PyPI in the next release.
