### ISSUE TITLE
[FEAT] Add force permutation option in UnusedFeatures check

### ISSUE THREAD

**Issue by ShaharKSegal** [deepchecks/deepchecks#553]
`UnusedFeatures` looks for the feature importance attr if possible, which is bias in some [sklearn models](https://explained.ai/rf-importance/).
I suggest adding an option to override this behaviour. This is already an option in `.utils.features.calculate_feature_importance`.

**Comment by noamzbr** [comment]
Thanks for the suggestion @ShaharKSegal. 
Because we are using lru cache to compute the FI only once, we should also enable a global flag (similar to _PERMUTATION_IMPORTANCE_TIMEOUT) that forces all FI calculations for to use permutation importance.

**Comment by matanper** [comment]
Is that an axiom? A user will always want the FI option to be the same across all checks?

**Comment by noamzbr** [comment]
My axiom is that permutation importance is always better than the internal sklearn one (as @ShaharKSegal said), so if we computed it once for some reason, makes sense that all other checks should use this result as well

**Comment by shir22** [comment]
Shouldn't this force permutation importance yes/no be somehow integrated in the model context structure?
