### ISSUE TITLE
Update error handling and display

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#561]
For all errors that are related to "metadata not relevant" - e.g. not a boosting model, no date/index column, etc. - make it a different type of error and update suite text to be something that doesn't sound like an error

For example, instead of - `DeepchecksValueError: Expected model to be a type from ['regression'], but received model of type: multiclass`
maybe something like: Check relevant for models of type ['regression'], received model of type 'multiclass'.

**Comment by noamzbr** [comment]
Also include in that DeepchecksTimeoutError & DeepchecksProcessError
