### ISSUE TITLE
[FEAT] Skip plots if error encountered rather than breaking

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#609]
Currently if the check is creating plots for several features by iterating over them, and an error is encountered during the plot method, the whole check exits. This happens for example in Feature Drift. 

Desired behavior:
Continue to plot and show the plots that did succeed, and print an error message instead of failed graphs.

**Comment by matanper** [comment]
Does the exception occurs while creating the graphs or while displaying them?

**Comment by JKL98ISR** [comment]
I think it's better to check why some plots are failing instead

**Comment by JKL98ISR** [comment]
could not reproduce
