### ISSUE TITLE
[FEAT] earth movers distance with nan values

### ISSUE THREAD

**Issue by vl123456** [deepchecks/deepchecks#617]
Using **input data containing missing values** with **earth movers distance**

it seems that when we use PSI, deepchecks tackle nan values (ignoring them)
while when we use earth movers distance, the result is `nan`

in the file deepchecks\checks\distribution\dist_utils.py l. 123-128
```python
train_dist = train_column.dropna().values.reshape(-1)
test_dist = test_column.dropna().values.reshape(-1)

 if column_type == 'numerical':
        scorer_name = "Earth Mover's Distance"
        score = earth_movers_distance(dist1=train_column.astype('float'), dist2=test_column.astype('float'))
``` 
Why do we use `train_column` and not `train_dist` ? Are there any reason I missed that would justify to use data with `nan`? 

if not, I suggest this correction
```python
        score = earth_movers_distance(dist1=train_dist.astype('float'), dist2=test_dist.astype('float'))
``` 

Thanks !

**Comment by noamzbr** [comment]
Thanks for catching this @vl123456! This was recently closed by #612 .
