### ISSUE TITLE
[Docs] Documentation: Switch the position of the links for Earth Movers Distance and Population Stability Index

### ISSUE THREAD

**Issue by chelseatroy** [deepchecks/deepchecks#620]
Package Version: stable

On [this page](https://docs.deepchecks.com/en/stable/api/checks/generated/deepchecks.checks.distribution.train_test_feature_drift.TrainTestFeatureDrift.html#), the order of the links for Earth Mover's Distance and PSI should be switched.

So it's currently

Check calculates a drift score for each column in test dataset, by comparing its distribution to the train dataset. For numerical columns, we use the Earth Movers Distance. See https://www.lexjansen.com/wuss/2017/47_Final_Paper_PDF.pdf For categorical columns, we use the Population Stability Index (PSI). See https://en.wikipedia.org/wiki/Wasserstein_metric.

And it should be

Check calculates a drift score for each column in test dataset, by comparing its distribution to the train dataset. For numerical columns, we use the Earth Movers Distance. See https://en.wikipedia.org/wiki/Wasserstein_metric. For categorical columns, we use the Population Stability Index (PSI). See https://www.lexjansen.com/wuss/2017/47_Final_Paper_PDF.pdf.

**Comment by ItayGabbay** [comment]
@chelseatroy Thanks for your issue. It is now resolved and will be deployed in the next release.
