### ISSUE TITLE
[FEAT] Implement to_json() and from_json() for suite output

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#622]
As an enabler to save suite results and later work with them in various manners (in UI / reproduce it in notebook / compare it with code...)
This json should include all suite outputs
and also check results for each check (the json result, even though it's not directly parsed in the suite, to enable further processing by user)

**Comment by noamzbr** [comment]
Note: in order to reproduce - this needs to contain also the suite definition.
