### ISSUE TITLE
[FEAT] Add testing to display functions

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#627]
**Is your feature request related to a problem? Please describe.**
There are no tests for the display functions

**Describe the solution you'd like**
Adding tests

**Comment by JKL98ISR** [comment]
@benisraeldan need to add test for suite display too

**Comment by yromanyshyn** [comment]
@ItayGabbay PR #1279 already includes tests for all serializers

**Comment by ItayGabbay** [comment]
@yromanyshyn cool! Please mention this issue in your PR
