### ISSUE TITLE
[FEAT] Example notebook with MyST

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#631]
Goal:
Currently the checks example notebooks and the guides are long and full of content. We wish to make the experience viewing them more convenient. Because of that, let's try MyST to convert one of the notebooks and then add features like collapisble cells, notes, and more.

@shir22 has a lot of ideas regarding this feature

**Comment by shir22** [comment]
Currently on hold for the sphinx gallery option. if we proceed with it, this issue should be closed

**Comment by noamzbr** [comment]
Closed in place of #921
