### ISSUE TITLE
[BUG] load_fitted_model() for datasets in package raises a warning 

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#633]
**Describe the bug**
load_fitted_model raises a warning of different sklearn version. for an example see the quickstart notebook

**Expected behavior**
The warning shouldn't appear

**Environment (please complete the following information):**
 - OS:  MacOS (google colab)
 - Python Version: 3.9
 - Deepchecks Version: 0.2.1

**Additional context**

**Comment by shir22** [comment]
IMO best is to load model - if it's the same version and otherwise train on the spot
(or alternatively if it's quick then always train on the spot)

note that this is for all "load_fitted_model" functions
