### ISSUE TITLE
[FEAT] Automatically deduce output format

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#634]
When running inside a jupyter kernel - output should be displayed inside the jupyter cell

When running on terminal/vscode/pycharm/other non-kernel envs - the output should be saved in the working directory of the user.

Important: Don't forget to write about this functionality in the docs, loud and clear.

**Comment by matanper** [comment]
If we will remove the auto-show does it is still needed?

**Comment by JKL98ISR** [comment]
the output is auto showing because of the jupyter, it doesn't break anything using not visual ide.

**Comment by matanper** [comment]
> the output should be saved in the working directory of the user.

It's not about whether it breaks, it's about user guidance. The user should know he has the ability to save the output as file. @ItayGabbay is leading the idea, so this issue he opened looks incompatible

**Comment by ItayGabbay** [comment]
As agreed we'll have a show() function, and if the user calls the show() function inside a non-interactive python scope - a warning will be raised.
