### ISSUE TITLE
[FEAT] add links to check examples to each check's one line description (Read More...)

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#647]

**Comment by shir22** [comment]
1. Is there a way to have these links pointing to the relevant version? (otherwise links may be broken if we update checks / structure....)
2. links should have following utm parameters (appended to the end of the url)
?utm_source=display_output&utm_medium=referral&utm_campaign=check_link

**Comment by JKL98ISR** [comment]
won't links pointing to the latest be enough in most cases or even better?
