### ISSUE TITLE
Robustness check

### ISSUE THREAD

**Issue by nirhutnik** [deepchecks/deepchecks#678]
Input: dataset & model

Check:
Add corruption (eg. short noise, impulse noise, rotation) to images and compare how much the model predictions changes before & after. Also, compare the model performance.

Output:
Value: dict[corruption, scorer(data)-scorer(corrupt_data)]
Display: 
Table with summary of corruptions and decrease in metric
For each corruption, show 2 sets of images - one where the model was confused by the corruption and one where it was successful.

**Comment by noamzbr** [comment]
Remaining tasks:
- [ ] Add imgaug augmentations
- [ ] Add to the notebook an explanation of the requirements to run this check
- [ ] Fix randomity issues in tests
- [ ] Improve the display

**Comment by noamzbr** [comment]
Specific ideas for improving the display by @Eranpaz:
1. In the first plot (compare original performance to augmented performance) - it's not clear that the % is "decline compared to origin" and not compared to "perfect performance". Should make it more visually clear or write it.
2. Least affected class is also interesting to know (especially when running on Training data)
3. The name of the augmentation is grouped together with the last plot of the previous augmentation, so the scrolling doesn't work well (see e.g. https://docs.deepchecks.com/en/latest/examples/vision/guides/quickstart_in_5_minutes.html)
4. Show images with most severe degradation.
