### ISSUE TITLE
[Docs] Documentation contains a mistake.

### ISSUE THREAD

**Issue by chelseatroy** [deepchecks/deepchecks#723]
Package Version: stable

Page:
https://docs.deepchecks.com/en/stable/examples/checks/methodology/single_feature_contribution_train_test.html

Text says "For further information about PPS you can visit the ppscore github or the following blog post: RIP correlation. Introducing the Predictive Power Score." However, neither piece of text is linked. 

So it should be:

For further information about PPS you can visit the [ppscore github](https://github.com/8080labs/ppscore) or the following blog post: [RIP correlation. Introducing the Predictive Power Score](https://towardsdatascience.com/rip-correlation-introducing-the-predictive-power-score-3d90808b9598).

**Comment by NaincyKumariKnoldus** [comment]
Hey @chelseatroy Can I do this please?
