### ISSUE TITLE
[FEAT] move drift title to before score bar

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#729]
Currently the name of the feature is displayed below the bar, and it should be above it - to make it clear what the bar is displayed for 

![image](https://user-images.githubusercontent.com/17730502/150779484-9a803a5e-a123-4412-9395-55ecb128f387.png)

**Comment by shir22** [comment]
@noamzbr should this one be marked closed by a PR from the cv milestone?

**Comment by noamzbr** [comment]
closed by #867

**Comment by noamzbr** [comment]
closed by #867
