### ISSUE TITLE
[BUG] bad support for predicting on Series, currently all predictions are done on DataFrame

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#761]
**Describe the bug**
bad support for predicting on Series, currently all predictions are done on DataFrame
models that expect
 
**To Reproduce**
use the following model on the full suite or any check that uses model

```
clf = Pipeline([
    ('vect', CountVectorizer(max_features = 10000, ngram_range = (1,2))),
    ('tfidf', TfidfTransformer(norm = 'l2')),
    ('clf', RandomForestClassifier(n_jobs=-1)),
])
```

**Expected behavior**
prediction to run on series and not dataframe

**Screenshots**
![image (29)](https://user-images.githubusercontent.com/26321553/151178168-fc213053-b1dd-4875-af29-43c9c9e7b676.png)

**Environment (please complete the following information):**
 - OS: mac 
 - Python Version: 3.8
 - Deepchecks Version: 0.3.2

**Comment by matanper** [comment]
Is this related to us? we are using directly the `model.predict` method

**Comment by JKL98ISR** [comment]
We are not supporting Pipelines that need to receive a Series.
We recommend using a FunctionTransformer in the Pipeline to convert a dataframe to a series
