### ISSUE TITLE
[BUG] Incorrect documentation of CategoryMismatchTrainTest.add_condition_new_category_ratio_not_greater_than

### ISSUE THREAD

**Issue by hsafer** [deepchecks/deepchecks#765]
**Describe the bug**
The documentation for 
[CategoryMismatchTrainTest.add_condition_new_category_ratio_not_greater_than](https://docs.deepchecks.com/en/latest/api/generated/deepchecks.checks.integrity.CategoryMismatchTrainTest.html#:~:text=CategoryMismatchTrainTest.add_condition_new_category_ratio_not_greater_than(%5B...%5D))  
says  
"given number of different new categories"  
but it should say something like  
"given fraction of instances with different new categories."

**Comment by shir22** [comment]
Adding here something similar:
load_data method of **all built-in (tabular) datasets** has an inconsistency between what's written in signature and in parameters, for parameter as_train_test
Should be fixed to be True for all
![image](https://user-images.githubusercontent.com/33841818/159283681-835aba0d-4149-4274-8771-d877c80677dc.png)
