### ISSUE TITLE
[BUG] we don't infer sentences as categorical feature

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#772]
**Describe the bug**
we don't infer sentences as categorical features

**To Reproduce**
use a feature that is sentences

**Expected behavior**
Infer as categorical or at least not numerical

**Screenshots**
![Screen Shot 2022-01-27 at 15 02 05](https://user-images.githubusercontent.com/26321553/151364437-e97823a7-e19d-4d16-8f5c-d6f9697365dd.png)

**Environment (please complete the following information):**
 - OS: mac
 - Python Version: 3.8
 - Deepchecks Version: 0.4

**Comment by benisraeldan** [comment]
This should be discussed, because in most cases, if there are a large variety of texts this data isn't categorical, but free text

**Comment by nirhutnik** [comment]
Agree with Dan. Also, on which data did this happen?

**Comment by JKL98ISR** [comment]
> I think, if it isn't categorical and isn't numeric these columns should be skipped on some checks

after a quick check you're right, but it will cause a refactor with sometimes harder logic.
if this case doesn't happen too much I think we either postpone support because no check is really to good for it rn.
