### ISSUE TITLE
[FEAT][CV] Distribution analysis and heatmap for object detection labels

### ISSUE THREAD

**Issue by eladrich** [deepchecks/deepchecks#777]
Deepchecks contains some really useful distribution analysis for class labels. When extending to object detection labels there are some additional analysis that could be very helpful
1. Distributions of detection properties (i.e. object size, aspect ratio)
2. Heatmap showing the relative location of objects in the image

Both of the above could also be splitted by train/test or class label, helping a researcher see whether there's a specific class with irregular properties.

**Comment by noamzbr** [comment]
Point number 1 is being added in #879 and by a future check detailed in #858 
Point number 2 - a PR will follow shortly.
