### ISSUE TITLE
[BUG] TrainTestFeatureDrift not showing features sorted by feature importance

### ISSUE THREAD

**Issue by DL1992** [deepchecks/deepchecks#811]
**Describe the bug**
When running TrainTestFeatureDrift on breast cancer dataset from the module the results are different than expected.
the test writes that the features will be shown according to their FI in a sorted way but, the 5 features shown are not the top 5 FI.
one of them is the 10th, and they are not sorted

**To Reproduce**
1. load breast cancer train and test
2. transform to Dataset
3. load fitted model
4. run TrainTestFeatureDrift
**Expected behavior**
the features shown should be sorted by FI and should be the first 5 FI features

**Screenshots**
![image](https://user-images.githubusercontent.com/21197955/152384226-5b79dbff-502c-4f80-8501-e66299fe0dc0.png)
![image](https://user-images.githubusercontent.com/21197955/152384281-a9edac73-2903-4ed0-b542-042973315337.png)

**Environment (please complete the following information):**
google colab
latest deepcheck version as of 3.2.22

**Comment by noamzbr** [comment]
Hi @DL1992, thanks for raising this issue! We've found out that this bugs occurs due to ties in the feature importance of that specific model, which messes with the ordering.
![image](https://user-images.githubusercontent.com/17730502/152678493-bff7b756-2d36-4057-b2f8-6822db73dad4.png)
