### ISSUE TITLE
[BUG] sidebar disappears when navigating suites

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#815]
No sidebar while navigating suites in API reference:
![image (17)](https://user-images.githubusercontent.com/33841818/152454987-cae6a8d1-163e-4673-ace9-b199ab9db2af.png)
![image (18)](https://user-images.githubusercontent.com/33841818/152454989-e4ddad27-3626-49c9-89ac-2fd0868834c5.png)

Currently in version 0.4.x

Also:
How can we vefiry this doesn't recur in any place in docs?

**Comment by yromanyshyn** [comment]
I do not encounter this problem, nor with 0.4.0 nor with 0.4.2:
![Screenshot from 2022-02-09 09-31-57](https://user-images.githubusercontent.com/71635444/153143135-af906880-2aad-4b45-97de-31fbaf5ccf06.png)
![Screenshot from 2022-02-09 09-30-01](https://user-images.githubusercontent.com/71635444/153143141-2882d012-a254-4649-9a7d-33d50322ec7b.png)

**Comment by shir22** [comment]
Indeed resulted fro a temporary bug in local build, that was solved prior to final deployment, closing issue
