### ISSUE TITLE
[CV] Develop common image measurements 

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#839]
Many future checks are going to need to extract properties / measurements / features of images, either for finding drift / outliers along these features or for using them for detecting leakage. For that, it would be useful to have a common way of calling methods that extract these features, and have a list of already implemented measurements. 

Example for measurements:
1. dimensions
2. color histogram
3. brightness
4. contrast?
5. sharpness

**Comment by ItayGabbay** [comment]
Are we going to have these on the ImageFormatter?
