### ISSUE TITLE
[FEAT][CV] Treat multiple labels in performance report

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#852]
Currently, metrics are calculated per class and displayed per class. In cases when there are many classes (e.g. > 30), we want an alternative way of inspecting metrics only for specific classes.

Current idea:
1. Have a per_class flag, default=True, to enable also displaying not per class
2. Have a n_to_show=20 arg, to control how many classes to show.
3. show_only = 'largest' arg, which controls the method by which the classes to show are selected. Can be either a list (assumed to be list of classes to show), or "largest", "smallest", "random", "best", "worst". Other ideas are welcome.

**Comment by ItayGabbay** [comment]
@noamzbr what will happen on ClassPerformance(per_class=False)?
