### ISSUE TITLE
[FEAT] Formatters validation for users.

### ISSUE THREAD

**Issue by matanper** [deepchecks/deepchecks#854]
Right now we have some internal validations we run inside the check to test the formatters returns a valid input. But those validations are not accessible to the users. While a user is writing formatters (which might take time) he needs an easy way to validate his work and not work blindly.

Solution: add a single function which gets the formatters and validates them. Possibly on vision data class

**Comment by noamzbr** [comment]
I would add that the validation should later on be visualized - so that the user sees that he's getting the correct results. 
For example, the image should be displayed using image formatter, or the label bbox should be visualized on the image.
