### ISSUE TITLE
[FEAT][CV] Find outliers in image properties

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#911]
Presenting images that are outliers in image properties (such as size, color, brightness etc.) may be very useful. Use an algorithm similar to the one used in #756 to make a check showing outlier images across the image properties.

Optional - add a flag to find classes which are on average outliers across image properties.

**Comment by nirhutnik** [comment]
### DoD:
Check that returns image ids of outliers by class / general and displays the images. Outliers are by label / image properties (can be both?)

### Check variables:
* by_class - flag for whether calculation should be by class or not
* outlier_threshold
* sample_size - relevant only if not saving all of the data but instead inferring the distribution based on sample
* n_show_top - like in other checks
* alternative_properties

### Check display:
* per property (and per class if flagged), show X outlier images and their outlier value (and the general distribution, maybe as KDE graph)

### Tasks:
* Create outlier criteria. As this is 1D data, can use either IQR or 3*std methods. 
* Run check on image properties, save distributions per class.
** Can estimate distribution from sample and afterwards just record the outliers - Ask Gabbay if needed
* Save outliers ids (how? do we have that data? Ask Matan)
* print outliers per property
