### ISSUE TITLE
[FEAT][CV] Vision model error analysis

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#915]
In the tabular package, the model error analysis check automatically detects segments in which the model error is high. In the vision package, this can be done based on the image properties. Otherwise, check should be pretty much the same.

**Comment by nirhutnik** [comment]
### DoD:
check, notebook and tests. Logic exactly like in ModelErrorAnalysis but in vision.

### Inputs
Same 
+ Alternative properties (default: image properties)

### Outputs
Same
+ Under each feature, show 1-3 examples of images per segment

### Tasks:
* Move most logic from ModelErrorAnalysis to a common utils and check that works
* Create check by using the same utils but with image properties
