### ISSUE TITLE
[FEAT][CV] Write a first "usage example" notebook

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#916]
In the tabular package we often included in the check notebook an example of a usecase in which the check brings some distinct value. For example, in the trust score notebook we create concept drift that is detected in way of decrease in average confidence.

We want to have similar examples for the vision package - for example, create a case in which the property drift check finds a distinct drift along some property between train and test (preferable, one that affects the performance). This task is about creating the first of these examples and setting the standard.

**Comment by shir22** [comment]
We should clarify if we are aiming to edit and improve the current example notebooks for the existing checks, or write separate usage example notebooks

**Comment by noamzbr** [comment]
I think we should aim to edit and improve - to the same standard we have in the tabular subpackage.
