### ISSUE TITLE
[FEAT][CV] Segment performance according to image / label properties.

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#917]
Currently, the class performance check shows performance per class.

We want the option to segment the performance according to additional properties, such as image or label properties. 
Implementation can be either enabling to select some other property to segment the performance, or alternatively letting the user select two such properties and showing the resulting performance in a grid, similar to the segment performance check in tabular.

**Comment by shir22** [comment]
Lets start with 1D (if good feedback - 2D is a good additional future check). Also 1D doesn't require choosing the properties and can be done for many together (or a chosen subset / custom) and then display the most relevant/interesting.
