### ISSUE TITLE
[FEAT] Suite/Check dynamic output format - streamlit

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#918]
Explore streamlit (also other alternatives can be relevant), as a replacement for the simple html option for displaying outputs dynamically

Show demo for enabling dynamic display of saved suites and/or checks (choosing from saved)
and for how this can enable comparing two runs (of suites/checks)

**Comment by shir22** [comment]
https://docs.google.com/document/d/1AqTF8FtggGo60sjrgBVoQ0jb-Cx0km0VxzSs47EASyk/edit

**Comment by matanper** [comment]
What's the functionality we are trying to improve in this issue?
Comparing suites/checks runs?

**Comment by SoulEvill** [comment]
marked - I also agree streamlit is a great way to display results, especially for comparison and the current report is quite lengthy, Utilizing streamlit can have a better interface to display more dynamically.

**Comment by noamzbr** [comment]
Exploration and examples were done. An actual feature will be developed in #1000.
