### ISSUE TITLE
[FEAT] Cache batch predictions and labels after transformation

### ISSUE THREAD

**Issue by benisraeldan** [deepchecks/deepchecks#922]
**Is your feature request related to a problem? Please describe.**
batches are passed to checks in a suite as tensors and we currently use the context to cache these values. this makes it complicated to use labels and predictions and also that they are not cached and need to be run each check

**Describe the solution you'd like**
Create a Batch object to pass to the checks which wraps the tensors and caches the predictions and labels after transform. This will also simplify the access: 
batch.labels
batch.predictions

**Describe alternatives you've considered**
save on context is uglier and less simple to use

**Comment by noamzbr** [comment]
Also, it's worth while to cache label/prediction and image properties so they will not be calculated multiple times for each batch
