### ISSUE TITLE
[DOCS] Go over list of documentation suggestions and draw conclusions and fixes

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#923]
List in #919

DoD:
1. Immediate suggestions and bugs should be fixed
2. More elaborate/complex options - should be "digested" and written as new issues for future milestone

**Comment by shir22** [comment]
List in #919

**Comment by noamzbr** [comment]
Closed previous issue, doc is here:
https://docs.google.com/document/d/1FXKRqMmlp3JyRAo7QJE0JAFhXmhzuQTzTryeAdwt6wU/edit?usp=sharing
