### ISSUE TITLE
[BUG] Json import throws exception

### ISSUE THREAD

**Issue by matanper** [deepchecks/deepchecks#928]
1. We have double export of json when exporting suite result as json. First the check results dumps as json, and then the suite result. the dump should happen only once.
2. Our docs mentions to use `json` to load results but when loading with json we get jsonpickle dicts:
`{'py/tuple': ['html', '<b>some text</b>:']}` and when loading jsonpickle some of the results throws exception `TypeError: the first argument must be callable`

Steps to reproduce:
Run full suite on iris dataset (tabular) and then try to export and import:
```
result = suite.run(train_dataset=ds_train, test_dataset=ds_test, model=rf_clf)
str = result.to_json()

jsonloaded = jsonpickle.loads(str)
for s in jsonloaded['results']:
    print(jsonpickle.loads(s))
```

**Comment by JKL98ISR** [comment]
It is the intended behavior, after you unpickle a json you can't unpickle it's content.

**Comment by ItayGabbay** [comment]
to_json shouldn't output an HTML output

**Comment by JKL98ISR** [comment]
not 100% sure what is the exact problem

**Comment by JKL98ISR** [comment]
couldn't reproduce the bug, only fix html in condition table
