### ISSUE TITLE
[FEAT] Formatter as classes

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#931]
**Is your feature request related to a problem? Please describe.**
The current problem is that the formatters object are not intuitive and hard to understand. we need to consider maybe to change it to class implementation instead of passing callbacks.

**Describe the solution you'd like**
The solution will be as follows:

- Remove the VisionData class and all of its usages
- Create 3 classes: `VisionTask`, `ClassificationTask`, and `DetectionTask`. The VisionTask class will contain base functionality that currently exists in the VisionData, for example  properties like `n_of_samples_per_class`, `to_display_data`, etc. In addition, it will contain the abstract function: `batch_to_images(batch)` that will replace the ImageFormatter. 
  - The `ClassificationTask` will contain classification-specific functionality, in addition to default formatter for classification. (`batch_to_labels`, `infer_on_batch`).
  - The `DetectionTask` will contain detection-specific functionality, in addition to utilities for converting bboxes format to our required format (Currently this logic exists in the DetectionFormatters). It will also contain the default formatters (`batch_to_labels`, `infer_on_batch`).

In order to run a suite/check, the user will HAVE to implement a class that inherits from the relevant task, and override the 3 "formatter" functions: `batch_to_images`, `batch_to_labels`, `infer_on_batch`.

**Comment by shir22** [comment]
will 
`batch_to_images`, `batch_to_labels`, `infer_on_batch`
receive all of the batch or only the relevant values (e.g. only the data relevant for the labels for that purpose)?
asking to verify clarity of the names of the methods

**Comment by matanper** [comment]
All of the batch, the direct result of doing `next(iter(data_loader))`
