### ISSUE TITLE
[BUG][CV] Class performance does not show classes by order

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#947]
See for example https://docs.deepchecks.com/en/latest/examples/vision/checks/performance/class_performance.html

1. should be sorted by class id/name ascending order
2. Class names are not shown correctly ("Class Name6", should be "Class 6")

**Comment by shir22** [comment]
about 1 -
Can we sort them in descending order according to size?
(that way this corresponds also with the argument of how many classes to show...)

**Comment by noamzbr** [comment]
A way to merge these ideas - Sort according to the sorting parameter we have in the "show_only" parameter
