### ISSUE TITLE
[FEAT][CV] Improve displays of all vision checks

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#967]
Most checks (specifically drift checks) can be expanded to give the user a better understanding of what is the source of the problem
For example, for image dataset drift (domain classifier) we can give examples for which the model has the most confidence they belong to one class or the other.

**Comment by nirhutnik** [comment]
Possible pitfall:

How do we show relevant images to domain classifier? we don't know which samples are relevant when running update() func

**Comment by noamzbr** [comment]
Opened #1015 #1016 and #1014 in it's stead.
