### ISSUE TITLE
[BUG] [Vision] improve numpy_to_html_image performance

### ISSUE THREAD

**Issue by benisraeldan** [deepchecks/deepchecks#990]
**Describe the bug**
results from profiling on quick start full suite:
run time | function
-- | --
185.434 | numpy_to_html_image  deepchecks/vision/utils/image_functions.py:59

which is a large portion of the robustness check. (330.995 seconds)

similar result from cprofiler:

calls | cumulative time | time per call | function
-- | --  | -- | -- 
98 |  175.785 | 1.794 | image_functions.py:59(numpy_to_html_image)

**To Reproduce**
1. run quick start until before `full_suite.run`, wrap it in a profiler (used cProfile and pyinstrument) and read the result 

**Expected behavior**
Run time should be shorter.

**Environment (please complete the following information):**
 - OS: Mac 
 - Python Version: 3.8
 - Deepchecks Version:  0.5.0-dev2

**Comment by yromanyshyn** [comment]
I do not see a reason why this function is using plotly to process the data/image instead of a more specialized package like Pillow, I think it is the main reason why it is slow/

@matanper  GitLens is saying that you added this function, is there some reason why you used plotly?

TODO:
- use Pillow instead of plotly to process the data/image

**Comment by matanper** [comment]
In the start, we used a whole figure to with subplots to create the layout, so we needed plotly traces. Then I changed the layout to be html-based and left plotly only the image creation (which we use also to draw labels & prediction bboxes on the image)

If it's possible to draw in Pillow we can use that in robustness but I don't know about other checks which uses the same functions to display heatmaps for example
